### ISSUE TITLE
where does the database file lies？

### ISSUE THREAD

**Issue by gooners1886** [cboxdoerfer/fsearch#102]
what is the location of database file of fsearch?

**Comment by cboxdoerfer** [comment]
Currently it is stored in `~/.config/fsearch/database` split into one database for each location. But that's about to change, it'll move to `XDG_CACHE_HOME/fsearch` into a single file for all locations.

**Comment by tjbrn** [comment]
Where is the current location?

**Arch Linux
Fsearch 0.1.4 (AUR-stable)**

```
# ls ~/.config/fsearch/
fsearch.conf

# ls ~/.cache/fsearch
No such file or directory
```

**Comment by cboxdoerfer** [comment]
It's in `$XDG_DATA_HOME/fsearch/fsearch.db`, so most likely in `~/.local/share/fsearch/fsearch.db`
