### ISSUE TITLE
PDF JPG Preview for fast fine selection in results

### ISSUE THREAD

**Issue by haasemailboxgmxde** [cboxdoerfer/fsearch#107]
The fastest way to refine a search from results list, like in the last Everything version too!
I think this will increase the workspeed by much similiar results. Nice to have. 

Thanks for this tool.

**Comment by cboxdoerfer** [comment]
Yes, that'd be a nice feature. The best way to implement that is probably with a plugin architecture. Then FSearch dependencies would remain small, but users still can install previewer plugins when they like.

However that feature isn't a high priority right now for me.

**Comment by cboxdoerfer** [comment]
Duplicate of #121, closing
