### ISSUE TITLE
Not compiling on Xubuntu 16.04

### ISSUE THREAD

**Issue by beatstick** [cboxdoerfer/fsearch#110]
I followed the build instructions for ubuntu but got these error messages upon running the command: ./autogen.sh

Please add the files
  codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
  progtest.m4
from the /usr/share/aclocal directory to your autoconf macro directory
or directly to your aclocal.m4 file.
You will also need config.guess and config.sub, which you can get from
ftp://ftp.gnu.org/pub/gnu/config/.

src/Makefile.am:71: warning: shell $(GLIB_COMPILE_RESOURCES: non-POSIX variable name
src/Makefile.am:71: (probably a GNU make extension)

Is there a workaround?
If I continue to /.configure I get the following errors:

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether NLS is requested... yes
checking for intltool >= 0.50.1... 0.51.0 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.22.1
checking for XML::Parser... ok
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/zero/Downloads/fsearch':
configure: error: C compiler cannot create executables
See `config.log' for more details

From the config.log:

gcc: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory
configure:3887: $? = 127
configure:3876: gcc -v >&5
gcc: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory
configure:3887: $? = 127
configure:3876: gcc -V >&5
gcc: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory
configure:3887: $? = 127
configure:3876: gcc -qversion >&5
gcc: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory
configure:3887: $? = 127
configure:3907: checking whether the C compiler works
configure:3929: gcc    conftest.c  >&5
gcc: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory

**Comment by cboxdoerfer** [comment]
I don't think there's anything I can do about that, there seems to be something wrong  with your system since gcc doesn't even start because of a missing libgsl library.

**Comment by beatstick** [comment]
I found a solution. I followed these steps found at: https://askubuntu.com/questions/647583/how-to-fix-configure-error-c-compiler-cannot-create-executables

    sudo apt-get install --reinstall build-essential

    sudo apt-get install --reinstall gcc

    sudo dpkg-reconfigure build-essential

    sudo dpkg-reconfigure gcc

Now gcc compiles as it should.

**Comment by al-mission-2016** [comment]
So, this #110 issue should be closed.

**Comment by cboxdoerfer** [comment]
Thx
