### ISSUE TITLE
Can't compile fsearch on Parabola Linux (syntax error near unexpected token `-std=c11,')

### ISSUE THREAD

**Issue by sda2b** [cboxdoerfer/fsearch#113]
Hello,

I have issues to compile fsearch on Parabola Linux.

./configure
```

checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
./configure: line 6461: syntax error near unexpected token `-std=c11,'
./configure: line 6461: `AX_CHECK_COMPILE_FLAG(-std=c11, CFLAGS+=" -std=c11" ,'
```

Thanks for your help.

EDIT : All needed dependencies are installed. I already compiled fsearch successfully on the same machine in September. I don't know why it fails.

**Comment by cboxdoerfer** [comment]
`AX_CHECK_COMPILE_FLAG` is provided by the autoconf archive. So probably `autconf-archive` (or whatever Parabola Linux calls that package) is missing.

**Comment by sda2b** [comment]
Thanks. It was missing for some reason. Maybe I removed it a few weeks ago. It compiles fine now.
