### ISSUE TITLE
FR: Integrate notmuch

### ISSUE THREAD

**Issue by gerroon** [cboxdoerfer/fsearch#117]
Hi

I realize this is a file search tool but it would be very handy also if it could search email files via using notmuch. Tjhis is optinonal since not every would be using notmuch to index their emails. 

thanks

**Comment by cboxdoerfer** [comment]
Can you describe in further details how this is supposed to work from the users point of view? E.g. do you need a command line interface to make that work and/or do you want FSearch to search the content of files?

**Comment by gerroon** [comment]
@cboxdoerfer 
Notmuch already provides all the necessary access to the email related search. I was thinking that Fsearch can additionallly use Notmuch bring results in the ui.

Fs normally searches files. Lets say I search for "dinosaur", it will bring all the files in that scope but also it can query Notmuch to search for "dinosaur" and display those results in the ui as well, with a distintion obviously, could be color, coould be underline to show that they were email results.

**Comment by cboxdoerfer** [comment]
Sorry for the late response. This seems out of the scope of this project, since I'd rather focus on file search exclusively.
