### ISSUE TITLE
"remember column configuration" does not work for sorting

### ISSUE THREAD

**Issue by sdx23** [cboxdoerfer/fsearch#118]
The sorting preference of columns is not remembered.

Steps to reproduce:
1. Edit Preferences, check box at "remember column configuration"
2. Change sorting, e.g. click twice on "date" to sort for most recent date (most used setting for me - maybe even a good default)
3. Close fsearch
4. Open fsearch again, sorting is by name

Version information
0.1 beta

**Comment by cboxdoerfer** [comment]
Yes, remembering column sort order is not implemented yet. Added to todo list.

**Comment by cboxdoerfer** [comment]
Duplicate of #67
