### ISSUE TITLE
Incorrect focus selection handling with instant search turned off

### ISSUE THREAD

**Issue by Erquint** [cboxdoerfer/fsearch#119]
Steps to reproduce:  
- Turn off the "search as you type" option.  
- Find something.  
- Select a result.  
- Select the query field. (Notice the result remaining selected)  
- Change or input new query.  
- Hit enter to search for it.  

Observed behavior:  
- The residual result selection prompts openning/executing of the result instead of a search operation.  

Expected behaviour:  
- A new search is performed.  

Found workaround:  
- Right-clicking on empty space (background) of the results list to de-select.  

Suggestions:  
- Make **selecting** the query input field de-select any search results. (*merely another workaround*)  
- Make **changing the contents** of the query input field de-select any search results.  
- Make **any interaction** with the query input field de-select any search results.

**Comment by cboxdoerfer** [comment]
I can't reproduce that. Which version do you use, i.e. how did you install FSearch?

**Comment by Erquint** [comment]
0.1+341+9~ubuntu17.10.1
Note that I'm using KDE(Kubuntu).  
Installed from your PPA.

**Comment by cboxdoerfer** [comment]
Is this bug still relevant? I still can't reproduce it.

**Comment by veksha** [comment]
just checked on my side. can't reproduce either.

**Comment by Erquint** [comment]
I'm not on Linux currently.
Can't confirm or deny.
If no one can reproduce — close it for the time being.
