### ISSUE TITLE
Doesnot remember my setting

### ISSUE THREAD

**Issue by nazar2sfive** [cboxdoerfer/fsearch#123]
![image](https://user-images.githubusercontent.com/12841320/36379808-10a5294c-15a8-11e8-99ce-230a796835a3.png)

The name of my files are usually longer so i make my column width longer.. But every time i close and reopen fsearch that width length is not remmebered and i have to increase that again.

**Comment by cboxdoerfer** [comment]
Do you have the setting enabled to remember column configuration?
