### ISSUE TITLE
Restore app window POSITION

### ISSUE THREAD

**Issue by al-mission-2016** [cboxdoerfer/fsearch#124]
Please remember/restore app window POSITION (the size is restored alright).
  In particular in "fsearch.conf" the following options could  be added:
        [Interface]
        restore_window_position=true
        window_position_x=0
        window_position_y=400
New options should be processed at startup alongside with "restore_window_size".
However, care should be taken to ensure that the window is within desktop rectangle.

Danke.

**Comment by cboxdoerfer** [comment]
Hm, I already thought to implement that, but I'm not so sure anymore if it makes sense to put this kind of code in an application. After all there are tools out there to move/resize windows which are also aware of multiple displays and many window managers also support this kind of functionality.

So this might happen at one point, but it is certainly no high priority for me right now.

**Comment by al-mission-2016** [comment]
OK, Christian. There is a controversy indeed about the question who is responsible for
storing window size/position - WM || app.

Thanks for hint anyway. I wrote a short bash script to start FSearch at place
I want to.

```
exec /usr/bin/fsearch &

# Wait necessary amount of time to ensure that fsearch main window popped up.
# This mainly depends on the size of FSearch database.
sleep 0.8;

# Find FSearch main window, make it active, then move\resize it.
xdotool search --class fsearch & \
xdotool getactivewindow windowsize 100% 33% & \
xdotool getactivewindow windowmove --relative x 400

```
