### ISSUE TITLE
Add support of MENU key to raise popup menu

### ISSUE THREAD

**Issue by al-mission-2016** [cboxdoerfer/fsearch#125]
Could you add support of MENU key (GDK_KEY_Menu) to raise popup menu for current active line in the search result list - same menu that popup on mouse right click event?

For that, one probably should process the GDK_KEY_Menu in file fsearch_window.c -> on_listview_key_press_event() adding all necessary machinery to invoke "right-click" popup menu.

Danke vielmals)

**Comment by cboxdoerfer** [comment]
Yes, I'll look into that.

**Comment by al-mission-2016** [comment]
Hi, Christian. Vielen dank.

But. It seems here is a bug or what?
New code raises popup menu for MENU_key, but pressing a key on any menu item either by keyboard or by mouse gives NOTHING. Popup menu is broken. :/

I compiled the code without the line src/listview_popup.c:151 and all works OK.
So, is it right place to put the g_signal_connec() there?!
That line of code emerges only in the last version.
Please fix it.
:)

**Comment by cboxdoerfer** [comment]
Thx for reporting. This is really weird, the g_signal_connect() is suggested by the GTK+ documentation, that's why I added it. I'll have a closer look into that.

**Comment by al-mission-2016** [comment]
Yea. Now popup menu works as expected!!
