### ISSUE TITLE
Add [build version] && || [build date] into About box

### ISSUE THREAD

**Issue by al-mission-2016** [cboxdoerfer/fsearch#126]
... to distinct somehow beta versions from each other.

**Comment by cboxdoerfer** [comment]
Yes, it makes sense to tell which commit the dev build is based on.

**Comment by cboxdoerfer** [comment]
Done.

**Comment by 07416** [comment]
The date doesn't appear to be there? I rebuilt the program today:

`0.1beta4.188-6fb5`
