### ISSUE TITLE
«Open Folder» should also SELECT current file in file manager

### ISSUE THREAD

**Issue by al-mission-2016** [cboxdoerfer/fsearch#127]
When «Open Folder»-action opens system default  file manager (FM) for selected/found file it would be also convenient to SELECT that file in FM, especially for heavily populated folders.

Many file managers accept full file path as a command line argument and not only open file’s directory but also select that file there. It has been tested with «nemo», «nautilus», «double commander»).

Example:
$nemo '/usr/include/GL/gl.h'
opens “nemo” FM with current dir = “/usr/include/GL/” and sets selection bar on file «gl.h».

To implement this in “fsearch”, it is probably necessary to use
"xdg-mime query default inode/directory"
to get the default FM string, e.g. "nemo.desktop". If the action is “Open Folder”, not “Open File”, then instead of "xdg-open" you may invoke system FM with full-file-path as param.

Here is a few appropriate links on the subject:
https://unix.stackexchange.com/questions/364997/open-a-directory-in-the-default-file-manager-and-select-a-file
https://superuser.com/questions/465495/how-to-find-the-default-file-manager
https://wiki.archlinux.org/index.php/default_applications
https://wiki.archlinux.org/index.php/desktop_entries

Glück zu!)

**Comment by cboxdoerfer** [comment]
Thanks, I already thought about that and the way I wanted to implement that is by letting the user specify the command which is supposed to be executed on folder_open, which would override the default folder_open command if present. Then users could just say, `folder_open_cmd = "nautilus --select $path_to_file"`, etc.

This way users can make the best use of every file manager and not just the ones I considered to hard code.

**Comment by cboxdoerfer** [comment]
@al-mission-2016, so I added an initial WIP implementation of that feature. If you want to try it here's how it works (there's currently no entry in the config dialog, so you'll have to edit the config file):

* open `~/.config/fsearch/fsearch.conf` with an editor
* add the following between two sections

```
[Applications]
folder_open_cmd=$cmd
```
where `$cmd` should be replaced by the command you want to execute. E.g. for Nemo this would look like:
```
[Applications]
folder_open_cmd=nemo {path_full}
```

FSearch automatically replaces `{path_full}` with the correct path to a file and escapes it. Currently there are the following placeholders available:

* `{path_full}' points to the full path of a file/folder, so if you have `/foo/bar/test.jpg` selected it becomes `'/foo/bar/test.jpg'`
* `{path}` points to the parent directory, so `/foo/bar/test.jpg` becomes `'/foo/bar'`
* `{path_raw}` and `{path_full_raw}` are the same as above but they don't get surrounded by `' '` and not escaped for command line usage

But keep in mind this feature is still open for change, e.g. with the identifieres for the placeholders aren't final.

**Comment by al-mission-2016** [comment]
Godlike)

It's more flexible than just hardwired approach.

--- --- ---

I've tested the feature with "nemo" and "doublecmd" with following results.

1) **{path_full}** - OK! No problems with DoubleCommander (doublecmd);
        some warnings in console with "nemo" (if this can somehow help):

>         Initializing nemo-image-converter extension
>         (nemo:23105): Gtk-CRITICAL **: gtk_widget_get_settings: assertion 'GTK_IS_WIDGET (widget)' failed
>         sys:1: Warning: g_object_get: assertion 'G_IS_OBJECT (object)' failed
>         (nemo:23105): Gtk-CRITICAL **: gtk_widget_get_mapped: assertion 'GTK_IS_WIDGET (widget)' failed
>         (nemo:23105): Gdk-CRITICAL **: gdk_window_is_visible: assertion 'GDK_IS_WINDOW (window)' failed
>         (nemo:23105): Gdk-CRITICAL **: gdk_window_show_internal: assertion 'GDK_IS_WINDOW (window)' failed
>         (nemo:23105): Gtk-CRITICAL **: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed
>         (nemo:23105): Gtk-CRITICAL **: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed
>         Initializing nemo-image-converter extension
>         (nemo:23243): Gtk-CRITICAL **: gtk_widget_get_settings: assertion 'GTK_IS_WIDGET (widget)' failed
>         sys:1: Warning: g_object_get: assertion 'G_IS_OBJECT (object)' failed
>         (nemo:23243): Gtk-CRITICAL **: gtk_widget_get_mapped: assertion 'GTK_IS_WIDGET (widget)' failed
>         (nemo:23243): Gdk-CRITICAL **: gdk_window_is_visible: assertion 'GDK_IS_WINDOW (window)' failed
>         (nemo:23243): Gdk-CRITICAL **: gdk_window_show_internal: assertion 'GDK_IS_WINDOW (window)' failed
>         (nemo:23243): Gtk-CRITICAL **: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed
>         (nemo:23243): Gtk-CRITICAL **: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed
>         (nemo:23243): Gtk-CRITICAL **: gtk_widget_get_settings: assertion 'GTK_IS_WIDGET (widget)' failed
>         (nemo:23243): Gtk-CRITICAL **: gtk_widget_get_mapped: assertion 'GTK_IS_WIDGET (widget)' failed

I'm not sure if these warnings are relevant to FSearch. Otherwise {full_path} does exactly what is wanted :)

2) **{path}** - OK! No warnins in console for both "nemo" & "doublecmd".

3) **{path_raw}** - NO! Tested with "nemo" & "doublecmd".
    Console message: 

> "Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged."
4) **{path_full_raw}** - NO! I tested with "nemo". Paths with spaces can't be processed correctly.
    Console message: 

> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

Obviously **unquoted (raw) path** can not be processed properly. FM stumbles upon spaces. IMHO, {*_raw}-family arguably useless.


Christian, thanks a lot).

**Comment by cboxdoerfer** [comment]
I'm glad you like it and it works for you.

And yes, the `raw` versions are most likely pretty useless, but I thought while I'm at it I might just as well add them - this was bascially zero effort. After all maybe someone finds a usecase for them. But I'll make sure to recommend the quoted and properly escaped ones to users once this feature is finished and only mention the `raw` versions as a sidenote.
