### ISSUE TITLE
File/Folder with red cross icon

### ISSUE THREAD

**Issue by cyantarek** [cboxdoerfer/fsearch#131]
Every time I reboot my system, all the files/folders get red cross mark and I can not open them from fsearch untill I rebuild the database

This is annoying.

Please give me a solution

**Comment by cboxdoerfer** [comment]
Do really "all the files/folders" break on reboot?

**Comment by cboxdoerfer** [comment]
Do you still have that issue? Also, please make sure FSearch exits properly when you reboot.
