### ISSUE TITLE
Database Update Sequence

### ISSUE THREAD

**Issue by celikbas** [cboxdoerfer/fsearch#133]
Hi Developer,
FSearch is a mandotary tool for me but updating database every start is annoying. Is it possible to have a feature like this: "Update database if not updated in one week"

Thanks

**Comment by cboxdoerfer** [comment]
Unfortunately that's not possible right now. However I've been working on a rework of the database backend for quite some time now and this will also allow scheduled database updates in the background.

**Comment by swyveu** [comment]
+1

**Comment by Alexeyan** [comment]
Any updates on this?

**Comment by klein-j** [comment]
The roadmap already lists inotify support, and I think this is a good solution. Like voidtools Everything I tend to use fsearch when clicking through folder hierarchies is too annoying for me (so I would use it all the time for everything). However, I search mostly for files that I currently work on, so for my usage scenario I have to have an up to date data base all the time.

Scanning on startup is annoying, but scanning every two minutes in the background would also be a quite heavy workload. So I think inotify or something similar is the way to go. This would be THE feature that decides if I can use fsearch all the time (like Everything) or only once a day when I really need to search for something.

So thanks for writing this app, know that it makes people happy and that the community values future developments.

**Comment by hoanghapham** [comment]
is it possible to add an option to force the database to update in the UI? I believe it will be a good alternative while waiting for scheduled update feature

**Comment by Alexeyan** [comment]
@hoanghapham That's already there, isn't it? Ctrl-Shift-R

**Comment by hoanghapham** [comment]
Thanks, I didn't know that!

**Comment by cs96and** [comment]
#166

**Comment by mbnoimi** [comment]
+1

**Comment by CarlosAllendes** [comment]
Hi from Chile
Thanks for the great job making Fsearch.

Im using the tool in "deepin-linux"  but  in every restart  the database is empty  (?) 

is there a sqlite or  a .config file that saves the configuration and last indexing?

TIA!!

**Comment by cboxdoerfer** [comment]
@CarlosAllendes 

> Im using the tool in "deepin-linux" but in every restart the database is empty (?)

That likely means that fsearch was shutdown properly. Either because it was forcefully quit, or it crashed. Do you have any logs that show what happened?

> is there a sqlite or a .config file that saves the configuration and last indexing?

Yes, there are. The config is stored in `~/.config/fsearch/fsearch.conf` and the databases in `~/.config/fsearch/database`.

**Comment by CarlosAllendes** [comment]
Thank you.
Now is all  working very well.

Nice Job. Congrats!!

**Comment by peter-avila** [comment]
Is there a way on the command line to run a database update? I also use Voidtools Everything and was so glad to find something similar on Linux. I'd like to set up a cron job to run database updates at a given time (e.g. 3 am) as I do in Everything instead of having to enable updates on opening or manually doing so (because I find I only update when I'm desperately looking for a file 😅).

**Comment by cs96and** [comment]
@peter-avila yes, the latest version has a -u switch that just updates the database and then quits. #166

**Comment by peter-avila** [comment]
> @peter-avila yes, the latest version has a -u switch that just updates the database and then quits. #166

That’s awesome. Thanks @cs96and.

**Comment by cboxdoerfer** [comment]
The `--updatedb` flag and tools like cron or systemd-timer allow that feature now.
