### ISSUE TITLE
installed. howto start it?

### ISSUE THREAD

**Issue by sl5net** [cboxdoerfer/fsearch#141]
its installed. thanks. howto start it?
BTW: i installed it like explained here:
https://launchpad.net/~christian-boxdoerfer/+archive/ubuntu/fsearch-daily
make[1]: Leaving directory '/home/sl5net/Downloads/fsearch'

~/Downloads/fsearch$ fsearch apache
load config failed: No such file or directory
(fsearch:14232): dbind-WARNING **: 22:18:43.656: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(fsearch:14232): GLib-GIO-CRITICAL **: 22:18:43.855: This application can not open files.

**Comment by sl5net** [comment]
starting works by typing cd fsearch
but BTW it says no database. i should ad one in edit > preference > daabase > add.
i tried to do with no success

**Comment by cboxdoerfer** [comment]
Can you provide more details? What happens after you added the path in the database preferences?

**Comment by cboxdoerfer** [comment]
Closing. No reponse.
