### ISSUE TITLE
Ubuntu 18.10 Cosmic Cuttlefish

### ISSUE THREAD

**Issue by AdamKane41** [cboxdoerfer/fsearch#144]
Could we get an updated PPA for  Ubuntu Cosmic Cuttlefish?
...pretty please ;-) ...

thanks!

**Comment by cboxdoerfer** [comment]
Hey, I added 18.10 to the automatic builds. The first build should appear within the next 24 hours.

**Comment by AdamKane41** [comment]
Updated... as of now cosmic is unavailable. will post again once the ppa is up and running to tell if  it works. thanks!
peace

**Comment by BjoernDaase** [comment]
I added the PPA  `ppa:christian-boxdoerfer/fsearch-daily` today (one Ubuntu 18.10) and it still did not work. Are you sure everything is alright?

**Comment by cboxdoerfer** [comment]
I just triggered a manual rebuild, hope this works now. I don't have access to an Ubuntu machine atm so I can't test it myself.

**Comment by BjoernDaase** [comment]
Yes, it works now!
