### ISSUE TITLE
Migration from intltool to gettext

### ISSUE THREAD

**Issue by mtsolekas** [cboxdoerfer/fsearch#147]
I have completed a complete migration to gettext, which I have been testing and tweaking
for some time now and it seems to have no problems. If you are interested in this check out my
fork and I can create a pull request.

I am not 100% positive there will be no hiccups, so if you can test it yourself to be sure.

https://github.com/mtsolekas/fsearch

**Comment by cboxdoerfer** [comment]
Migration is complete.
