### ISSUE TITLE
Cut Paste File or Directory.

### ISSUE THREAD

**Issue by blueray453** [cboxdoerfer/fsearch#151]
When I right click a file, it gives copy option but not cut option.

I have to right click, go to the location, search for the file and then cut it.

Can you please add cut along side copy on the roadmap.

**Comment by Areahints** [comment]
+1 for this functionality

**Comment by theorangeBirdybird** [comment]
For some reason Ctrl+C or clicking the copy option doesn't work. My Clippboard always ends up empty.

**Comment by mbnoimi** [comment]
+1

**Comment by AtilioA** [comment]
This is one of the things I miss about Everything the most when using fsearch.

**Comment by AtilioA** [comment]
This is one of the things I miss the most about Everything when using fsearch.

**Comment by cboxdoerfer** [comment]
Closing, duplicate of #48. Discussion should continue there.
