### ISSUE TITLE
[Feature request] Update database from command line

### ISSUE THREAD

**Issue by krow147** [cboxdoerfer/fsearch#156]
Maybe I'm ignorant and there's some way to do this, but the -help-all command line option is useless, and I can't find any documentation. As of posting this fsearch.org returns a blank page. I'm also running a probably slightly outdated version from the Linux Mint repositories (the Help > About section doesn't have a version number).

This programs is very seriously impaired by the fact that you can only update the file database while running the GUI. Basically this means that the database is going to have to be updated when I'm actually trying to use the software. Compared to Everything on Windows, this is an enormous inconvenience.

While I would ideally like FSearch to behave like Everything and update itself constantly, I understand that this has been very difficult to implement. I would be perfectly fine with just having a script running something like the following in the background

while 1
    fsearch -update-database
    sleep(5 minutes)

**Comment by phil294** [comment]
why did you close this?
without having looked further into it, maybe fsearch is using locate? in this case, updating the database would be `updatedb`

**Comment by cs96and** [comment]
#166
