### ISSUE TITLE
Menu bar is hidden

### ISSUE THREAD

**Issue by pa657** [cboxdoerfer/fsearch#157]
Menu bar seems to be hidden and I don't know how to restore it .... 
![Screenshot_20190402_105242](https://user-images.githubusercontent.com/1125551/55389410-766d1a00-5535-11e9-8eb2-2aec27c33f25.png)

**Comment by Vioner** [comment]
CTRL+M (I'd suggest the dev to change it to simple, standard "ALT")

wt., 2 kwi 2019 o 10:53 Aguilar <notifications@github.com> napisał(a):

**Comment by pa657** [comment]
Thank you
