### ISSUE TITLE
how to exclude many file?

### ISSUE THREAD

**Issue by Chrislzy1993** [cboxdoerfer/fsearch#160]
hi, @Calinou @adamwojs @shishi @ronjouch @fitojb , thanks for yours great work, it help me a lot.  
and now , i want to exclude some type file, like *.jpg, *png...,  when i write as `*.jpg, *png`, or `*.jpg *.png`,  it does not work,  can u show me how to make it right , thanks again!

**Comment by fitojb** [comment]
You should use a semicolon: `.git;*.tmp`

**Comment by Chrislzy1993** [comment]
@fitojb , thanks, it works
