### ISSUE TITLE
Add OpenSUSE to build instructions in wiki

### ISSUE THREAD

**Issue by fxk8y** [cboxdoerfer/fsearch#162]
I'm on OpenSUSE 42.2 and installing the dependencies works very similar to Fedora. After installing them with

sudo zypper install automake autoconf intltool libtool autoconf-archive pkgconfig glib2-devel gtk3-devel

I was able to build and run the program without errors.
Please add this to the wiki page so others will know.

**Comment by cboxdoerfer** [comment]
Thx, done.
