### ISSUE TITLE
UNKNOWN version in help

### ISSUE THREAD

**Issue by leodom** [cboxdoerfer/fsearch#169]
Hi there ! 

I was using a version of fsearch I installed some times ago (can't remember when or how though) When looking the About I was getting UNKNOWN instead of a nice number.

To have a newer version to be able to use /u parameter with CRON job to update database automatically, I followed the Build instructions, installed dependencies, cloned git and make install.

When calling **fsearch**, the version still says UNKNOWN, no apparent changes took place
Calling **fsearch /u** I get the error _**(fsearch:25865): GLib-GIO-CRITICAL : 15:05:36.001: This application can not open files.**_

**dpkg --list** tells me _**fsearch-trunk 20191002+r397.4dda089~ub amd64**_

I have 2 files called fsearch with different size/date in  /usr/bin and /usr/local/bin
I get the same error launching each one of those binaries with the /u

Now, I built nothing in linux for ages, so something might as well have gone wrong, as ./autogen.sh cries :
> Copying file po/Makefile.in.in
> 
> Please add the files
>   codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
>   progtest.m4
> from the /usr/share/aclocal directory to your autoconf macro directory
> or directly to your aclocal.m4 file.
> You will also need config.guess and config.sub, which you can get from
> ftp://ftp.gnu.org/pub/gnu/config/.
> src/Makefile.am:73: warning: shell $(GLIB_COMPILE_RESOURCES: non-POSIX variable name
> src/Makefile.am:73: (probably a GNU make extension)

But then configure, make and make install do their things without complaining...
So... Any idea on wether I actually installed a newer version, or I still need to install it, and the meaning behind the error messages ?

Thanks :)

**Comment by cboxdoerfer** [comment]
`fsearch /u` means launching fsearch with opening the `/u` file. Command line options start with `-`, so you want `fsearch -u` or `fsearch --updatedb`

**Comment by leodom** [comment]
Great thanks ! Some things should not be done after midnight :P
