### ISSUE TITLE
installation on Kubuntu 19.10 failed

### ISSUE THREAD

**Issue by res55** [cboxdoerfer/fsearch#171]
Hello
both approaches failed:
see 2 logfiles attached.
[failed-built-of-fsearch.log](https://github.com/cboxdoerfer/fsearch/files/4000286/failed-built-of-fsearch.log)
[failed-install-fsearch.log](https://github.com/cboxdoerfer/fsearch/files/4000287/failed-install-fsearch.log)

who can help?
Res

**Comment by cboxdoerfer** [comment]
In the first log you're trying to run FSearch in a non-graphical environment or the environment variables are messed up, e.g. $DISPLAY. That's why launching the app fails.

The install from the second log failed because at the time 19.10 wasn't enabled as a build target. It's now.
