### ISSUE TITLE
How to set up the keyboard shortcuts?

### ISSUE THREAD

**Issue by wwfgxnyi** [cboxdoerfer/fsearch#172]
Hi, I noticed that this app supports keyboard shortcuts, but I can't find a place to set up them. For example, I hope to enter "Ctrl + Ctrl" to open fsearch, is it possible? I use Linux mint 19.3 cinnamon and I can find the keyboard settings, but still could not find the shortcut's settings of fsearch.

**Comment by bad63r** [comment]
> I hope to enter "Ctrl + Ctrl" to open fsearch, is it possible?
If you want keyboard shortcut to open fsearch in Linux Mint, please go check out your system settings for keyboard. I'm sure there must be some settings as I remember(didn't use Mint for a while)

**Comment by cboxdoerfer** [comment]
> For example, I hope to enter "Ctrl + Ctrl" to open fsearch, is it possible?

That depends on the hotkey daemon you're using, which in your case seems to be some part of Cinnamon. There's nothing FSearch itself can do to achieve that.

**Comment by wwfgxnyi** [comment]
All right, thank you.
