### ISSUE TITLE
Remember column configuration - Date modified issue

### ISSUE THREAD

**Issue by smjure** [cboxdoerfer/fsearch#173]
It would be good that fsearch opens as it was previously closed, including that the results are sorted according to "Date modified", newest first. But when ever I open the fserach, column configuration is "remembered" but not Date modified, it goes back to alphabetic file sort.

**Comment by cboxdoerfer** [comment]
Closing, duplicate of #67

**Comment by cboxdoerfer** [comment]
Fixed.
