### ISSUE TITLE
Open folder on Path click

### ISSUE THREAD

**Issue by smjure** [cboxdoerfer/fsearch#174]
Would it be possible to make that when you click on File path of a searched file, the Folder of the file opens (just like in Everything) instead of the file itself opens?

**Comment by cboxdoerfer** [comment]
Probably. Does Everything do that by default or is this configurable?

**Comment by smjure** [comment]
No, it's configurable. It's under Everything Options -> General -> Results -> Open path with double click in path column

![image](https://user-images.githubusercontent.com/22912191/72543160-9df36000-3885-11ea-9731-d8c2fcc7ec0a.png)

**Comment by cboxdoerfer** [comment]
Hey, sorry it took a while, but the feature is now implemented. It's disabled by default, but you can enable it in `Preferences -> Interface -> Open path with double click in path column`

Thanks for the suggestion!
