### ISSUE TITLE
Cannot build fsearch

### ISSUE THREAD

**Issue by wrongRaisins** [cboxdoerfer/fsearch#177]
I heard about Fsearch and it sounds perfect! So I tried to build it on Debian 9. I ran ./autogen.sh and got this result:

> Copying file po/Makefile.in.in
Please add the files
  codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
  progtest.m4
from the /usr/share/aclocal directory to your autoconf macro directory
or directly to your aclocal.m4 file.
You will also need config.guess and config.sub, which you can get from
ftp://ftp.gnu.org/pub/gnu/config/.

> configure.ac:15: installing './compile'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
src/Makefile.am:70: warning: shell $(GLIB_COMPILE_RESOURCES: non-POSIX variable name
src/Makefile.am:70: (probably a GNU make extension)
src/Makefile.am: installing './depcomp'

I'm new to this so please excuse my inexperience. I do not have a file named  isc-posix.m4 in my /usr/share/aclocal directory. (All the others are there.) So I do not know how to proceed.

Also, I'm sorry but I don't know what "You will also need config.guess and config.sub" means. Do I get those files and copy them somewhere? Thank you.

**Comment by cboxdoerfer** [comment]
You can ignore all of that. As long as the `configure` script was successfully generated (which I suppose it did because I don't see any errors regarding it), everything is fine. Just continue with the build process:

`./configure && make && sudo make install`

**Comment by cboxdoerfer** [comment]
I'm closing this issue. If something went wrong at a later stage, just let me know.
