### ISSUE TITLE
Cron database update while using fsearch GUI

### ISSUE THREAD

**Issue by mlusic** [cboxdoerfer/fsearch#182]
Mint 19.3 Cinnamon

If cron process for automatic database update start while GUI are opened newly created files are not written in database. Tested by creating new file than running database update from terminal (fsearch -u) while GUI are opened and closed. 

Great program! Thank you.

**Comment by cboxdoerfer** [comment]
Thanks, great find. I'll have a look.

**Comment by cboxdoerfer** [comment]
Fixed.

**Comment by mlusic** [comment]
Thank you

Mario Lušić
mario.lusic@gmail.com
________________________________
