### ISSUE TITLE
Crash when trying add directories 

### ISSUE THREAD

**Issue by minutesinch** [cboxdoerfer/fsearch#183]
for reproduce issue first make sure program updating database(in edit>preference> database>enable update databse on start or you can doing manually by pressing shift+ctrl+r ) when program start(i mean when database is updating then try go to edit>preference> database> and add directory , first try to add dirctory in include part, you can see program is crash try exclude with same step you see crash too

**Comment by Futureknows** [comment]
Exact same here, on two machines. First noticed when I was trying to exclude timeshift folder, but after finding this report I tried any other folders also crash when excluding. Latest build from Git in Fedora 32.

**Comment by Futureknows** [comment]
Just to update. I found that the crash happens when attempting to add/exclude folders while the database is indexing. Seems to work OK after indexing is compete.

**Comment by minutesinch** [comment]
@Futureknows thank you for your comment and hope get fixed by dev

**Comment by cboxdoerfer** [comment]
Yes, that's a know issue and requires quite some work to fix, I'll see what I can do. Thanks for reporting.

**Comment by cboxdoerfer** [comment]
Fixed!

**Comment by minutesinch** [comment]
thank you
