### ISSUE TITLE
Can we search in a specific folder? If so, how? 

### ISSUE THREAD

**Issue by YousufAzadSami** [cboxdoerfer/fsearch#185]
Let's say I want to search in `/home/user/Desktop/` only. Can I do that?

**Comment by Vioner** [comment]
Yes. It's done exactly how you've written it. `/home/user/Desktop/ phrase`
F.e if I want to find all ebooks in my Desktop folder, I'd search
`/home/user/Desktop/
.epub`

śr., 29 kwi 2020 o 13:24 Yousuf Azad (Sami) <notifications@github.com>
napisał(a):

**Comment by cboxdoerfer** [comment]
Thx @Vioner, that's exactly how to do it.
