### ISSUE TITLE
fsearch database keeps reset on application restart

### ISSUE THREAD

**Issue by salimsaid** [cboxdoerfer/fsearch#187]
Each time i open fsearch , the folders that i included in the database search path are gone.

I have to manually enter the folder path for searching each time i start fsearch. It used to work flawlessly before but not anymore. I only set database once, and fsearch used to remember the path even after i restart the application.

I am on ubuntu 20.04 64bit

What am i missing ?

**Comment by cboxdoerfer** [comment]
Can you post the content of `~/.config/fsearch/fsearch.conf` before starting FSearch?

**Comment by salimsaid** [comment]
I don't really know what happened, but everything seems to be working as normal

Below is the content of ~/.config/fsearch/fsearch.conf

[Interface]
restore_column_configuration=false
enable_list_tooltips=true
enable_dark_theme=false
show_menubar=true
show_statusbar=true
show_filter=true
show_search_button=true
show_base_2_units=false
action_after_file_open=0
action_after_file_open_keyboard=false
action_after_file_open_mouse=false
restore_window_size=false
window_width=800
window_height=476
show_listview_icons=true
show_path_column=true
show_type_column=true
show_size_column=true
show_modified_column=true
name_column_width=250
path_column_width=250
type_column_width=100
size_column_width=75
modified_column_width=125
name_column_pos=0
path_column_pos=1
type_column_pos=2
size_column_pos=3
modified_column_pos=4

[Dialogs]
show_dialog_failed_opening=true

[Search]
search_as_you_type=true
auto_search_in_path=true
search_in_path=false
enable_regex=false
match_case=false
hide_results_on_empty_search=true
limit_results=true
num_results=1000

[Database]
update_database_on_launch=false
exclude_hidden_files_and_folders=false
follow_symbolic_links=false
location_1=/home/salim
location_2=/media/salim/B2CE3F5CCE3F1855
exclude_files=

**Comment by cboxdoerfer** [comment]
> I don't really know what happened, but everything seems to be working as normal

Hm, maybe FSearch didn't quit properly the last time you used it and therefore didn't save the config. But anyway, if the issues arises again please feel free to raise the issue again.
