### ISSUE TITLE
feature suggestion: close to tray

### ISSUE THREAD

**Issue by gersonjferreira** [cboxdoerfer/fsearch#188]
I've read the roadmap and I think this is a missing feature that would be really helpful.

It would be great to have FSearch at the tray and easy open with a keyboard shortcut.

**Comment by cboxdoerfer** [comment]
Yes, I agree. Do you know what's the current standard protocol to provide tray icons and if there's a well maintained C library that provides the necessary functionality? GTK+ unfortunately deprecated that functionality and GNOME doesn't seem to care at all about status icons.

**Comment by cboxdoerfer** [comment]
Duplicate of #52
