### ISSUE TITLE
[Feature request] Add shortcut to bring up window

### ISSUE THREAD

**Issue by DaveHuman** [cboxdoerfer/fsearch#189]
Firstly just installed this and it's awesome. Just like Everything :)

Apologies if this has already been suggested or implemented, but I can't find it anywhere.

In Everything I have a hotkey setup of Ctrl+Space to bring up the Everything window (a bit like Spotlight on a Mac, I suppose), and it saves a ton of time, and I'm using it several times a day. Would be great if FSearch had this. Thanks.

**Comment by ben2talk** [comment]
Yes, go to Keyboard Shortcuts, create a custom shortcut Ctrl+Space and enter the command to launch FSearch.
This doesn't need to be set by software...

**Comment by rockpham** [comment]
@ben2talk thank you, your method works well

**Comment by cboxdoerfer** [comment]
Yes, I think the desktop environment is the best place to have that feature, since global key bindings on some Wayland compositors aren't supported well anyway, so FSearch itself can't implement it properly.
