### ISSUE TITLE
Add support for older GTK+ and GLib versions (e.g. the ones shipped by Ubuntu 14.04)

### ISSUE THREAD

**Issue by trappedinspacetime** [cboxdoerfer/fsearch#19]
Hi;
First of all thank you for developing such an application. I am on Ubuntu 14.04.5 platform. I downloaded 14.04 zip version of your project. After running `./autogen.sh` and then `./configure` I get 

```
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /bin/mkdir -p
  checking for gawk... gawk
  checking whether make sets $(MAKE)... yes
  checking whether make supports nested variables... yes
  checking whether make supports nested variables... (cached) yes
  ./configure: line 2877: syntax error near unexpected token `IT_PROG_INTLTOOL'
  ./configure: line 2877: `AX_REQUIRE_DEFINED(IT_PROG_INTLTOOL)'
```

I also checked out https://www.reddit.com/r/linux/comments/4lwo5n/fsearch_a_new_file_search_application_based_on/ and https://github.com/cboxdoerfer/fsearch/issues/3 

but the tips in those links didn't help. 

I installed `gnome-common` and `autoconf-archive`. 

I hope you help me fix it.

Regards.

Kenn

**Comment by cboxdoerfer** [comment]
Did you install the build requirements listed [here](https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions)?

**Comment by kensully** [comment]
@cboxdoerfer  Thank you for responding. I downloaded the one tagged ubuntu 14.04 in branch section. 
I already tried master branch beforehand and I noticed GTK+ 3.12 dependency during `./configure` process

**Comment by cboxdoerfer** [comment]
The Ubuntu 14.04 branch is a work in progress. Once I've finished the support for older GTK+ and GLib versions I'll merge it to master and will notify you. We should keep the bug report open until then.

**Comment by thekalinga** [comment]
@cboxdoerfer Is there any progress on this issue.

**Comment by cboxdoerfer** [comment]
Since those distros are pretty much EOL, I'm going to close this. Given the limited amount of time I have, it's just not feasible to spend a lot of time to support old libraries.
