### ISSUE TITLE
search in a particular hidden folder only

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#190]
How can I search in a particular hidden folder only? I want to search only in my winetricks prefix. It is hidden. But I can't choose it. It's just not visible although in thunar I have activated "show hidden".

Thank you.
![Fsearch hidden folders](https://user-images.githubusercontent.com/13977359/85218850-8c673480-b39e-11ea-8607-dfaf72889801.png)

**Comment by Lamecarlate** [comment]
The Ctrl + H shortcut should work here (it's a shortcut from Nautilus, I don't exactly know what software is used when browsing files within another software).

**Comment by Golddouble** [comment]
Thank you. This works great.
