### ISSUE TITLE
Open With when multiple files selected

### ISSUE THREAD

**Issue by musictrivianut** [cboxdoerfer/fsearch#192]
Hi, first, the obligatory "thank you greatly for such a fantastic program!"  I was using gnome-search-tool to find files, but recently found fsearch, which has most of the functionality that I was using before.

My one issue (other than drag-and-drop not working, even though that issue was noted as implemented) is the Open With menu item when selecting multiple files.  I would include screenshots to illustrate, but I can't get Ubuntu to take a screenshot when the context menu is activated.

Anyhow, right-clicking on any single item allows the use of the Open With function.  But when multiple items are selected, that menu it blank (literally a very small rectangle with no programs to choose from).  This isn't just files with different extensions, but even files with the same extension.

Wondering if anyone else is experiencing this or if this is a known issue (I did search, but didn't find a post on this).

Thanks again!

Wayne

**Comment by cboxdoerfer** [comment]
Open With menu is currently disabled when multiple items are selected, because I wasn't sure at the time how to handle them properly.

I guess the best behavior for now would be to just add a menu item to manually select which application to use, instead of trying to guess a best common application of all selected files.

**Comment by musictrivianut** [comment]
Well, that completely explains why I'm not seeing any programs available there :-)

Thank you very much for the explanation!

**Comment by cboxdoerfer** [comment]
No problem. 

I just fixed the issue and it's now possible to open multiple files at once with the "Open With" menu and I also added the option to select a different application than the suggested ones. So I'm closing the issue now.

**Comment by musictrivianut** [comment]
Awesome!
