### ISSUE TITLE
Why pressing down arrow once from the search bar does not select the first result immediately?

### ISSUE THREAD

**Issue by AtilioA** [cboxdoerfer/fsearch#193]
Suppose I have my cursor in the search bar:
![image](https://user-images.githubusercontent.com/27153776/88485813-4da13d00-cf4f-11ea-96d3-92fb466280ca.png)
After pressing 'down arrow' once (entry gets an outline, but isn't selected):
![2020-07-26_14-49_1](https://user-images.githubusercontent.com/27153776/88485824-6578c100-cf4f-11ea-952b-c1757dac7ae4.png)
After pressing 'down arrow' again (second time):
![2020-07-26_14-49_2](https://user-images.githubusercontent.com/27153776/88485815-5265f100-cf4f-11ea-8e73-03a31bc65d79.png)

Is this an oversight or is it intended? For reference, I think Everything does select the first result right away, but I have yet to verify it.

**Comment by cboxdoerfer** [comment]
It's just the default behaviour of GTK. I'll see if this can be overriden.

**Comment by cboxdoerfer** [comment]
Fixed.
