### ISSUE TITLE
fsearch crashing

### ISSUE THREAD

**Issue by valdotdev** [cboxdoerfer/fsearch#195]
Hi! Just clean installed fsearch-git using yay in Manjaro.

Unfortunately the app won't open on me even if I delete the config directory. When I try to open the app it only generates the database folder and that's it and it crashes on me.

When I try to open it in terminal I get this:
```
❯ fsearch
load config failed: No such file or directory
fsearch: database.c:996: db_load_from_file: Assertion `db->includes != NULL' failed.
[1]    4961 abort (core dumped)  fsearch
```
Any ideas? :)

**Comment by cboxdoerfer** [comment]
Thx for reporting. I made a lot of changes today in the way the database works and this stupid mistake unfortunately slipped through, sorry.

But it's easily solvable and I'll fix it right tomorrow when I'm back at my PC.

**Comment by valdotdev** [comment]
Awesome! Thanks!

**Comment by cboxdoerfer** [comment]
Fixed.
