### ISSUE TITLE
fsearch crashes when trying to type while database is updating on app launch

### ISSUE THREAD

**Issue by valdotdev** [cboxdoerfer/fsearch#196]
So basically when I try to type in anything on the field while the database is being updated the app crashes.

This only happens when the `Update database on start` option is enabled and I launch fsearch and begin typing while the db is updating. So if I manually update the database typing seems to work fine.

When done in terminal here's the output:
```
❯ fsearch
disable action: update_database
fsearch: database.c:944: db_try_lock: Assertion `db != NULL' failed.
[1]    52204 abort (core dumped)  fsearch
```
Normally I don't actually type anything yet while it's updating but when I saw your commit that you can now type while the db is updating then I gave it a try on app launch. And yeah, it crashed.

System: Manjaro KDE

**Comment by cboxdoerfer** [comment]
Thx for reporting, fixed.

**Comment by valdotdev** [comment]
That was fast! Tested and works fine on my end!

Although the issue is now closed I did notice something. When I type no results are displayed. Is this an intended behavior?

**Comment by cboxdoerfer** [comment]
It's intended, but I could change it so that the database is first loaded from disk and then the update is triggered. I'll think about that.

**Comment by valdotdev** [comment]
Thanks! For me it's not really a big deal since in the first place I never though about searching while updating when I first start the app. But good to know it's an option. :smiley:

**Comment by cboxdoerfer** [comment]
Yes, after further thinking about it, it's kind of nice being able to search right after the application has launched, even when the database is being updated. So I enabled that now.
