### ISSUE TITLE
Multiple languages are supported, yet there is no option to switch between them

### ISSUE THREAD

**Issue by AtilioA** [cboxdoerfer/fsearch#197]
We currently have 20+ languages with over 80% completion on Weblate, but there is no option to change fsearch's UI language.

As a side question: how often does Weblate push changes to this repo? There is a string that shouldn't be translated (the string for the program's icon, '`system-search`'), else the program will not have an icon, or, at least, this string should be translated to a specific string, i.e. the icon's name in the target language, although I really doubt this is the case. I introduced this bug to the PT-BR translation and noticed that a handful of other languages have this string translated as well, but I didn't test any of them.

**Comment by cboxdoerfer** [comment]
FSearch follows the language of your desktop. If you want to change the language for only FSearch you need to launch it with `LANGUAGE` with the appropriate language identifier.

I'm not sure how often Weblate pushes, I would guess once every day if there are any changes.

Regarding the `system-search` icon, thanks for bringing that to my attention. I'm not exactly sure why this string is marked translatable in the first place, the UI file seems fine, so there's seems to be something strange going on.

**Comment by AtilioA** [comment]
Alright, just something to keep in mind; many applications allow you to set the language within the application. However, I did not understand how I can set `LANGUAGE` when launching.

`system-search` issue has been fixed.

**Comment by Henriquelay** [comment]
@AtilioA, to start the application with the desired locale, simply set a enviroment variable called `LANGUAGE` to a desired [locale name](https://www.gnu.org/software/libc/manual/html_node/Locale-Names.html) (by testing, only the language and territory parts of the syntax are required). What this means is:
In bash, run: `LANGUAGE=pt_BR; fsearch`
In fish, run: `set LANGUAGE pt_BR; fsearch`

If you are using a `.desktop` file to launch the application, be sure to change the `EXEC` field accordingly.

**Comment by cboxdoerfer** [comment]
Like mentioned, this is better covered by the system and/or environment variables. Closing.
