### ISSUE TITLE
FSearch version is UNKNOWN

### ISSUE THREAD

**Issue by AtilioA** [cboxdoerfer/fsearch#198]
My entry for FSearch's version is `UNKNOWN`, whether by building from source or installing through the PPA. This is an old issue. Perhaps related to localized strings?

From the terminal:
![2020-07-27_13-01](https://user-images.githubusercontent.com/27153776/88584611-4a2db480-d028-11ea-9be6-a7f6cff82113.png)

From the GUI:
![2020-07-27_13-01_1](https://user-images.githubusercontent.com/27153776/88584615-4b5ee180-d028-11ea-9c7b-df07f438618f.png)

**Comment by cboxdoerfer** [comment]
Hm, that's weird, the version string is set properly on my local builds. I'll have a look at that tomorrow.

**Comment by AtilioA** [comment]
Well, I don't know how but it is correct now; I'll close this issue and keep an eye on this.

![image](https://user-images.githubusercontent.com/27153776/88685511-61be7900-d0cc-11ea-9fce-e639877d88b5.png)

![image](https://user-images.githubusercontent.com/27153776/88685537-68e58700-d0cc-11ea-906e-40dd13c52381.png)
