### ISSUE TITLE
Wrong GTK3 requirements 

### ISSUE THREAD

**Issue by kmikolaj** [cboxdoerfer/fsearch#2]
fsearch require GTK+ 3.20 not 3.12 as stated in README. File preferences.ui introduces this. 
I build it on Ubuntu 16.04 but it has GTK+ 3.18 so every time I open preferences window it crashes.

**Comment by cboxdoerfer** [comment]
Hi, thx for reporting. Apparently Glade uses the installed GTK+3 version automatically as a requirement, even if not needed. Should be fixed now.
