### ISSUE TITLE
Allow include/exclude folders to be entered in a text field

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#200]
We can add places, where Fsearch should search here:
![Fsearch](https://user-images.githubusercontent.com/13977359/88934676-33ce6580-d281-11ea-835b-06ba873a7677.png)

It seems, we can only add new folders, by browsing. But sometimes I have already the folder in my clipboard and just want to copy it into Fsearch. But it's a pity, I can not do this. Although I have the folder in my clipboard, I nevertheless have to browse to this folder again.

Please add the possibility to add new search folders just by copying (or typing) it into this dialog field.

Thank you.

**Comment by cboxdoerfer** [comment]
![2020-07-30-192251_492x414_scrot](https://user-images.githubusercontent.com/6108388/88954053-1659c580-d29a-11ea-8c17-222406ee3250.png)

I already have a WIP implemented. See the "Select path..." entry in the screenshot, where you can copy/paste and get path completion, to quickly add new paths.

Once the remaining bugs and annoyances are gone I'll publish it, probably next week.

**Comment by Ryder17z** [comment]
I'd like to add ***/.thumb/*** to the exclude list as it isn't a useful set of folders.

How's this enhancement going?

**Comment by cboxdoerfer** [comment]
No progress so far, I've been focusing on getting the 0.1 release out first.

But you can already exclude that folder with the current UI.

If it's a particular folder you can add it to the exclude list with the "Add" button, and if you want to exclude all `. thumb` folders just add `.thumbs` to the exclude file list text entry.

**Comment by cboxdoerfer** [comment]
Done. There's now a text entry to quickly add paths to the include/exclude lists.

**Comment by lee321987** [comment]
Was this feature removed?
