### ISSUE TITLE
[Feature request] deactivate search folders

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#201]
I speak about this dialog field:
![Fsearch](https://user-images.githubusercontent.com/13977359/88935268-da1a6b00-d281-11ea-9a94-9190ce9e2d76.png)

Here normally I have "/" as search folder.
But sometimes I want to change my search folder for a particular search and replace "/" through another folder. But later I want to go back to "/".

So for example I want to look after the greatest files in the folder 
~/.thunderbird/oabbl9j2.default/Mail
So I go to 
![Fsearch](https://user-images.githubusercontent.com/13977359/88935570-2fef1300-d282-11ea-95fb-c6505e877046.png)
and replace "/" through "~/.thunderbird/oabbl9j2.default/Mail".
Then I search for all files and sort the result after the file size. This way I see, which are the biggest files in this folder.
Then I have to go back into...
![Fsearch](https://user-images.githubusercontent.com/13977359/88935746-5e6cee00-d282-11ea-81c3-23ba2038afbd.png)
... To delete the folder "~/.thunderbird/oabbl9j2.default/Mail" and add again "/".

So what is my feature request?
Please add the possibility to deactivate search folders.

So in the scenario above I just could deactivate "/" temporary, add "~/.thunderbird/oabbl9j2.default/Mail".
Later I just could again activate "/" and delete "~/.thunderbird/oabbl9j2.default/Mail".

**Comment by cboxdoerfer** [comment]
Maybe I'm missing something, but why don't you just limit the search to that folder by using the search? In your example you could just type the following in the search entry: 

`.thunderbird/oabbl9j2.default/Mail your_search_term`

Then you'll only get the results from within your thunderbird mail folder. With custom filters (which I'm working on ATM) you could then also store these kind of queries and quickly switch between them in the filter dropdown to the right of the search entry.

**Comment by Golddouble** [comment]
Thank you this is what I was looking for. You gave me the trick.

(Hint: Works not with   "~/"   , but with "/home/Golddouble/" )

**Comment by Golddouble** [comment]
But how can I bring this into work, when one of my folder has "spaces"?

For example:
`/home/Golddouble/My dokuments my_search_term`

I have tried this without success:
`"/home/Golddouble/My dokuments" my_search_term`

And I have tried this without success:
`/home/Golddouble/My\ dokuments my_search_term`

Thank you.

**Comment by cboxdoerfer** [comment]
Escaping spaces is supported yet, they're always treated as AND operators. So the only thing you can do in that case right now is to narrow it down like that: `/home/Golddouble/My dokuments/ my_search_term`

**Comment by Golddouble** [comment]
Thank you. Not sure if I understand.

> So the only thing you can do in that case right now is to narrow it down like that: `/home/Golddouble/My dokuments/ my_search_term`

But this is not working because of the space between "My dokuments" .

**Comment by cboxdoerfer** [comment]
> But this is not working because of the space within "My dokuments"

That's weird, I just tested it and it works, as expected. What FSearch does with this query is: Show all files where `/home/Golddouble/My` AND `dokuments/' are within the path AND `my_search_term` is within the file name. This matches all the files within `/home/Golddouble/My dokuments/`.

**Comment by Golddouble** [comment]
You are right. I have now tested exactly the example above.

Please note: I have more something like this:
`/home/Golddouble/My nice dokuments/ my_search_term`

or even something like:
`/home/Gold double 33/My nice dokuments/ my_search_term`

And this two eamples seems not to work.

**Comment by cboxdoerfer** [comment]
> And this two examples seems not to work.

Yes, the workaround won't work in that cases, because there's more than one space in the path. The only way to filter those right now is with the regex mode (or wildcard) mode. Are you familiar with how regular expressions work?

**Comment by Golddouble** [comment]
I only know "^" and "$".
Unfortunately I do not know how to escap spaces.

**Comment by cboxdoerfer** [comment]
@Golddouble, I just added the ability to easily use space characters in a normal search. You can either escape them with `\` like so:

`/home/Golddouble/My\ new\ dokuments my*`

or with quotation marks like so:

`"/home/Golddouble/My new dokuments" my*`

To find all files beginning with `my` in  `/home/Golddouble/My new dokuments`. If you use the PPA the new version with those changes should be available within the next 24-48 hours. Please let me know if everything works as you expected.

**Comment by Golddouble** [comment]
Wow, thank you. 
As soon as I will find it in the package manager (test tab), I will try this out.

**Comment by Golddouble** [comment]
What is the name of the latest version?
I was not able to find it here:
https://github.com/cboxdoerfer/fsearch/releases
The latest version in this list is from 24 feb 2020.

The version in my package manager (test repository) is "0.1b2+git20191012-1" .

I guess, when I want to make a package request in my distribution, then the newest version should at least be listed here:
https://github.com/cboxdoerfer/fsearch/releases

Thank you.

**Comment by cboxdoerfer** [comment]
I didn't tag a new release, because the next release is going to be the stable 0.1 release (hopefully end of Sep or start of Oct). If you want the updated dev builds you either need to use the PPA with daily builds if you use an Ubuntu based distribution or build from source.

Which distribution do you use and how did you install FSearch?

**Comment by Golddouble** [comment]
I use MX Linux, which is debian based and I have installed it with the "MX Package Installer" (test repository tab).

**Comment by cboxdoerfer** [comment]
Ah ok, I guess your options then are:

* contact the maintainer of the FSearch package in MX Linux and ask them to pull the latest changes
* build the new version yourself (it's fairly straight forward: https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions)

Sorry, there's nothing else I can do here.

**Comment by Golddouble** [comment]
Thank you.

When I choose this way:
-build the new version by myself with https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions

Does then my package manager update Fsearch in the future, like it does with all other programs? Or do I have to build it again the same way, when Fsearch has a new version again in the future?

**Comment by cboxdoerfer** [comment]
> Does then my package manager update Fsearch in the future, like it does with all other programs? Or do I have to build it again the same way, when Fsearch has a new version again in the future?

You're package manager only manages the copy you already have. When you build it from source you get an additional copy, which you need to maintain yourself, i.e. when you want a new version of that copy you need to build it again.

I'd also not recommend switching from a newer release back to an older one. Since FSearch is still in beta state there might be breaking changes, which means an older version of the program might not be able to read the database or config of a newer version properly.
