### ISSUE TITLE
404 error on link in README

### ISSUE THREAD

**Issue by Kienyew** [cboxdoerfer/fsearch#203]
I was trying to contribute to the translation of this project. When I tried to follow the original link of instruction in README.md: https://weblate.readthedocs.io/en/latest/user/index.html, it turned out the link was moved by the website. 

The above mentioned link is located in README.md > Localization > ... https://weblate.readthedocs.io/en/latest/user/index.html

I suppose the new location is and should be modified to https://docs.weblate.org/en/latest/index.html

**Comment by cboxdoerfer** [comment]
Thank you! I updated the README.md.
