### ISSUE TITLE
Can't stop updating database

### ISSUE THREAD

**Issue by Andreaptr030** [cboxdoerfer/fsearch#206]
Dear Mr. Christian Boxdoerfer,
I installed Fsearch from the terminal, a really useful application, although very essential, as  Fsearch-trunk  version 20200718+r447.1fc1b43 - ubuntu18.04.1  on Linux Mint 19.1 Cinammon (Mint based on Ubuntu ), but i had this problem: every time I open the application the indexing starts and I can't stop to change the search path, i don't see the checkbox even in the preferences; having chosen to index the whole pc I am slowed down for several minutes and I am forced to close Fsearch.
Thanks for your attention. Andrea Pietrobon, Italy

**Comment by cboxdoerfer** [comment]
Hi, the ability to disable certain paths from being updated has been added on Aug 1 and the ability to search while the database is updating on Jul 26, so your version is just a couple of days to old. I suppose you're using the PPA, so doing a system update should provide you the newest version, which allows you to search while the indexing takes place.

Please let me know of it works as you expect.

**Comment by Andreaptr030** [comment]
I actually did as you suggested (and I preferred to proceed in this way: first by completely uninstalling Fsearch and its directories and files, then as you indicated in "https://github.com/cboxdoerfer/fsearch":

sudo add-apt-repository ppa: christian-boxdoerfer / fsearch-daily
sudo apt-get update
sudo apt install fsearch-trunk

The version is now 20200813 + r539.902a5dc - ubuntu18.04.1 
The program seems to work fine and fast even in the updating database.

However, I observe that restarting the PC the Fsearch program forgets the previous databases added, except the first one I had inserted, that is, they are no longer seen in preferences > database and this forces them to be reloaded manually.

On the other hand, it was possible to insert the right-click, cut and paste into folder option within the Fsearch program itself, this would make it even more efficient and useful.

Finally I observe that the program version does not appear in Help> about and I have to look for it in the Software manager

Thank you

**Comment by cboxdoerfer** [comment]
> However, I observe that restarting the PC the Fsearch program forgets the previous databases added

This either means that FSearch crashed on exit or you or your system didn't exit FSearch properly, which means it never had a chance to save its config. If you can provide the output of FSearch I'd probably be able to tell you what happened.

> On the other hand, it was possible to insert the right-click, cut and paste into folder option within the Fsearch program itself, this would make it even more efficient and useful.

Possible yes, but it'll take a while until I start working on it.

> Finally I observe that the program version does not appear in Help> about and I have to look for it in the Software manager
>

That's a know issue of the Ubuntu builds. I'll try to fix it soon.

**Comment by cboxdoerfer** [comment]
The unkown version issue in Ubuntu builds should now be fixed. Since the original issue of this bug report seems to be fixed I'm closing this issue.

If the other issue (database not being remembered) still exists, please open a separate issue with more informations. Thanks.

**Comment by Andreaptr030** [comment]
In the meantime, thank you very much for your attention and for answering me so promptly, though I couldn't answer you equally soon.
Thank you for fixing the version number that is now visible in Help/About.

Andreaptr030, Italy
