### ISSUE TITLE
Error in fsearch.desktop

### ISSUE THREAD

**Issue by axzxc1236** [cboxdoerfer/fsearch#207]
How to reproduce:

1. Install fsearch (In my case I installed from PPA, using Pop! OS (Ubuntu based) 20.04)  
2. In terminal, cd to the folder that contains fsearch.desktop (In my case it's `/usr/share/applications`)  
3. Use the command `desktop-file-validate fsearch.desktop` (requires desktop-file-utils preinstalled)
4. Terminal shows error messages  
> fsearch.desktop: error: file contains multiple keys named "Name[ko]" in group "Desktop Entry"
> fsearch.desktop: error: file contains multiple keys named "Comment[tr]" in group "Desktop Entry"
> fsearch.desktop: error: file contains multiple keys named "Keywords[tr]" in group "Desktop Entry"

This error won't affect usability of the desktop file, but produces errors with my other software.  
(I'm trying to create an AppImage out of PPA with [pkg2appimage](https://github.com/AppImage/pkg2appimage), can't create an AppImage because of the error)

**Comment by cboxdoerfer** [comment]
Thanks for reporting, I'll fix those issue.

**Comment by cboxdoerfer** [comment]
Fixed!
