### ISSUE TITLE
Case insensitive search is broken for Turkish

### ISSUE THREAD

**Issue by bilgincoskun** [cboxdoerfer/fsearch#210]
Turkish has two "I"s compared to english: I and İ. Conversion to lowercase as follows: İ->i and I->ı . When searched for İ or ı, fsearch only matches with İ or ı and not their lower/upper counterparts (i or I). On the other hand i or I matches both letters. May I suggest either a) considering locale when converting case  or b) adding an option to convert language specific letters to similar english letters (e.g. Firefox seems to use this so when searching for keyword **İ**terator or **ş**hip in bookmarks, it returns Iterator or ship.

**Comment by cboxdoerfer** [comment]
Thank you for reporting. Yes, case conversion isn't locale aware. I'll need to do some research at how to handle this, so it doesn't affect search performance much.

**Comment by cboxdoerfer** [comment]
Here's an idea that solves this and actually would even improve search performance in almost all cases significantly: 

Convert all of the file names to lower case (locale aware) and keep them in RAM, in addition to the on-disk file names. Then we don't need to convert them each time a search is performed. This saves a lot of CPU cycles and the search (when match case is disabled) becomes much faster and we treat locales with more complex case conversion properly. 

The big downside is that this uses quite a lot of RAM. A brief test shows that with my library of 800.000 files the memory consumption jumps from 200 to 300 MB, which is fine for me but I think there are others who don't like increased RAM usage. An option to chose between both approaches would be possible, at the cost of making the code slightly more complex. Tough decision ^^

**Comment by bilgincoskun** [comment]
Another idea is adding ASCII representation column to the database which would be empty when the feature is not used or if filename is already ASCII. I am not sure how difficult would be to implement but this way runtime wouldn't be affected since only the query would need to be converted not all results.  Another benefit of this is since Unicode relatively adopted recently old files (or even new files due to habit)  are named such that they only contain English characters (so kırmızı becomes kirmizi) so it would lead to more accurate results.

**Comment by cboxdoerfer** [comment]
Yes, I think this is what Everything does. But, unless I'm missing something, this would still require converting the results. For example a simple query like  `İ`would become `I`or `i` (depending on whether match case is active) in its ASCII representation. Now when we try to match that against a file named `İ`, it'll fail unless we also convert the file name to its ASCII representation.

**Comment by bilgincoskun** [comment]
Yes I meant converting filenames to ASCII during database update and storing along with the original name. My guess is converting filenames would be negligible compared to traversing filesystem so updating database would not be affected much. And if the feature is not used then ASCII field would be just empty so overhead to the db size would be minimal. I also think search performance wouldn't change much since searching in ASCII field would suffice instead of searching in both ASCII and original fields.

**Comment by cboxdoerfer** [comment]
@bilgincoskun, fixed.

**Comment by bilgincoskun** [comment]
@cboxdoerfer , thank you for making an already great program better.

**Comment by bilgincoskun** [comment]
I tried latest version from Aur but the issue still persists. e.g. when I try to search for indirilenler (downloads) it only finds lower case and not İndirilenler (and vice versa). Am I missing something?

**Comment by cboxdoerfer** [comment]
No, I can confirm that. I only tested it with files with single character names and it worked there, but apparently it breaks as soon as `İ` is followed by more characters. This should now be fixed.

**Comment by cboxdoerfer** [comment]
Oh and unfortunately performance kinda sucks now when you have i's in your search terms with Turkish locale enabled, because it'll always perform a unicode search which is much slower than the default ascii search. Fixing that is a separate issue that involves more work.

**Comment by bilgincoskun** [comment]
Ok, now "indirilenler" both finds "indirilenler" and "İndirilenler" but "İndirilenler" only finds "İndirilenler", but looking at ascii search results I think this is the intended behaviour (acting case insensitive if all cases are small I mean). Yeah, I noticed performance hit due to unicode conversation , but that was expected. Thanks for all your effort. By the way If you're ok with ascii-inner-representation approach, I might want to try to implement it.

**Comment by cboxdoerfer** [comment]
> but "İndirilenler" only finds "İndirilenler

That's actually a feature. By default if one character is upper case then FSearch uses a case-sensitive search for that query. You can disable that feature in`Preferences -> Search -> Match case when query contains at least one upper case character`

> Thanks for all your effort. By the way If you're ok with ascii-inner-representation approach, I might want to try to implement it.

Thanks, I'd appreciate that. Maybe this could be done as a toggle-able option (fast and inaccurate ascii search vs slower more accurate search). But before you start working on it, please open a new issue where we can discuss the details.

**Comment by bilgincoskun** [comment]
Ok, will do when I have more free time.
