### ISSUE TITLE
Why I can't close fsearch?

### ISSUE THREAD

**Issue by silocoder** [cboxdoerfer/fsearch#212]
It says task is active. Not sure with what. 

![image](https://user-images.githubusercontent.com/57298274/91508177-c1af6780-e8a4-11ea-962b-10bd84cd3aff.png)

**Comment by cboxdoerfer** [comment]
I need more information. For example, which version is FSearch (apt package version or commit if you built from source)?

**Comment by silocoder** [comment]
Linux Mint 20
Installed via Software Manager 

![image](https://user-images.githubusercontent.com/57298274/91603798-9f1c5d80-e93b-11ea-9fbb-a30405fbed39.png)

Also About has no mention of version

![image](https://user-images.githubusercontent.com/57298274/91603928-ce32cf00-e93b-11ea-98bf-bd6d68eddd74.png)

**Comment by cboxdoerfer** [comment]
Thanks! You're not using the most recent version, the current one likely doesn't have this issue. So please update your system and report back if this helped resolving this issue.

**Comment by cboxdoerfer** [comment]
Closing. This has most likely already been fixed. If it still happens with the latest builds, let me know and we can reopen it.
