### ISSUE TITLE
Fsearch, database not remembered

### ISSUE THREAD

**Issue by Andreaptr030** [cboxdoerfer/fsearch#214]
However, I observe that restarting the PC the Fsearch program forgets the previous databases added

This either means that FSearch crashed on exit or you or your system didn't exit FSearch properly, which means it never had a chance to save its config. If you can provide the output of FSearch I'd probably be able to tell you what happened.

... ... ... 

Dear Mr. Christian Boxdoerfer,

Your program correctly saves the database when I close it but not when I do a soft shutdown. So I agree with you that my system (linux Mint 19) probably doesn't properly communicates the shutdown to FSearch. 
Now I'm forced each time to close your program and reopen it just in order to make sure that my change is not lost.

"If you can provide the output of FSearch I'd probably be able to tell you what happened".
Where is it ? 
Is it the  fsearch.conf  file in the config/fsearch  directory? 

I think that a solution could be simply to save the config file each time the user adds/removes a Path in Edit\Preferences\Database or whenever he changes a preference, it means whenever he does OK in the dialog Preferences.

I attach files
My best regards
Andreaptr030, Italy

SAVING CORRECTLY (ONLY THE FINAL PART OF THE CONFIGURATION FILE, THE REST REMAINS THE SAME):

[Database]
update_database_on_launch=false
exclude_hidden_files_and_folders=false
follow_symbolic_links=false
location_1=/
location_enabled_1=false
location_update_1=true
location_num_items_1=0
location_2=/home/gmm
location_enabled_2=true
location_update_2=true
location_num_items_2=0
location_3=/media/gmm/487A6F587A6F4234
location_enabled_3=true
location_update_3=true
location_num_items_3=0
location_4=/media/gmm/01D502AECE652D80
location_enabled_4=true
location_update_4=true
location_num_items_4=0
exclude_files=

NOT SAVING CORRECTLY:
[Interface]
single_click_open=false
restore_column_configuration=true
double_click_path=false
enable_list_tooltips=true
enable_dark_theme=false
show_menubar=true
show_statusbar=true
show_filter=true
show_search_button=true
show_base_2_units=false
action_after_file_open=0
action_after_file_open_keyboard=false
action_after_file_open_mouse=false
restore_window_size=true
window_width=1366
window_height=740
show_listview_icons=true
show_path_column=true
show_type_column=true
show_size_column=true
show_modified_column=true
sort_ascending=true
sort_by=Date Modified
name_column_width=809
path_column_width=257
type_column_width=100
size_column_width=75
modified_column_width=125
name_column_pos=0
path_column_pos=1
type_column_pos=2
size_column_pos=3
modified_column_pos=4

[Dialogs]
show_dialog_failed_opening=true

[Search]
search_as_you_type=true
auto_search_in_path=true
search_in_path=false
enable_regex=false
match_case=false
hide_results_on_empty_search=true
limit_results=true
num_results=1000

[Database]
update_database_on_launch=false
exclude_hidden_files_and_folders=false
follow_symbolic_links=false
location_1=/
location_enabled_1=false
location_update_1=true
location_num_items_1=0
exclude_files=

**Comment by cboxdoerfer** [comment]
Thanks for the information.

> I think that a solution could be simply to save the config file each time the user adds/removes a Path in Edit\Preferences\Database or whenever he changes a preference, it means whenever he does OK in the dialog Preferences.

Yes, that makes sense. I'll change that.

**Comment by cboxdoerfer** [comment]
Fixed.

**Comment by Andreaptr030** [comment]
Thanks a lot,

your program now works perfectly, it remembers my choices and the indexes of the databases don't get corrupted when the computer abruptly shuts down.

Best Regards,

Andrea
