### ISSUE TITLE
[CRASH] Update database while editing excluded pattern

### ISSUE THREAD

**Issue by darkguy2008** [cboxdoerfer/fsearch#216]
Thanks for this awesome app! Been missing an Everything alternative since I just switched to KDE Neon :)

However, I found a small crash (using your ppa from fsearch-trunk): When you are updating the database, and then go to preferences -> exclude and type a pattern then press OK, the app will stop responding. Maybe it should stop the indexing (if any), recreate the database and restart?

Thanks!

**Comment by cboxdoerfer** [comment]
Thanks for reporting. That's a known limitation. In fact FSearch doesn't crash, the UI just freezes until the update finished. But I will fix that soon and I will also add an option to cancel the current update.

> Maybe it should stop the indexing (if any), recreate the database and restart

Yes, that's the plan.

**Comment by cboxdoerfer** [comment]
@darkguy2008 , this should be fixed. Now the current indexing process restarts immediately when you change the database configuration, without blocking the UI. The indexing process can also be aborted at any time from the menu.

The PPA should be updated with the fixed version in one or two days.
