### ISSUE TITLE
app freezes when I close it while database is updating

### ISSUE THREAD

**Issue by veksha** [cboxdoerfer/fsearch#220]
Version is latest (2e160fcae40660ad2504795b2bb94a1fd02ea2ea)
It's good that "stop db updating" button is implemented now, but can we trigger it when user closes FSearch application?

to reproduce:
1. start application
2. watch status bar that db update is in process.
3. quickly close window.
4. the app is frozen now and stays in this state forever.

//void-linux.openbox-wm

**Comment by cboxdoerfer** [comment]
Thank you for reporting! Fixed.
