### ISSUE TITLE
Case Insensitive Search broken for ALL CAPS

### ISSUE THREAD

**Issue by Copyrites** [cboxdoerfer/fsearch#223]
I'm using 0.1beta4 on ubuntu 20.04.  With "Match Case" turned off searching for all caps text does not work.  It is easily repeatable - search in all lowercase - get a hit, then retype in all uppercase - no hits.  In fact, it seems like adding just one uppercase character (where the target filename only has a lowercase character) is enough to make not match.

For example:

1. Actual filename "Foo"
2. type "foo" -  matches
3. type "fOo" - no matches
4. type "Foo" - matches

**Comment by cboxdoerfer** [comment]
That's a feature and can be disabled, see `Preferences -> Search -> Match case when query contains at least one upper case character`

**Comment by cboxdoerfer** [comment]
Maybe I need to disable it by default. You're not the first one to report it as a bug, so it seems misleading. I'll think about it.

**Comment by Copyrites** [comment]
Maybe change the "Match Case" menu entry to indicate the setting.  Something like "Case Insensitive (unless Uppercase)"  Or could put it in the status bar where it currently just says "CASE."  Seems like there is a lot of space available there.

**Comment by cboxdoerfer** [comment]
Yes, maybe showing something like `SMART CASE` and `SMART PATH` in the status bar when their respective options are enabled and the query contains upper case characters or path separators, would solve that confusion.

**Comment by cboxdoerfer** [comment]
The status bar now indicates when those modes are active by showing CASE or PATH in a dimmed style when the query contains upper case characters or path separator and the corresponding settings are enabled. There's also a tooltip description when hovering over those labels. Hope this makes it less confusing.
