### ISSUE TITLE
untranslated text "Sorting..."

### ISSUE THREAD

**Issue by veksha** [cboxdoerfer/fsearch#224]
https://github.com/cboxdoerfer/fsearch/blob/0b198c6b0c9e3d0eb06656579660a505560f2289/src/database.c#L1024

![fs3](https://user-images.githubusercontent.com/275333/94874722-60f2ec00-045b-11eb-92bf-b3117b2152d4.png)

this string has no translation.

**Comment by cboxdoerfer** [comment]
Thx, updated and is now editable on Weblate.

**Comment by veksha** [comment]
I noticed another text without translation support.
In Preferences "Cancel" and "OK" buttons. :)

**Comment by cboxdoerfer** [comment]
Thanks :) Fixed on master.

**Comment by veksha** [comment]
<img src="https://user-images.githubusercontent.com/275333/95119607-e1179b00-0754-11eb-84c8-b57ee684501c.png" width="300">
I guess Cancel and OK buttons are still in English only.

**Comment by cboxdoerfer** [comment]
Oh yeah, just pushed the fix. Thx
