### ISSUE TITLE
Can't search full result without CASE

### ISSUE THREAD

**Issue by DuongQuy123** [cboxdoerfer/fsearch#226]
In last month, when fsearch updated I can't have full all result, only when CASE

![1](https://user-images.githubusercontent.com/68831019/95401068-7a51d780-0936-11eb-847c-87f47dba19ad.png)
No Capitalization no CASE : 8 result

![2](https://user-images.githubusercontent.com/68831019/95401069-7b830480-0936-11eb-8da7-3e965013ce11.png)
Capitalization no CASE: 0 result

![3](https://user-images.githubusercontent.com/68831019/95401072-7c1b9b00-0936-11eb-9f16-2e6aea99d412.png)
Capitalization with CASE: 431 result

![4](https://user-images.githubusercontent.com/68831019/95401075-7d4cc800-0936-11eb-8e86-1708749c4df5.png)
No Capitalization with CASE: 593 result

My config file:
`[Interface]
single_click_open=true
highlight_search_terms=true
restore_column_configuration=true
restore_sort_order=true
double_click_path=true
enable_list_tooltips=true
enable_dark_theme=true
show_menubar=true
show_statusbar=true
show_filter=true
show_search_button=true
show_base_2_units=true
action_after_file_open=0
action_after_file_open_keyboard=false
action_after_file_open_mouse=false
show_indexing_status=true
restore_window_size=true
window_width=1366
window_height=691
show_listview_icons=true
show_path_column=true
show_type_column=true
show_size_column=true
show_modified_column=true
sort_ascending=true
sort_by=Type
name_column_width=816
path_column_width=502
type_column_width=100
size_column_width=75
modified_column_width=125
name_column_pos=0
path_column_pos=1
type_column_pos=2
size_column_pos=3
modified_column_pos=4

[Dialogs]
show_dialog_failed_opening=true

[Search]
search_as_you_type=true
auto_search_in_path=true
auto_match_case=true
search_in_path=false
enable_regex=false
match_case=false
hide_results_on_empty_search=true
limit_results=false
num_results=1000

[Database]
update_database_on_launch=true
exclude_hidden_files_and_folders=false
follow_symbolic_links=false
location_1=/Data
location_enabled_1=true
location_update_1=true
location_num_items_1=0
exclude_files=
`
Please help me, I use your search tool to manager my file and folder, I used your software regularly, everyday. Love your job and thankyou very must.

**Comment by cboxdoerfer** [comment]
Thanks for this detailed bug report, the issue should now be fixed!

**Comment by DuongQuy123** [comment]
Thank you very much, I use foder and file as mindmap tree to remember most of thing i learned and work, your software is one of most important thing i use in my laptop everyday. You make it perfect, thank you with all of my heart. Love You!!!
