### ISSUE TITLE
version info

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#229]
Where can I find the information, which Fsearch version I have installed on my system?

I have tried out 
Menu -> help -> Info

But there I was not able to find the version.

Do I miss anything?
Thank you.

**Comment by cboxdoerfer** [comment]
The version info should be in `Help -> About` below the application name. Likely something like: 0.1beta4

You can also use the command line: `fsearch --version`

**Comment by Golddouble** [comment]
Thank you.

OK, do you mean the position where the word "unknown" lies?

![Fsearch version](https://user-images.githubusercontent.com/13977359/97081296-c58c0b80-1601-11eb-8a9a-c7100351d378.png)

**Comment by cboxdoerfer** [comment]
Yes, that probably means you're using an old version or something in the build/packaging process went wrong. How did you install FSearch?

**Comment by Golddouble** [comment]
It's from MX Test Repositorium.

When I try 
`fsearch --version`

I get this:
```
Golddouble@mx:~
$ fsearch --version
loaded config file
FSearch UNKNOWN
Golddouble@mx:~
$ 
```

**Comment by cboxdoerfer** [comment]
What does `apt show fsearch` or `apt show fsearch-trunk` (depending on how mx linux named the package) show?

**Comment by Golddouble** [comment]
```
$ apt show fsearch
Package: fsearch
Version: 0.1.b2+git20191012-1mx19
Status: install ok installed
Priority: optional
Section: utils
Maintainer: Steven Pusser <stevep@mxlinux.org>
Original-Maintainer: Christian Boxdörfer <christian.boxdoerfer@posteo.de>
Bugs: mailto: <stevep@mxlinux.org>
Installed-Size: 630 kB
Depends: libatk1.0-0 (>= 1.12.4), libc6 (>= 2.4), libcairo-gobject2 (>= 1.10.0), libcairo2 (>= 1.2.4), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.41.4), libgtk-3-0 (>= 3.16.2), libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0), libpcre3
Conflicts: fsearch-dev, fsearch-trunk
Homepage: https://cboxdoerfer.github.io/fsearch/
Download-Size: unbekannt
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: fast file search utility
    FSearch is a fast file search utility for Unix operating systems,
    inspired by Everything Search Engine and based on GTK+3.
```

**Comment by cboxdoerfer** [comment]
Ok, I see, the package is from a year ago. That's why the version isn't shown - there was a bug in the build system at the time.

If you want to get a more recent version with the latest enhancements and bug fixes you might want to contact the package maintainer or build it manually.

**Comment by Golddouble** [comment]
Thank you.

**Comment by cboxdoerfer** [comment]
No problem 👍
