### ISSUE TITLE
[question] stale PO files

### ISSUE THREAD

**Issue by veksha** [cboxdoerfer/fsearch#231]
I got into a situation where new translation strings were not present in a new build no matter what I do.
I tried "make clean" command but translations were still old.

I looked into "po" subdirectory and found out that ru.po and ru.gmo files were different. (and .po~ also)
the newest changes were present in .po file, but not in .gmo.

so "make && make install" command did nothing to make translations updated to the newest versions.
BUT sometimes it works. So I am wondering what is ideal build command should look like.
maybe "./autogen.sh && ./configure && make && make distcheck"?
this worked well but I think it's an overkill for me.

**Comment by cboxdoerfer** [comment]
Hi, to update the gmo files you can run `make -C po update-gmo` from the toplevel source dir. I'm not really sure why this isn't automatically done with `make && make install`, but I'll try to figure it out.

**Comment by cboxdoerfer** [comment]
Just FYI, since meson is now the default build system used, to update the locale files you can do:

ninja fsearch-pot && ninja fsearch-update-po && ninja install
