### ISSUE TITLE
[Feature request] Add cut to copy ability

### ISSUE THREAD

**Issue by musictrivianut** [cboxdoerfer/fsearch#234]
Hi, understand that drag-and-drop functional may not be coming in the future and I can't really complain about that with free software :-)

So, would it be possible to include the ability to "cut" files, in addition to "copy"?  I end up using fsearch to move a lot of files around, organizing them.  Having to copy, put them in the new directory and then go back and delete the old files seems to be a couple of extra steps (of course, I'm not a programmer, so I could be way off-base).

Definitely not a big deal if it cannot be implemented.  I certainly won't stop using fsearch because of it.  It's a great piece of software (as such, thank you very much for putting time into it!).

Thanks for considering,
Wayne

**Comment by cboxdoerfer** [comment]
Hi,

>So, would it be possible to include the ability to "cut" files, in addition to "copy"?

Yes, that's definitely possible and I just implemented it. But for now the user experience isn't great, like with all the other file operations (copy, delete, trash), because the database won't detect those changes until the next database update. Fixing that requires more work, which I'm afraid will have to wait a little.

**Comment by musictrivianut** [comment]
You, sir, are a superstar!

**Comment by cboxdoerfer** [comment]
No problem 👍

**Comment by musictrivianut** [comment]
I'm not sure if you made more modifications after you posted what you did about the database not detecting changes until next update, but I just used fsearch to cut a file and paste it and it knew that the original file was gone (icon changed to the red circle with slash).

That is pretty much exactly what I was looking for, so maybe you don't have to delve any further?

Really, *really* appreciate you adding that!

**Comment by musictrivianut** [comment]
Hello again,

I know this is closed, but something has definitely changed with the new function.  Before, as noted in my previous post, the icon for files that had been moved changed to a red circle with a slash (black background).  After updating (I get the daily pulls), now there is no icon or it's blank or whatever.

Definitely not a complaint, just a note to let you know, just in case it is an unintended side effect of something else.

Thanks again!

Wayne

**Comment by cboxdoerfer** [comment]
Hi, thx that was indeed an unintended side effect of a small optimization I did. It's now fixed.

**Comment by musictrivianut** [comment]
Okay, cool.  Glad I could be of help.
