### ISSUE TITLE
[BUG] results are hidden when limit is not set

### ISSUE THREAD

**Issue by veksha** [cboxdoerfer/fsearch#235]
FSearch 0.1beta4.483-3469b

**To Reproduce**

1. uncheck "Hide results";
2. uncheck "Limit number of results";
3. no results are shown in the main window.

**Expected behavior**
results are there

**This is workaround for me**
![fs1](https://user-images.githubusercontent.com/275333/97788461-c56fab00-1bc1-11eb-8c3c-4dbb89934a3b.png)
I set max limit.

**Comment by cboxdoerfer** [comment]
Thx for reporting, should be fixed.
