### ISSUE TITLE
How to have FSearch search all Linux folders?

### ISSUE THREAD

**Issue by androidmessages** [cboxdoerfer/fsearch#236]
I found a workaround: include all folders listed under Computer/File System (such as usr, etc, lib), but is there an easier way to have FSearch comb through the entire Linux system rather than just the home/user/ folder?

**Comment by cboxdoerfer** [comment]
Yes, you can do that by including the filesystem root `/`. Or do you mean something else?

**Comment by androidmessages** [comment]
Yup! Works perfectly!! Thank you
![image](https://user-images.githubusercontent.com/52135169/98409818-86b67680-2041-11eb-9b5d-0c505d59ee6d.png)

**Comment by cboxdoerfer** [comment]
No problem 👍
