### ISSUE TITLE
Column's visibility/invisibility is not consistent

### ISSUE THREAD

**Issue by tong2shot** [cboxdoerfer/fsearch#237]
**Step to reproduce:**
1. _Name_, _Path_, _Type_, _Size_, _Date Modified_ columns by default are visible. 
2. Now I want only _Name_, and _Path_ columns visible. I can do that by right-clicking column bar and deselecting _Type_, _Size_, and _Date Modified_ columns indicator.  
3. Close Fsearch and reopen it.

**Actual result:**
All columns are now visible again, but the visibility indicator indicates that only _Name_, and _Path_ column visible. If I reenable _Type_ column, I get two _Type_ columns.

**Expected result:**
Only _Name_, and _Path_ columns should be visible as indicate by the column indicator.

**Comment by cboxdoerfer** [comment]
Thx, the columns appearing twice is definitely a bug.

Do you have the "Remember column configuration" option enabled, otherwise it's actually the expected result to have all the default columns visible on the next launch.

**Comment by tong2shot** [comment]
I just realize that there's "Remember column configuration" option in preferences. But still, when the option is disabled, shouldn't the column indicator follows the columns state (all visible)? So that the column appearing twice doesn't happen.

Also I don't understand why there's "Remember column configuration" option in preferences? Other programs (Dolphin, Krusader, Akregator, uGet, etc) don't have the similar option. I mean, the column configuration is auto saved when you exit in other programs. I think it's more intuitive that way.

Thanks.

**Comment by cboxdoerfer** [comment]
This should be fixed now.
