### ISSUE TITLE
allow exclusion of directories matching a pattern from indexing  - i.e.  .svn  .git 

### ISSUE THREAD

**Issue by jreidthompson** [cboxdoerfer/fsearch#24]
it would be helpful to be able to exclude from indexing all .svn directories with a single entry of the pattern  .svn

**Comment by cboxdoerfer** [comment]
Yes, this sounds like a useful feature. I'll add that.

**Comment by cboxdoerfer** [comment]
Added. You can find it in **Preferences -> Database -> Exclude -> Exclude Files**
