### ISSUE TITLE
[BUG] RegEx not working

### ISSUE THREAD

**Issue by superbonaci** [cboxdoerfer/fsearch#240]
Using ubuntu package `FSearch 0.1beta4`.
Example path:
```
/media/data//Avatars/Station-Forfait.gif
```
i use regex `vatar.*orf` and does not find the file on fsearch, however this website does recognize the match: https://regex101.com/r/faWmap/1/

Could you check what is going on?

**Comment by veksha** [comment]
enable search by PATH and try again.

**Comment by superbonaci** [comment]
@veksha thank you very much, it works now! You have to enable both:

- Search -> Search in Path (Ctrl+U)
- Search -> Enable RegEx (Ctrl+L)

Also if you disable  `Match Case (Ctrl+I)` it will be case insensitive, so you don't need to use the `[Ff]` thing to include both uppercase and lowercase.
