### ISSUE TITLE
[feature request] mac version

### ISSUE THREAD

**Issue by kocoman1** [cboxdoerfer/fsearch#248]
[feature request] mac version.
Will a version for mac be on the roadmap? thx

**Comment by cboxdoerfer** [comment]
No, I don't know any simple way to develop for macOS without having access to a Mac, which I don't have.

So unless someone else starts to work on a macOS port I'm afraid this won't happen.

**Comment by cboxdoerfer** [comment]
Duplicate of #7 

Closing.
