### ISSUE TITLE
Question: What is "Search in Path" supposed to do?

### ISSUE THREAD

**Issue by pauljurczak** [cboxdoerfer/fsearch#251]
I'm using FSearch 0.1beta4 on Ubuntu 18.04.5 and (un)checking `Search in Path` doesn't change search results, What is it supposed to do? My guess was that it limits the search to a specific path, but it doesn't do that.

**Comment by veksha** [comment]
by default your keywords are searched in filenames only.
"Search in Path" - tell fsearch to scan path part too.

**Comment by pauljurczak** [comment]
Thank you. Perhaps an example or description on https://github.com/cboxdoerfer/fsearch page would be help some users in the future.

BTW, it would be nice to be able to easily limit the search to a given directory without changing the database in `Preferences`.

**Comment by veksha** [comment]
"Custom query syntax" is planned in version 0.2 (see [/wiki/Roadmap](https://github.com/cboxdoerfer/fsearch/wiki/Roadmap))
But for now you can just use multiple keywords, one of them will be path to your directory.

**Comment by cboxdoerfer** [comment]
> Perhaps an example or description on https://github.com/cboxdoerfer/fsearch page would be help some users in the future.

Yes, I agree, the documentation is basically non-existent at the moment and definitely needs to be taken more seriously in the future. I will add a description of the search and all its options to the wiki soon.

**Comment by Golddouble** [comment]
> BTW, it would be nice to be able to easily limit the search to a given directory without changing the database in Preferences.

>  I just added the ability to easily use space characters in a normal search. You can either escape them with \ like so:
> 
> /home/Golddouble/My\ new\ dokuments my*
> 
> or with quotation marks like so:
> 
> "/home/Golddouble/My new dokuments" my*
> 
> To find all files beginning with my in /home/Golddouble/My new dokuments. If you use the PPA the new version with those changes should be available within the next 24-48 hours. Please let me know if everything works as you expected.

Source: https://github.com/cboxdoerfer/fsearch/issues/201#issuecomment-683409498
