### ISSUE TITLE
[BUG] modified date sorting + limit number of results

### ISSUE THREAD

**Issue by jouven** [cboxdoerfer/fsearch#252]
**Describe the bug**
Sorting by "date modified" and limiting the amount results produces wrong results, it's easier to see filtering only by files, because the results don't show the oldest files or the newest files, depending if the sort is ascending or descending. Disabling results limits fixes the issue, but I have 3.6~million indexed files which slows down fsearch a lot. Found the issue checking which were the last modified files of all the indexed and realized they were not showing correctly

**Desktop (please complete the following information):**
 - OS: debian bullseye
 - How you installed FSearch: manually
 - Version: FSearch 0.1beta4.623-1c57
 - Output of `localectl status`: 
System Locale: LANG=en_GB.UTF-8
                  LANGUAGE=en_GB:en
       VC Keymap: n/a
      X11 Layout: es
       X11 Model: pc105

**Comment by cboxdoerfer** [comment]
That's a known issue which has been bothering me a lot as well for quite a while and I'm currently working on it.

Long story: The only reason why the option to limit the number of results is there in the first place are the performance issues you describe.

What's slowing down FSearch in this case is the GtkTreeView which is used to display the results. It just can't handle that many items and the only way to fix this is to implement a custom listview widget. However I actually started working on it yesterday and it can already display and scroll basically any amount of files instantly with less memory usage, however there's still a lot of work to be done before I can release it: selection handling, sorting, keyboard navigation and a column header are not implemented yet.

**Comment by cboxdoerfer** [comment]
Some progress report on the new listview:

* selection handling is done and it's now also way faster than before: with the old listview selecting ~2.3 million files took ~6 seconds, with the new listview it's down to 0.4s
* mouse and keyboard handling are mostly done (rubberband selection is still missing)
* sorting has been added and its performance improved a lot: reversing the sort order is now instant and sorting ~2.3 million files by modification time went from 17 seconds to 0.5 seconds
* column headers are now mostly finished (toggling them on/off doesn't work yet)
* the visuals improved a lot compared to a couple of days ago, it should look almost identical to the GtkTreeView, I just can't seem to figure out how to style the column headers to match the GtkTreeView theme style (however I actually prefer the new look): 

![2021-03-31_16-52](https://user-images.githubusercontent.com/6108388/113164574-8497c300-9241-11eb-91f7-a0ea0677f751.png)

Currently the new listview also doesn't work well with languages with right-to-left scripts, which is something I need to work on too.

**Comment by cboxdoerfer** [comment]
This should now be fixed on master. I'll close the bug report, but feel free to report back if any issues pop up.
