### ISSUE TITLE
[BUG] Asstertion Failure on First Usage

### ISSUE THREAD

**Issue by lucidBrot** [cboxdoerfer/fsearch#253]
**Describe the bug**
I have installed from the ubuntu apt PPA. started using `fsearch`  in the terminal.
The GUI showed up and looked like it started indexing the files. I clicked the text search box and started typing a word starting with `w`. That crashed ` fsearch`:

```
[config] loading failed (0.022000 ms)
[application] disable action: update_database
[application] enable action: cancel_update_database
[application] disable action: update_database
[application] enable action: cancel_update_database
[database_update] finished in 0.24 ms
[database_scan] scan location: /home/generic
[database_ref] increased to: 2
[search] 
[database_ref] increased to: 3
[database_unref] dropped to: 2
[database_ref] increased to: 3
[database_unref] dropped to: 2
[database_unref] dropped to: 1
[database_ref] increased to: 2
[search] w
[search] token 0: w
fsearch: array.c:129: darray_get_num_items: Assertion `array != NULL' failed.
Aborted (core dumped)
```

**To Reproduce**
I can actually reproduce this. Open fsearch, click the box, type "who", and it crashes. It does not crash when I don't type anything.

**Expected behavior**

**Desktop**
OS:
```bash
generic@motorbrot:~$ uname -a
Linux motorbrot 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
``` 
 - How you installed FSearch [e.g. built manually, PPA, AUR]
 ```bash
sudo add-apt-repository ppa:christian-boxdoerfer/fsearch-daily
sudo apt-get update
sudo apt install fsearch-trunk
```
 - Version [output of `fsearch --version`]
 ```
 fsearch --version
FSearch 0.1beta4
 ```
 - Output of `localectl status`
 ```bash
generic@motorbrot:~$ localectl status
   System Locale: LANG=en_US.UTF-8
                  LANGUAGE=en_US:en
                  LC_NUMERIC=de_CH.UTF-8
                  LC_TIME=de_CH.UTF-8
                  LC_MONETARY=de_CH.UTF-8
                  LC_PAPER=de_CH.UTF-8
                  LC_NAME=de_CH.UTF-8
                  LC_ADDRESS=de_CH.UTF-8
                  LC_TELEPHONE=de_CH.UTF-8
                  LC_MEASUREMENT=de_CH.UTF-8
                  LC_IDENTIFICATION=de_CH.UTF-8
       VC Keymap: sg
      X11 Layout: ch,us,de
     X11 Variant: de_nodeadkeys,,ru
generic@motorbrot:~$ 
```

**Additional context**
That was during the very first launch and on the second launch reproduced. Now that I have given it enough time to build the database once, the issue seems to be gone.

**Comment by cboxdoerfer** [comment]
Thank you for this detailed report! Yes, that's probably caused because the database was empty on the first launch. I'll fix that.

**Comment by cboxdoerfer** [comment]
Fixed. The update should available for Ubuntu within in the next day.
