### ISSUE TITLE
[feature request] re Column Display

### ISSUE THREAD

**Issue by kajodowe** [cboxdoerfer/fsearch#254]
Request that columns have ability to be moved either left or right, to allow changing the width of columns, and to center justify columns (in particular the date and time column). Thank you for all your efforts! I use fsearch daily -- multiple times per day!

**Comment by cboxdoerfer** [comment]
Yes, making columns more configurable is already on my todo list. I'm currently writing a custom listview and once it has feature parity with the current list I'm going to work on that.

What do you mean with "center  justify columns"?

**Comment by kajodowe** [comment]
Hi Christian -- I just meant to center the date modified column. But maybe
an indentation would be more appropriate -- when I look at fsearch in full
screen the date column is far to the right. But I realize that if you make
the columns configurable that should fix the problem.

Thanks very much for all your work on FSearch! Well done!

-Allen

**Comment by kajodowe** [comment]
Hi Christian -- I submitted this issue and have now since realized that there is nothing wrong with fsearch. The problem I was having with fsearch columns is related to the fact that on my slower computer I am still using GTK2 because in some cases GTK3 caused programs to run extremely slow. With GTK2 the dates in the last column ("Date Modified") go off screen and can't be read. On my newer computer running GTK3 this is not a problem. I should have noticed that you had specified that GTK3 was a requirement for running fsearch.

All is well! Thanks again!
