### ISSUE TITLE
Higher contrast themes

### ISSUE THREAD

**Issue by paul1149** [cboxdoerfer/fsearch#255]
Thanks for FSearch; great program, very useful.

I find it hard to read the text in the Results. The Light theme isn't too bad, but the Dark theme, which I prefer, has Path, Type, and Size text that is very hard to discern. I wish the themes either had more contrast or were configurable.

Thank you.

**Comment by cboxdoerfer** [comment]
Yes, currently the text of all columns except the name column are dimmed, but I agree this is a questionable design choice and I'll revert that with the new results view. Making the colors configurable is already on my todo list.

**Comment by cboxdoerfer** [comment]
Btw. if you want to try out the new results view, with higher contrast text, the code is already in the `listview` branch. Otherwise it'll take a month or so before it lands in master.

**Comment by paul1149** [comment]
Thanks so much. That is excellent news. I'll look at the code, but if it requires building, etc, that's out of my league at the moment, and I'll simply wait. Be well.

**Comment by paul1149** [comment]
Oh yes, that is a very nice Dark theme! Makes searching so much easier. thanks much again.
