### ISSUE TITLE
[Feature request] please mark the search phrase with bold size in the result list

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#257]
Especially when the option ->menu->search->search in path is checked it is difficult to see where the searched phrase is. Sometimes it is in the list at the right in the filename. Sometimes it is not in the right in the filename, because the search phrase was found in the path.

If the font would be bold, then the eyes would be able to catch the search phrase faster. This would make Fsearch more user friendly.

**Comment by cboxdoerfer** [comment]
That's already supported: https://user-images.githubusercontent.com/6108388/94472642-51f60a80-01cb-11eb-9b8c-e38fe2c02e43.png

Maybe it's disabled in your config? See **Preferenfes -> Search -> Show highlighted search terms** 

Or maybe you're FSearh package/build is too old.
