### ISSUE TITLE
font color in some column in not good in kde

### ISSUE THREAD

**Issue by Maziar123** [cboxdoerfer/fsearch#259]
Hi

in KDE with many gtk themes some column have very light gray font and near invisible
![Screenshot_20210502_190806](https://user-images.githubusercontent.com/6292459/116817023-c2a64080-ab79-11eb-8e90-603aad9ab96f.png)

**Comment by cboxdoerfer** [comment]
Thx for the bug report. I'm already aware of this issue. There's a new listview widget in the making (see `listview` branch if you're adventures) which fixes that issue.

**Comment by cboxdoerfer** [comment]
Fixed.
