### ISSUE TITLE
Add a debian repository / get in debian repositories

### ISSUE THREAD

**Issue by mlncn** [cboxdoerfer/fsearch#260]
I think this issue is just a placeholder for something that's on the unstated distribution roadmap anyhow, similar to #85 

Using the [build instructions](https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions ) for Debian right now, but would love to get FSearch from a source that manages updates like the Debian package manager (or Flatpak?)

Thanks for the great search tool!

**Comment by cboxdoerfer** [comment]
It's now available as a Flatpak: https://flathub.org/apps/details/io.github.cboxdoerfer.FSearch
  
As for Debian, I'll see if I we can get it into the official repositories next.

**Comment by cboxdoerfer** [comment]
Debian is now supported via the OpenBuildSevice: https://software.opensuse.org//download.html?project=home%3Acboxdoerfer&package=fsearch#manualDebian
