### ISSUE TITLE
Periodic database updates

### ISSUE THREAD

**Issue by slrslr** [cboxdoerfer/fsearch#261]
Until proper automatic DB updating is there (see: #26 and #116 )

can be quick/simple to enable periodic database updates?

Preferences/Database

here can be: Update DB every [enter number] hours if app is running.

Or adding an instruction to run the binary with a --dbupdate parameter using cron?

If making this seems like complicating things (while the proper automatic db update should be done soon), please close this.

I am having the app constantly running, seems to be the fastest way to access search, and so db updates i am doing manually when i see i am unable to find something i know is there.

**Comment by cboxdoerfer** [comment]
> Preferences/Database

> here can be: Update DB every [enter number] hours if app is running.

That's already there.

> Or adding an instruction to run the binary with a --dbupdate parameter using cron?

That's also already possible with `fsearch --update-database`

You're probably using an older build where those features aren't there yet. How did you install FSearch and which operating system do you use?

**Comment by slrslr** [comment]
if the periodic update and manual update by running the app with a switch via cron is already there, this can be closed.

I see i am using latest package for my OS: https://aur.archlinux.org/packages/fsearch-git/ (you link this from your README page)
but i see now it shows Last Updated: **2020**-03-08 😢

After [trying to build](https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions), i see that the periodic update feature is already there.

**Comment by cboxdoerfer** [comment]
The AUR package is a git package, which means it'll always use the newest code, so there's no need to bump the version manually. If you want to update it either just install it again to get the newest build or if your AUR helper supports it you can do things like `yay -Syu --devel` while doing a normal system update, which then also includes git packages.
