### ISSUE TITLE
[HELP] How to exclude certain folder in any subdirectory from being indexed

### ISSUE THREAD

**Issue by TasinIshmam** [cboxdoerfer/fsearch#264]
Hi, I want to remove certain folders from being indexed when searching, such as ```node_modules``` and ```venv```. As I have a lot of such projects, they take up a lot of time when indexing. 

Inside *Preferences->Database->Exclude* there's an option to either manually add folders or add patterns for files. Since I want to remove folders with a certain name across all directories, I used the exclude files option. This is what it looks like at the moment. 

![image](https://user-images.githubusercontent.com/29299547/121608426-bdd78500-ca73-11eb-9154-46b9301ee2a9.png)

However, node_modules folders are still getting indexed. Help is really appreciated!

**Comment by cboxdoerfer** [comment]
This doesn't work, because the pattern are a matched against the file/folder names, not their full path. So using path separators here doesn't work. Just add this instead to the exclude files entry:

> node_modules;venv

**Comment by TasinIshmam** [comment]
Fixed the issue. Thank you!
