### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by suprapoke** [cboxdoerfer/fsearch#265]
**Describe the bug**
after updating to the june 8th daily build, everytime I start up the program, it would get stuck updating/scanning the folders.

**Expected behavior**
I am not sure what version I was on before upgrading to the June 8th daily build, but everything worked fine before the upgrade

**Screenshots**
![Screenshot from 2021-06-11 01-20-56](https://user-images.githubusercontent.com/85733434/121655640-9cff3780-ca53-11eb-8821-6287eb592a95.png)
![Screenshot from 2021-06-11 01-26-50](https://user-images.githubusercontent.com/85733434/121656220-20b92400-ca54-11eb-9dda-0b0fecdf54b5.png)

**Desktop (please complete the following information):**
 - OS: [Linux Mint 20]
 - How you installed FSearch [PPA]
 - Version [FSearch 0.1beta4, june 8th daily build]
 - Output of `localectl status`   
System Locale: LANG=en_US.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105

**Additional context**

**Comment by cboxdoerfer** [comment]
What do you mean with it gets stuck? Is there no progress shown in the status bar?

**Comment by suprapoke** [comment]
hi, normally, the scanning will go through each folder to index the files and build the search database.

however, after this most recent update to the June 8th daily build, it will randomly "get stuck" at a folder and the lower bottom status just shows scanning.  I've let it sit for up to 10 hours and it will still be stuck.  when I click on the X to close the window, that's when the not responding dialog shows up and I tried "wait" for a couple of hours, but its still "stuck"

**Comment by suprapoke** [comment]
also, I tried to look up the apt-cache for fsearch-trunk to see if I can roll back to an older version, but it seems like the june 8th daily build was the only option

**Comment by cboxdoerfer** [comment]
Thx for the information and I'm sorry for the inconvenience. This sounds like there's definitely something going very wrong, however it's difficult to tell where it gets stuck exactly.

I just added a few more debug statements to the relevant code paths and I'm going to trigger new build for the PPA. Once it's ready I'll let you know. Then after installing the new build you can launch FSearch from the terminal with `env G_MESSAGES_DEBUG=all fsearch > fsearch_debug.log`which will write a lot of debug output to the `fsearch_debug.log` file, which you then can inspect. Hopefully this gets us closer to the cause of the issue.

Also, can you also post your config (`~/.config/fsearch/fsearch.conf`)?

**Comment by cboxdoerfer** [comment]
Also, can you post the output of `htop -F fsearch` after the scan has been going on for a couple of minutes?

**Comment by cboxdoerfer** [comment]
The new build with the debug output is now ready in the PPA. Be aware that the log file can become quite large if the application ends up in an endless loop, so don't run `env G_MESSAGES_DEBUG=all fsearch > fsearch_debug.log` for too long (on my system `fsearch_debug.log` ends up at 60MB after scanning 3 million files/folders). Maybe you just want to start with `env G_MESSAGES_DEBUG=all fsearch`, maybe you can already spot an issue right away in the terminal output.

**Comment by suprapoke** [comment]
==========================================
the beginning of fsearch_debug.log
==========================================
(fsearch:51632): GLib-GIO-DEBUG: 01:33:37.823: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(fsearch:51632): GLib-DEBUG: 01:33:37.874: unsetenv() is not thread-safe and should not be used after threads are created
(fsearch:51632): Gtk-DEBUG: 01:33:37.874: Connecting to session manager
(fsearch:51632): fsearch-config-DEBUG: 01:33:37.874: [config] loading...
(fsearch:51632): fsearch-config-DEBUG: 01:33:37.874: [config] loaded in 0.148000 ms
(fsearch:51632): fsearch-application-DEBUG: 01:33:38.027: [app] disabled action: update_database
(fsearch:51632): fsearch-application-DEBUG: 01:33:38.027: [app] enabled action: cancel_update_database
(fsearch:51632): fsearch-database-DEBUG: 01:33:38.028: [db_load] load 2860 folders, 111560 files
(fsearch:51632): fsearch-database-DEBUG: 01:33:38.028: [db_load] folder size: 84909, file size: 3377481
(fsearch:51632): fsearch-application-DEBUG: 01:33:38.059: [app] database update finished in 32.30 ms
(fsearch:51632): fsearch-application-DEBUG: 01:33:38.060: [app] enabled action: update_database
(fsearch:51632): fsearch-application-DEBUG: 01:33:38.060: [app] disabled action: cancel_update_database
(fsearch:51632): fsearch-database-DEBUG: 01:33:38.065: [db_ref] increased to: 2
(fsearch:51632): fsearch-database-DEBUG: 01:33:38.065: [db_ref] increased to: 3
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.065: [darray_ref] increased to: 2
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.065: [darray_ref] increased to: 2
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_ref] increased to: 3
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_ref] increased to: 3
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_unref] dropped to: 2
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_unref] dropped to: 2
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_ref] increased to: 3
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_ref] increased to: 3
(fsearch:51632): fsearch-database-DEBUG: 01:33:38.066: [db_unref] dropped to: 2
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_ref] increased to: 4
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_ref] increased to: 4
(fsearch:51632): fsearch-search-DEBUG: 01:33:38.066: [query 0.0] finished in 0.08 ms
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_unref] dropped to: 3
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_ref] increased to: 4
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_unref] dropped to: 3
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_ref] increased to: 4
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_unref] dropped to: 3
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:33:38.066: [darray_unref] dropped to: 3
(fsearch:51632): fsearch-application-DEBUG: 01:33:42.066: [app] disabled action: update_database
(fsearch:51632): fsearch-application-DEBUG: 01:33:42.067: [app] enabled action: cancel_update_database
(fsearch:51632): fsearch-database-DEBUG: 01:33:42.067: [db_scan] scan path: /media/e/14-USB6TB
(fsearch:51632): fsearch-database-DEBUG: 01:33:42.068: [db_scan] scanning directory: /media/e/14-USB6TB/
(fsearch:51632): fsearch-database-DEBUG: 01:33:42.068: [db_scan] scanning directory: /media/e/14-USB6TB/$RECYCLE.BIN/


==========================================
the last few entries of fsearch_debug.log
==========================================
(fsearch:51632): fsearch-database-DEBUG: 01:34:25.042: [db_scan] scanning directory: /media/e/USB6TB2/youtube/
(fsearch:51632): fsearch-database-DEBUG: 01:34:25.116: [db_scan] scanning directory: /media/e/USB6TB2/youtube/New folder/
(fsearch:51632): fsearch-database-DEBUG: 01:34:25.151: [db_scan] scanned: 664152 files, 19178 files -> 683330 total
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.151: [sort] sorting with 16 threads
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.184: [sort] merge with 8 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.193: [sort] merge with 4 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.201: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.202: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.202: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.202: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.202: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.202: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.202: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.202: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.202: [sort] merge with 2 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.220: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.220: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.220: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.220: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.221: [sort] merge with 1 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.246: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.246: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.478: [sort] sorting with 16 threads
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.492: [sort] merge with 8 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.499: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.500: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.500: [sort] merge with 4 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.511: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.512: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.512: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.512: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.512: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.512: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.512: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.512: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.512: [sort] merge with 2 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.529: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.530: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.530: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.530: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.530: [sort] merge with 1 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.561: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.562: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.563: [sort] sorting with 16 threads
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.573: [sort] merge with 8 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.578: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.578: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.578: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.579: [sort] merge with 4 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.585: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.585: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.585: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.585: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.585: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.585: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.585: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.585: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.586: [sort] merge with 2 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.595: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.595: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.595: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.596: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.596: [sort] merge with 1 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.612: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.613: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.614: [sort] sorting with 16 threads
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.668: [sort] merge with 8 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.681: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.681: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.681: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.681: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.681: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.681: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.681: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.681: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.681: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.681: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.682: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.682: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.682: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.682: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.682: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.682: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.682: [sort] merge with 4 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.697: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.698: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.698: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.698: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.698: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.698: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.698: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.698: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.698: [sort] merge with 2 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.722: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.723: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.723: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.723: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.724: [sort] merge with 1 thread(s)
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.768: [darray_free] freed
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.769: [darray_free] freed
(fsearch:51632): fsearch-database-DEBUG: 01:34:25.769: [db_sort] sorted files: 0.618202 s
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:34:25.788: [darray_ref] increased to: 2
(fsearch:51632): fsearch-database-DEBUG: 01:34:25.788: [db_sort] sorted folders: 0.019115 s
(fsearch:51632): fsearch-task-DEBUG: 01:35:00.211: [queue_thread] quit
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:35:00.211: [darray_unref] dropped to: 2
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:35:00.211: [darray_unref] dropped to: 2
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:35:00.211: [darray_unref] dropped to: 1
(fsearch:51632): fsearch-dynamic-array-DEBUG: 01:35:00.211: [darray_unref] dropped to: 1
(fsearch:51632): fsearch-database-DEBUG: 01:35:00.211: [db_unref] dropped to: 1
(fsearch:51632): fsearch-application-DEBUG: 01:35:00.213: [app] waiting for database thread to exit...

**Comment by suprapoke** [comment]
~$ htop -F fsearch
bash: htop: command not found

**Comment by suprapoke** [comment]
>Also, can you also post your config (~/.config/fsearch/fsearch.conf)?

[Interface]
single_click_open=false
highlight_search_terms=true
restore_column_configuration=false
restore_sort_order=true
double_click_path=false
enable_list_tooltips=true
enable_dark_theme=false
show_menubar=true
show_statusbar=true
show_filter=true
show_search_button=true
show_base_2_units=false
action_after_file_open=0
action_after_file_open_keyboard=false
action_after_file_open_mouse=false
show_indexing_status=true
restore_window_size=false
window_width=800
window_height=600
show_listview_icons=true
show_path_column=true
show_type_column=false
show_extension_column=true
show_size_column=true
show_modified_column=true
sort_ascending=false
sort_by=Size
name_column_width=1369
path_column_width=250
extension_column_width=100
type_column_width=100
size_column_width=75
modified_column_width=125
name_column_pos=0
path_column_pos=1
type_column_pos=2
size_column_pos=3
modified_column_pos=4

[Dialogs]
show_dialog_failed_opening=true

[Search]
search_as_you_type=true
auto_search_in_path=true
auto_match_case=false
search_in_path=false
enable_regex=true
match_case=false
hide_results_on_empty_search=true

[Database]
update_database_on_launch=false
update_database_every=false
update_database_every_hours=0
update_database_every_minutes=15
exclude_hidden_files_and_folders=false
follow_symbolic_links=false
location_1=/media/e/14TB1
location_enabled_1=true
location_update_1=true
location_2=/media/e/14TB2
location_enabled_2=true
location_update_2=true
location_3=/media/e/14TB3
location_enabled_3=true
location_update_3=true
location_4=/media/e/14TB4
location_enabled_4=true
location_update_4=true
location_5=/media/e/14TB5
location_enabled_5=true
location_update_5=true
location_6=/media/e/14TB6
location_enabled_6=true
location_update_6=true
location_7=/media/e/6TBnew1
location_enabled_7=true
location_update_7=true
location_8=/media/e/14-USB6TB
location_enabled_8=true
location_update_8=true
location_9=/media/e/USB6TB2
location_enabled_9=true
location_update_9=true
location_10=/media/e/3TB1
location_enabled_10=true
location_update_10=true
location_11=/media/e/3TB2
location_enabled_11=true
location_update_11=true
location_12=/media/e/17-USB8TB
location_enabled_12=true
location_update_12=true
exclude_files=

**Comment by cboxdoerfer** [comment]
Thank you very much for the detailed information, this helped a lot to narrow the issue down.

According to the log the database scan and sorting was successful, but interestingly writing the database to disk never finished, so it likely gets stuck there. This would also explain why canceling the database update doesn't work, because this part of the code can't be cancelled (but I'm going to change that).

Unfortunately I didn't expect that it gets stuck in that part of the code, which is why there's no useful debug output shown. So I fear we might need to do the same procedure again -- I'll add a few more debug statements, trigger a rebuild and notify you when that's done.

Again, I'm sorry for the inconvenience.

**Comment by cboxdoerfer** [comment]
Also, can you provide the output of: `ls  -al ~/.local/share/fsearch`

**Comment by cboxdoerfer** [comment]
@suprapoke, the new build is now ready. After updating fsearch you can now run `env G_MESSAGES_DEBUG=all fsearch > fsearch_debug.log` again, perform a database update and try to quit the application after a while. Note, this time there won't be so much debug output as before, so the file won't get very big.

**Comment by suprapoke** [comment]
~$ ls -al ~/.local/share/fsearch
total 5836
drwx------  3 e e    4096 Jun 10 00:42 .
drwxr-xr-x 16 e e    4096 Jun 12 01:54 ..
drwx------ 14 e e    4096 Aug 24  2020 database
-rw-rw-r--  1 e e 5293176 Jun 10 00:39 fsearch.db
-rw-rw-r--  1 e e  663552 Jun 12 08:32 fsearch.db.tmp

**Comment by suprapoke** [comment]
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.668: [db_sort] sorted files: 0.602465 s
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_sort] sorted folders: 0.013271 s
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_save] saving database to file...
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_save] trying to open temporary database file: /home/e/.local/share/fsearch/fsearch.db.tmp
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_save] updating folder indices...
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_save] saving database header...
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_save] saving database index flags...
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_save] saving number of folders: 19178
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_save] saving number of folders: 664148
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_save] saving folder block size...
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_save] saving file block size...
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_save] saving indice...s
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_save] saving excludes...
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_save] saving exclude pattern...
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.681: [db_save] saving folders...
(fsearch:61579): fsearch-database-DEBUG: 08:35:19.687: [db_save] saving files...
(fsearch:61579): fsearch-task-DEBUG: 08:35:58.257: [queue_thread] quit
(fsearch:61579): fsearch-database-DEBUG: 08:35:58.257: [db_unref] dropped to: 1
(fsearch:61579): fsearch-application-DEBUG: 08:35:58.259: [app] waiting for database thread to exit...

**Comment by suprapoke** [comment]
also, I did an apt remove and then a new install, but it seems like the config file and the database are from previous installation.

is there anyway I can wipe everything clean and start fresh?

**Comment by cboxdoerfer** [comment]
Thank you very much. Again this helped a lot and I might have found the issue. I suspect it's caused by an integer overflow when comparing two incredibly long file names. I just pushed a fix for that and I'll let you know when the new build is ready for testing.

Yes, you can start fresh, but it would be really great if you could wait with that until the issue is fixed, so I'm sure that I'll caught the bug.

FSearch stores it's files in only two folders, so by removing:

* `~/.config/fsearch`
* `~/.local/share/fsearch`

you will end up with a fresh FSearch install.

**Comment by cboxdoerfer** [comment]
(Hopefully) fixed version should now be ready.

**Comment by suprapoke** [comment]
I just updated to the latest version, and I am happy to report that it is working fine again!

thank you so much for fixing this bug so quickly!!!

**Comment by cboxdoerfer** [comment]
Great, no problem. Thanks again for reporting and taking the time to provide all the helpful information.
