### ISSUE TITLE
[BUG]: "Search in path when query contains path separators" no longer working

### ISSUE THREAD

**Issue by nashving** [cboxdoerfer/fsearch#267]
**Describe the bug**
"Search in path when query contains path separators" feature does not seem to work any more.

**To Reproduce**
1. Ensure "Search in path when query contains path separators" option is selected:
![Preferences_Search](https://user-images.githubusercontent.com/65134226/122529651-ff40d500-d01d-11eb-92e0-bbe751fea798.png)
2. Perform a search including the '/' character (to invoke Search In Path)
3. Expected files are not found:
![SearchInPath_Off](https://user-images.githubusercontent.com/65134226/122529656-010a9880-d01e-11eb-8c26-693f77a41bcb.png)

**Expected behavior**
Expected files should be found, using Search In Path
![SearchInPath_On](https://user-images.githubusercontent.com/65134226/122529657-01a32f00-d01e-11eb-93c8-e22761acafbc.png)

**Screenshots**
See Attached Screenshots

**Desktop (please complete the following information):**
 - OS = Linux Mint 19.3 Tricia (based on Ubuntu 18.04)
 - How you installed FSearch = PPA
 - Version [output of `fsearch --version`] = FSearch 0.1beta4 (ppa = 20210617+r1332.6cdc27d~ubuntu18.04.1, although I first noticed the bug in 20210610 build)
 - Output of `localectl status` = 
System Locale: LANG=en_ZA.UTF-8
                  LANGUAGE=en_ZA:en
                  LC_COLLATE=C
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105

**Additional context**

**Comment by cboxdoerfer** [comment]
What a coincidence, I just fixed that bug a few minutes before you opened the issue (https://github.com/cboxdoerfer/fsearch/commit/56becf42743c53399e1ab2eecb475d4a41102329). :) But thanks for the report, I'll leave the issue open until you can confirm that the fix indeed works as expected. The new build with the fix for the PPA should be available within the next 24 hours.

**Comment by nashving** [comment]
Wow, that is a great Mean Time To Repair! :-)

I will confirm the fix after checking the new build.

Btw, thank you for this awesome software.  It is definitely the best of it's kind!

**Comment by nashving** [comment]
Fixed in 20210618+r1336.c6c0fcc~ubuntu18.04.1

Great work!

**Comment by cboxdoerfer** [comment]
Awesome, thanks for taking the time to check if it's working :+1:
