### ISSUE TITLE
Package for Fedora/RHEL/CentOS

### ISSUE THREAD

**Issue by inori39** [cboxdoerfer/fsearch#268]
Hi! Thank you for this amazing utility! Simply awesome.

We currently have Arch / Ubuntu and SUSE packages but lacks packages for red hat distributions.

To address this issue, I have created a Fedora copr for FSearch, provides pre-built packages for fedora / RHEL / CentOS etc. :

https://copr.fedorainfracloud.org/coprs/inori39/fsearch/

Please suggest your advice, if you think it looks okay, consider adding this repository to README.md, thank you!

**Comment by cboxdoerfer** [comment]
Thank you! I'll have a look at it.

**Comment by cboxdoerfer** [comment]
Looks and works fine :) I'll add it to the README

Thanks again!

**Comment by cboxdoerfer** [comment]
Btw. would you mind if at one point in the future I use your copr configuration as a template for my own copr builds for FSearch? This way I could label those builds as "official". Of course I'd credit you for the initial work.

**Comment by inori39** [comment]
> Thank you! I'll have a look at it.

Oh! I'm the one should say thank you - for this really amazing tool! Without such a searching tool I can't live with my computer! KDE's baloo and KFind sucks.

I used fsearch several years ago but it was just not that good. It is almost perfect now!

> Btw. would you mind if at one point in the future I use your copr configuration as a template for my own copr builds for FSearch? This way I could label those builds as "official". Of course I'd credit you for the initial work.

Of course!! Glad you have interest in packaging RPMs! 

It seems you were developing quite actively these days, very appreciated! I used `master` as version number because of this reason, I don't think it's a good idea. Looking forward to see next tagged release! Building only tagged release seems to be a better idea.

Once you have done packaging please mention me here so I can deprecate the copr repository, or you can just do it now :laughing: ! before people starts to use the copr I have created.

**Comment by cboxdoerfer** [comment]
@inori39 FYI, I've just setup my own copr project for FSearch: https://copr.fedorainfracloud.org/coprs/cboxdoerfer/fsearch_nightly/

Thank you for bringing this to my attention and maintaining your own repository so far!
