### ISSUE TITLE
openSUSE RPM: rpmlint issues

### ISSUE THREAD

**Issue by jaltek** [cboxdoerfer/fsearch#27]
Hi,

I would like to contribute by providing a RPM for openSUSE at the [openSUSE Build Service](https://build.opensuse.org/). rpmlint throws two warnings:

```
fsearch.x86_64: W: no-manual-page-for-binary fsearch
Each executable in standard binary directories should have a man page.

fsearch.x86_64: W: invalid-desktopfile /usr/share/applications/fsearch.desktop value "0.1" for key "Version" in group "Desktop Entry" is not a known version
.desktop file is not valid, check with desktop-file-validate

```

As FSearch is currently 0.1 and in beta stadium, the `Version` warning can be ignored (IMHO). Otherwise you should omit the `Version` entry in the `.desktop` file as long as the version is lower than 1.0.

Cheers,

Jan

**Comment by cboxdoerfer** [comment]
Thx, I'll add a man page. Regarding the version entry in the desktop file, I just had a look at the specification and the version is supposed to be the version of the Desktop Entry Specification, not of the application. So I'll fix that right away.

**Comment by cboxdoerfer** [comment]
Fixed version number bug.

**Comment by jaltek** [comment]
Ok, I added the latest release (not commit) of the package to my home repo at the build service:

https://build.opensuse.org/package/show/home:jaltekger/fsearch

The build for openSUSE Leap 42.1 actually [fails.](https://build.opensuse.org/package/live_build_log/home:jaltekger/fsearch/openSUSE_Leap_42.1/x86_64)

**Comment by cboxdoerfer** [comment]
Ok, the build fails because gtk_overlay_set_overlay_pass_through was introduced with GTK+ 3.18 (which I didn't notice) and Leap 42.1 is still using GTK+ 3.16.

I think the gtk_overlay_set_overlay_pass_through calls aren't needed, so I'll try to remove them. Then the build should succeed.

**Comment by cboxdoerfer** [comment]
Fixed.

**Comment by jaltek** [comment]
Build succeeded locally. I will update the repo upon your next release.

**Comment by jaltek** [comment]
Just a small update on this: Build succeeds for all current openSUSE versions.
Only last issue left here seems to be the missing manual entry.

```
fsearch.x86_64: W: no-manual-page-for-binary fsearch
Each executable in standard binary directories should have a man page.
```
