### ISSUE TITLE
[BUG] Doubled results

### ISSUE THREAD

**Issue by jaclas** [cboxdoerfer/fsearch#271]
I was looking for some directory, but in result list I found doubled results:

![obraz](https://user-images.githubusercontent.com/17312717/125099756-a7efcb00-e0d8-11eb-96e3-4eeca75aafc0.png)

Before search I updated database

It's correct behavior?

**Comment by cboxdoerfer** [comment]
Which folders did you include in the database (`Preferences -> Database -> Include`)

**Comment by jaclas** [comment]
Ok, I'm going to go clean the bathroom ;-)
