### ISSUE TITLE
Issue Request to remember sorting by 'Date Modified' in descending order (most recent files first)

### ISSUE THREAD

**Issue by kajodowe** [cboxdoerfer/fsearch#272]

**Comment by kajodowe** [comment]
Hi Christian -- Can you provide a way to remember the sort by 'Date Modified' in descending order (most recent files first). When I close fsearch and reopen it sorts by 'Name' in A-Z order. I do see that if I set fsearch to 'minimize' after selecting a file that preservers the 'Date Modified' sort so I'll just use that for now. 

Fsearch is great -- do you take donations? You really ought to charge for it!

**Comment by cboxdoerfer** [comment]
> Hi Christian -- Can you provide a way to remember the sort by 'Date Modified' in descending order (most recent files first). When I close fsearch and reopen it sorts by 'Name' in A-Z order. I do see that if I set fsearch to 'minimize' after selecting a file that preservers the 'Date Modified' sort so I'll just use that for now.

Thank you for the report. Yes, I'll fix that.

> Fsearch is great -- do you take donations? You really ought to charge for it! It is so helpful to me!

Thanks :), however at the moment I don't take any donations. But I'll make that possible as soon as FSearch leaves the beta state.

**Comment by kajodowe** [comment]
Hi Christian -- thanks for working on this sorting option. And thanks for developing FSearch. I was a Voidtools / Everything addict when I used Windows extensively. So I naturally am a big fan of FSearch. 

I would be willing to volunteer if you need any assistance. I am only a primitive programmer :) but if there's any other way I could help I would be glad to do it.

-Allen

**Comment by cboxdoerfer** [comment]
The sort order should now be restored properly on startup. Please let me know if it works for you once you tried the updated version.

> I would be willing to volunteer if you need any assistance. I am only a primitive programmer :) but if there's any other way I could help I would be glad to do it.

Thanks, help is always appreciated. Unfortunately I already fixed this issue before I read you're reply, because this one would have been a good start for a first contributor. But anyway, if there's anything else you want to work on just let me know and I can offer some guidance, even when you're not confident with programming in C yet.

**Comment by kajodowe** [comment]
Hi Christian -- the sort order works great now. Thanks for taking care of
this. I'd be willing to try to do something -- what about a feature to
minimize FSearch to the notification area when closed, and also to have a
toggle shortcut key to maximize and minimize FSearch. If I'm not mistaken
Voidtools/Everything has this option. Let me know what I can do. I can
certainly give it a try. Probably won't succeed but I will learn something
for sure! 😄

-Allen

**Comment by cboxdoerfer** [comment]
> toggle shortcut key to maximize and minimize FSearch.

This is already provided by your desktop environment, on GNOME and Cinnamon it's `<Super><Up>` and `<Super><Down>` I think, and it works with all windows.

> a feature to minimize FSearch to the notification area

Yes, this is a planned feature. Here are a few tips to implement it:

* libappindicator is probably the library we want to use. It'll work in most desktops and X11/Wayland alike, so the first step is to add this library as an optional dependency to the build system (FSearch uses meson and autotools).
* then the appindicator and it's menu can be created in the startup handler of `FsearchApplication` in `fsearch.c`
* then an option can be added to the preferences dialog to enable/disable the appindicator

For a start the actions we want in the appindicator menu are:

* Show FSearch
* Quit

As a reference, here's how Transmission implements the core part of its appindicator: https://github.com/transmission/transmission/blob/master/gtk/tr-icon.c

**Comment by kajodowe** [comment]
Thanks Christian. I will take a look at this. It may be too advanced for me
but I'll enjoy trying!

-Allen

**Comment by cboxdoerfer** [comment]
Sure, and like I said, if you have any questions don't hesitate to reach out to me.
