### ISSUE TITLE
Open fsearch in a path (right click)

### ISSUE THREAD

**Issue by prestidigitonium** [cboxdoerfer/fsearch#274]
**Is your feature request related to a problem? Please describe.**
I'd like to propose a feature request

**Describe the solution you'd like**
Add a new cli command to fsearch `fsearch <path>` to start a new search from the given path (if the path is in the list of allowed paths, or in a sub-path of allowed paths). In this way fsearch could be integrated in thunar's scripts in a comfortable way (`fsearch %d`)

**Describe alternatives you've considered**
Add a new feature that allows fsearch to be opened directly in the default file manger (starting a new search in the current path, as described above), using right click in a folder

**Additional context**
/null/

**Comment by MaurizioRicci** [comment]
For integrations it also would be useful to be able to specify a search term.
You could use it in whisker menu, for example this command
`fsearch <searchString>`

Could open an fsearch window searching for `<searchString>`

So in whisker menu you could write your own search action:
`search fsearch %s`

And finally when you write:
`search <fileName>`

The fsearch window will open searching for `<fileName>`

**Comment by cboxdoerfer** [comment]
> For integrations it also would be useful to be able to specify a search term.
> You could use it in whisker menu, for example this command
> `fsearch <searchString>`

This is now possible. It works like that:

`fsearch --search=SEARCH_STRING` or `fsearch -s SEARCH_STRING`

**Comment by MaurizioRicci** [comment]
> > For integrations it also would be useful to be able to specify a search term.
> > You could use it in whisker menu, for example this command
> > `fsearch <searchString>`
> 
> This is now possible. It works like that:
> 
> `fsearch --search=SEARCH_STRING` or `fsearch -s SEARCH_STRING`

Great thank very helpful!!

**Comment by SalimF** [comment]
> fsearch --search=SEARCH_STRING

Hi, I want to add it to `Thunar` action mention for folder search 
When It's open shows me the folder path in search box, not what I want it,
If there is way Fsearch start the search from specified directory, that's will help a lot.
![image](https://user-images.githubusercontent.com/16048674/147247740-9f5d096a-d9d5-4706-98be-68ee760cc88f.png)

![image](https://user-images.githubusercontent.com/16048674/147247341-3c3ee530-87ea-47ec-a9aa-5f7271abb651.png)

![image](https://user-images.githubusercontent.com/16048674/147247521-233a6398-5c6c-4dd4-a7ad-6f0ee3fabf64.png)

**Comment by cboxdoerfer** [comment]
@SalimF sorry for the late reply. No, there's no other way to limit the search to a particular folder. All searches are controlled by the text in the search entry.

**Comment by ghyujkilop** [comment]
Any chance of bringing this in as a feature? It's be so helpful! You can search via folder by copying the path into the search, is there no way of implementing some extra function that just auto copies the path into the fsearch? I feel like that'd have to be able to exist to some degree!

**Comment by cboxdoerfer** [comment]
> Any chance of bringing this in as a feature? It's be so helpful! You can search via folder by copying the path into the search, is there no way of implementing some extra function that just auto copies the path into the fsearch? I feel like that'd have to be able to exist to some degree!

Do you mean by adding a new folder to the database config via a command line option?
