### ISSUE TITLE
Text alignment is off in search preferences

### ISSUE THREAD

**Issue by aha999** [cboxdoerfer/fsearch#276]
**Describe the bug**
Text alignment is off in search preferences.

**To Reproduce**
1. Go to Preferences
2. Click on Search menu
3. See some text misaligned.

**Expected behavior**
The text should extend to the entire line width and align the text to the left side if the window is too small to fit in so it auto-fits.

**Screenshots**
![image](https://user-images.githubusercontent.com/50620416/130258879-68f92a49-6076-47aa-a444-51f059371073.png)

**Desktop (please complete the following information):**
 - OS: Pop!OS 21.04
 - How you installed FSearch - PPA via terminal (for Ubuntu tutorial)
 - Version FSearch 0.1beta4
 - Output of `localectl status` 
   

> System Locale: LANG=en_US.UTF-8
>                   LC_NUMERIC=de_AT.UTF-8
>                   LC_TIME=de_AT.UTF-8
>                   LC_MONETARY=de_AT.UTF-8
>                   LC_PAPER=de_AT.UTF-8
>                   LC_NAME=de_AT.UTF-8
>                   LC_ADDRESS=de_AT.UTF-8
>                   LC_TELEPHONE=de_AT.UTF-8
>                   LC_MEASUREMENT=de_AT.UTF-8
>                   LC_IDENTIFICATION=de_AT.UTF-8
>        VC Keymap: slovene
>       X11 Layout: si
>      X11 Variant: us

**Comment by cboxdoerfer** [comment]
Thank you for reporting! Fixed.

**Comment by aha999** [comment]
woah that was fast. you are awesome!
