### ISSUE TITLE
Add donation information to Readme.md

### ISSUE THREAD

**Issue by aha999** [cboxdoerfer/fsearch#277]
**Is your feature request related to a problem? Please describe.**
Currently there's no donating information, if users want to show appreciation like that.

**Describe the solution you'd like**
Add a Donations section to the readme and some buttons below as to where donate.

**Describe alternatives you've considered**
If you comment the information of the donation methods you use and addresses, i will do it for you and make a pull request, did this a couple of times.

**Comment by aha999** [comment]
I saw a lot of open-source projects use LiberaPay or other in the list: 
- [LiberaPay](https://liberapay.com/) -- [example](https://liberapay.com/k9mail/donate)
- [PayPal](https://www.paypal.com/)
- [Github Sponsors](https://github.com/sponsors)
- [Ko-fi](https://ko-fi.com/)
- [OpenCollective](https://opencollective.com/) -- [example](https://opencollective.com/darkreader#sponsor)
- [Flattr](https://flattr.com/)
- [BountySource](https://www.bountysource.com)

Displaying a sponsor button in your repository: [link](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository) 
Some [donate buttons](https://github.com/aha999/DonateButtons)

_Suggestion copied from my [previous issue](https://github.com/UriahShaulMandel/BaldPhone/issues/170#issuecomment-569430916) in another project._

**Comment by cboxdoerfer** [comment]
Thank you, I've already set up some of the donation options you listed (PayPal and GitHub sponsors), but they're not public yet. In Germany it's a little tricky to ask for donations, because the tax authorities treat them like regular revenue. So I needed to register a small business or freelance work with authorities for proper taxation first. At the moment I'm awaiting their response.

**Comment by lucidBrot** [comment]
Any news on that front yet? I find it odd that there is a sponsor button but it just redirects to your github profile (unless something is just broken on my two machines)

**Comment by cboxdoerfer** [comment]
It took a while but donation options are now available. Currently there are only two optoins: Github Sponsors and PayPal. But Github Sponsors is clearly the preferred option, since there are no fees involved.
