### ISSUE TITLE
Don't cross filesystem boundaries

### ISSUE THREAD

**Issue by rieje** [cboxdoerfer/fsearch#278]
Allow the option to not cross filesystem boundaries, i.e. "stay on the file system" option from `cp` and `rsync`. I have some bind mounts and duplicate entries will show for the same file as a result. I do not want to explicitly exclude certain directories as a workaround..

**Comment by cboxdoerfer** [comment]
That's a good idea, I'll add that.

**Comment by cboxdoerfer** [comment]
Added.
