### ISSUE TITLE
Add option to mix files and folders in result list

### ISSUE THREAD

**Issue by DUOLabs333** [cboxdoerfer/fsearch#281]
**Describe the bug**
If files A, B, and C are in folder D, the files will be sorted properly, while the folder is at the bottom, with all the folders.

**To Reproduce**
1. Just have any folder with files in it, and the error shows up.

**Expected behavior**
The folder D should show on top of the files A, B, and C.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Arch ARM
 - How you installed FSearch: AUR
 - Version UNKNOWN
 - System Locale: LANG=C
       VC Keymap: n/a
      X11 Layout: n/a

**Additional context**

**Comment by cboxdoerfer** [comment]
Do you mean that when you have the sort set to descending order, that folders should stay above the files, like they are when it's set to the default sort order (ascending)?

**Comment by DUOLabs333** [comment]
Not all folders -- basically files and folders should be treated the same in sorting, and placed accordingly (all folders should not be grouped together in the top or bottom).

**Comment by cboxdoerfer** [comment]
You mean mixing files and folders, like this?

    1. file_a   |   4MB
    2. folder_a |   16MB
    3. file_b   |   32 MB
    4. file_c   |   64MB
    5. folder_b |   128 MB

**Comment by DUOLabs333** [comment]
Yes.

**Comment by cboxdoerfer** [comment]
This is tricky to implement and it would definitely be much slower or require more memory, because currently files and folders are stored separately in memory. I'll add it to my todo list, but I can't promise anything and it'll probably take a while until I get to that feature request.
