### ISSUE TITLE
Visibly highlight file when hovered over when single click to open is enabled

### ISSUE THREAD

**Issue by rieje** [cboxdoerfer/fsearch#282]
Visibly highlight file when hovered over when single click to open is enabled to provide clear action when clicked. Currently, there's no visible indicator of which file you're opening if your mouse cursor is between two rows of files. On other applications I've used which has "a single click to open" (e.g. Pcmanfm), you can set the value of the delay before updating the item you're hovering over, e.g. .2 seconds delay.

**Comment by cboxdoerfer** [comment]
That's a good point. I'll add that.

**Comment by cboxdoerfer** [comment]
The row which is currently being hovered is now highlighted.
