### ISSUE TITLE
[BUG] No indication of deleted file, single click does not show indication of failure to open file

### ISSUE THREAD

**Issue by rieje** [cboxdoerfer/fsearch#283]
There is no longer indication of deleted file. Previously, the icon before the file name would change to reflect the file is no longer on the system, which is of course very useful.

Also, single click does not show indication of failure to open file (it doesn't do anything), unless I right-click to open file. When I do this, it shows the prompt window indicating failure to open file, but selecting Yes/No to the question "Do you want to keep the window open?" does nothing, not even exiting the prompt window. I use the Wayland tiling window manager Sway and just close this window manually.

Both issues exist for both the default window decorations and the client-side decorations option.

 - OS: Arch Linux
 - Installed via the AUR (fsearch-git)
 - Version 0.1beta4.1192-f46c
 - `localectl status`:    

     System Locale: LANG=en_US.UTF-8
     VC Keymap: n/a
     X11 Layout: n/a
-   Wayland (Sway)

**Comment by cboxdoerfer** [comment]
> There is no longer indication of deleted file. Previously, the icon before the file name would change to reflect the file is no longer on the system, which is of course very useful.

Yes, this is a known issue. I'm working on a fix.

> Also, single click does not show indication of failure to open file (it doesn't do anything), unless I right-click to open file. When I do this, it shows the prompt window indicating failure to open file, but selecting Yes/No to the question "Do you want to keep the window open?" does nothing, not even exiting the prompt window. I use the Wayland tiling window manager Sway and just close this window manually.

I can confirm that, that's definitely a bug. I'll fix that.

Thanks for reporting those issues!

**Comment by cboxdoerfer** [comment]
I've just improved the single click handling:

* the row under the mouse cursor gets highlighted
* the mouse cursor changes to a pointing hand symbol when you're hovering a row to indicate that a single click will activate the row

**Comment by rieje** [comment]
Works great!

**Comment by cboxdoerfer** [comment]
Closing. The single click part has been resolved and the indication of deleted files is covered by #64
