### ISSUE TITLE
[BUG] Can't stretch so that i can see a full path

### ISSUE THREAD

**Issue by tonypachino** [cboxdoerfer/fsearch#284]
**Describe the bug**
Now in the newest version i can't stretch a Name, Path or anything else so that i can see a more informations that i was searching for, i can only see a brief preview.

**To Reproduce**

**Expected behavior**
In previous version you make that feature but right now it dissapeared in new version.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - How you installed FSearch [e.g. built manually, PPA, AUR]
 - Version FSearch 0.1beta4.1200-05e0
 - Output of 
 System Locale: LANG=en_US.UTF-8
       VC Keymap: sr-latin
      X11 Layout: rs
     X11 Variant: latin

**Additional context**

**Comment by cboxdoerfer** [comment]
Should be fixed now in master branch.
