### ISSUE TITLE
Excluding folders based on name

### ISSUE THREAD

**Issue by daedalus-0** [cboxdoerfer/fsearch#287]
Hi, I think it'd be great if in addition to excluding individual files and hidden folders excluding folders was also possible. I haven't for example figured out how to exclude a "node_modules" folder which really bogs the indexing speed down.

**Comment by cboxdoerfer** [comment]
If it is a particular folder you want to exclude, you can add it to the list of excluded folders. If you want to exclude every folder with that name you can add 'node_modules' to the exclude files text entry (it applies to files and folders).

**Comment by daedalus-0** [comment]
thanks for the quick response. That does appear to remove the folder itself from the search results, but it does not seem to exclude the files within it, or at least I could not find a pattern to make it work.

**Comment by cboxdoerfer** [comment]
This is weird. Can you post the content of `~/.config/fsearch/fsearch.conf`?

**Comment by daedalus-0** [comment]
problem has been resolved, I had a space in the string, my bad.
