### ISSUE TITLE
[BUG] package doesn't include a binary (Ubuntu)

### ISSUE THREAD

**Issue by saalkom** [cboxdoerfer/fsearch#289]
**Describe the bug**
`fsearch-trunk` is now a transitional package in the Ubuntu PPA, but the new canonical package `fsearch` which supersedes it doesn't include a binary. There is no `fsearch` binary in `/usr/bin` anymore, or anywhere else in my `$PATH`.

**To Reproduce**
1. Upgrade to the latest `fsearch-trunk` from the PPA, or just install `fsearch` directly
2. Execute `fsearch`
3. Witness output: `Command 'fsearch' not found`

**Expected behavior**
FSearch executes.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Installed from PPA
 - Can't do `fsearch --version` obviously
 - `fsearch` package version `20210925+r1473.5692fe8~ubuntu20.04.1`

**Additional context**
Output of `dpkg -L fsearch`:
```
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/fsearch
/usr/share/doc/fsearch/README.Debian
/usr/share/doc/fsearch/changelog.gz
/usr/share/doc/fsearch/copyright
/usr/share/doc-base
/usr/share/doc-base/fsearch
```

**Comment by cboxdoerfer** [comment]
Thx, I'm working on a fix.

**Comment by cboxdoerfer** [comment]
Should be fixed. Please let me know if everything works now.

**Comment by saalkom** [comment]
The binary is there and FSearch seems to work now. Some documentation files seem broken, however.

```
...
Setting up fsearch (20210925+r1475.c1e3272~ubuntu20.04.1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for doc-base (0.10.9) ...
Processing 1 changed doc-base file...
Error in `/usr/share/doc-base/fsearch', line 20: all `Format' sections are invalid.
Note: `install-docs --verbose --check file_name' may give more details about the above error.
...
```
Output of `install-docs --verbose --check /usr/share/doc-base/fsearch`:
```
Warning in `/usr/share/doc-base/fsearch': unknown section: `unknown'.
Warning in `/usr/share/doc-base/fsearch', line 11: file mask `/usr/share/doc/fsearch/fsearch.sgml.gz' does not match any files.
Warning in `/usr/share/doc-base/fsearch', line 14: file mask `/usr/share/doc/fsearch/fsearch.ps.gz' does not match any files.
Warning in `/usr/share/doc-base/fsearch', line 17: file mask `/usr/share/doc/fsearch/fsearch.text.gz' does not match any files.
Warning in `/usr/share/doc-base/fsearch', line 20: file `/usr/share/doc/fsearch/html/index.html' does not exist.
Error in `/usr/share/doc-base/fsearch', line 20: all `Format' sections are invalid.
/usr/share/doc-base/fsearch: Fatal error found, the file won't be registered.
```
