### ISSUE TITLE
"remember column configuration" does not work column width

### ISSUE THREAD

**Issue by Muhammad-2021** [cboxdoerfer/fsearch#290]
"remember column configuration" does not work for column width

**To Reproduce**
1. Edit > Preference > interface tab > check "remember column configuration"
2. open the application and increase the width of "path" column 
3. close the application then search again and the "path" column width is reset to its defaults

**Expected behavior**
preserve the width configuration of columns

**Version**
 - installed FSearch from: PPA - stable
 - Version: `FSearch 0.1`

**Comment by mrubli** [comment]
Looking at the code there doesn't seem to be a code path that updates the internal config data structure (e.g. `config->path_column_width`) even though there is code for reading the column widths from and writing them to the config file. (That code is executed regardless of the "Remember column configuration" setting, by the way.)

I'm currently looking into creating a PR to implement this feature but in the meantime you can hand-edit `~/.config/fsearch/fsearch.conf` as a workaround and the column sizes will then persist.

(Note that this is related to issue #123 which was closed by the reporter without an obvious resolution.)

**Comment by cboxdoerfer** [comment]
Yes, the code for remembering the current size is just missing right now. I probably forgot to add during the transition from the GtkTreeView widget to the new FsearchListView.

@mrubli: It would be great if you want to work on that. If you have any questions, just reach out to me. Otherwise I'll probably add the feature back myself in the next couple of weeks.

**Comment by mrubli** [comment]
Thanks, that was really easy with your pointers. :+1: Please check out #293 and let me know if you want me to change something.

**Comment by Muhammad-2021** [comment]
path_column_width is worked for me
thanks all
