### ISSUE TITLE
[BUG] Ubuntu PPA installation of documentation file fails - Format issue - missing doc files

### ISSUE THREAD

**Issue by troubleshooter** [cboxdoerfer/fsearch#291]
See output below. 

### sudo apt-get install fsearch
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed
  fsearch
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 0 B/171 kB of archives.
After this operation, 824 kB of additional disk space will be used.
Selecting previously unselected package fsearch.
(Reading database ... 393265 files and directories currently installed.)
Preparing to unpack .../fsearch_0.1-0~202109251316~ubuntu20.04.1_amd64.deb ...
Unpacking fsearch (0.1-0~202109251316~ubuntu20.04.1) ...
Setting up fsearch (0.1-0~202109251316~ubuntu20.04.1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for doc-base (0.10.9) ...
**Processing 1 added doc-base file...
Error in `/usr/share/doc-base/fsearch', line 20: all `Format' sections are invalid.
Note: `install-docs --verbose --check file_name' may give more details about the above error.**
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24+linuxmint1) ...

### sudo install-docs --verbose --check /usr/share/doc-base/fsearch
Warning in `/usr/share/doc-base/fsearch': unknown section: `unknown'.
Warning in `/usr/share/doc-base/fsearch', line 11: file mask `/usr/share/doc/fsearch/fsearch.sgml.gz' does not match any files.
Warning in `/usr/share/doc-base/fsearch', line 14: file mask `/usr/share/doc/fsearch/fsearch.ps.gz' does not match any files.
Warning in `/usr/share/doc-base/fsearch', line 17: file mask `/usr/share/doc/fsearch/fsearch.text.gz' does not match any files.
Warning in `/usr/share/doc-base/fsearch', line 20: file `/usr/share/doc/fsearch/html/index.html' does not exist.
Error in `/usr/share/doc-base/fsearch', line 20: all `Format' sections are invalid.
/usr/share/doc-base/fsearch: Fatal error found, the file won't be registered.

OS: Ubuntu
Installed by: PPA
Version FSearch 0.1
Output of `localectl status`

   System Locale: LANG=en_GB.UTF-8
                  LANGUAGE=en_GB:en
                  LC_NUMERIC=en_US.UTF-8
                  LC_TIME=en_US.UTF-8
                  LC_MONETARY=en_US.UTF-8
                  LC_PAPER=en_US.UTF-8
                  LC_NAME=en_US.UTF-8
                  LC_ADDRESS=en_US.UTF-8
                  LC_TELEPHONE=en_US.UTF-8
                  LC_MEASUREMENT=en_US.UTF-8
                  LC_IDENTIFICATION=en_US.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105

**Comment by cboxdoerfer** [comment]
Thx for the report. I'll try to fix as soon as possible.

**Comment by cboxdoerfer** [comment]
Hm weird, I can't reproduce the bug on my Ubuntu 18.04, 20.4 and Debian Unstable installations. However I did some changes to the build process, which hopefully resolve that issue. The new packages should be ready in an hour or so.

**Comment by saalkom** [comment]
I didn't get the error when updating to the latest package under 20.04.

**Comment by troubleshooter** [comment]
I installed the updated package and that seemed to have fixed it. Thanks so much.

**Comment by cboxdoerfer** [comment]
Awesome! Thanks for letting me know.
