### ISSUE TITLE
[BUG] Attempt to update returns error

### ISSUE THREAD

**Issue by simurq** [cboxdoerfer/fsearch#292]
I received an update notification from my system (Pop OS 21.04) re: FSearch. But when I try to update, as per `The following packages have been kept back` error described in [this article](https://itsfoss.com/following-packages-have-been-kept-back/), it returns the following error:

[https://i.imgur.com/6b6tTxv.jpeg](url)

But in fact, I have FSearch updated to v0.1 a couple of days ago - I can also see this on `About` page with the word `beta` removed. 

Any clue what might prevent the update? Maybe you've changed some dependencies with the stable release.

Thank you!

**Comment by cboxdoerfer** [comment]
Hi, the `fsearch-trunk` package is now obsolete, it was replaced by the `fsearch` package. Hence you're getting an error when you want to install both at the same time. Just run:

`sudo apt install fsearch`

**Comment by simurq** [comment]
Thank you very much, Christian! It did the trick. Closing the issue...
