### ISSUE TITLE
[BUG] Übersetzungsfehlerchen

### ISSUE THREAD

**Issue by LinuxOpa** [cboxdoerfer/fsearch#294]
**Describe the bug**
Übersetzungsfehlerchen: Properties, Copy Text As, Path usw.
Nicht schlimm aber bei Gelegenheit bitte richten

**To Reproduce**
Innerhalb der Menüs

**Expected behavior**
deutscher Text

**Screenshots**
nicht nötig

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - How you installed FSearch: PPA
 - Version 0.1 aktuell
 - Output of `localectl status`:
System Locale: LANG=de_DE.UTF-8
       VC Keymap: n/a
      X11 Layout: de
       X11 Model: pc105

**Additional context**
Anmerkung: Sauschnell - Danke dafür!

**Comment by cboxdoerfer** [comment]
Fixed.
