### ISSUE TITLE
Datenbankupdate zu bestimmter Uhrzeit, z.B. 03:00

### ISSUE THREAD

**Issue by LinuxOpa** [cboxdoerfer/fsearch#295]
**Is your feature request related to a problem? Please describe.**
Kein Problem, nur ein Vorschlag

**Describe the solution you'd like**
Datenbankupdate zu bestimmter Uhrzeit, z.B. 03:00

**Describe alternatives you've considered**
Datenbankupdate zu bestimmter Uhrzeit, z.B. 03:00

**Additional context**
nix

**Comment by LinuxOpa** [comment]
ok, gefunden:
in crontab 0 3 * * * /usr/bin/fsearch --update-database
für mich erledigt

**Comment by cboxdoerfer** [comment]
Genau, `cron` ist eine Möglichkeit um die Datenbank zu bestimmten Zeiten zu aktualisieren. Im Wiki gibt es dazu auch einen Eintrag. Dort wird statt `cron` nur ein `systemd-timer` als Beispiel genutzt: https://github.com/cboxdoerfer/fsearch/wiki/Database-update

In English:
Exactly, `cron` is one way to update the database at certain points in time. The wiki describes how you can do that with `systemd-timers` instead: https://github.com/cboxdoerfer/fsearch/wiki/Database-update
