### ISSUE TITLE
[BUG] Menu key stopped working

### ISSUE THREAD

**Issue by blueclochard** [cboxdoerfer/fsearch#299]
Hi there,

It seems that around the introduction of version 1.0, the menu key (usually next to the righ Ctrl key and does the same as a right mouse click) stopped working. This is very useful if you want to open a file with a program that is not your standard program for opening a file. Think of opening an image in GIMP instead of your usual image viewer.

**To Reproduce**
1. Search for something random.
2. Hit the Menu key and nothing happens.

**Expected behavior**
The same menu that appears when you right click should appear.

**Desktop (please complete the following information):**
 - OS: Xubuntu 20.04.
 - Tried both the stable and daily builds from the Ubuntu PPA.
 - Version 0.1
 - The menu key works in other programs.

**Comment by cboxdoerfer** [comment]
Thx for letting me know, I'll fix it.

**Comment by cboxdoerfer** [comment]
This issue has been fixed a while ago.
