### ISSUE TITLE
Trying Compiling

### ISSUE THREAD

**Issue by sapomuyverde** [cboxdoerfer/fsearch#3]
Hi,
For me does not work…
./autogen.sh output:

```
Copying file po/Makefile.in.in

Please add the files
codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
progtest.m4
from the /usr/share/aclocal directory to your autoconf macro directory
or directly to your aclocal.m4 file.
You will also need config.guess and config.sub, which you can get from
ftp://ftp.gnu.org/pub/gnu/config/.

Unescaped left brace in regex is deprecated, passed through in regex; marked by <– HERE in m/\${ <– HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3930.
src/Makefile.am:33: warning: shell $(GLIB_COMPILE_RESOURCES: non-POSIX variable name
src/Makefile.am:33: (probably a GNU make extension)
```

./configure –prefix=/usr output:
`configure: error: invalid variable name: `–prefix'`

Any help is welcome.

Regards,
Javier

**Comment by cboxdoerfer** [comment]
Hi, which linux distribution are you using?

**Comment by cboxdoerfer** [comment]
Did you write? ./configure --prefix=/usr output

**Comment by sapomuyverde** [comment]
Hi,
I'm using solus, this is the output:

> javier@linuxsolus ~/fsearch $ ./autogen.sh
> Copying file po/Makefile.in.in
> 
> Please add the files
>   codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
>   progtest.m4
> from the /usr/share/aclocal directory to your autoconf macro directory
> or directly to your aclocal.m4 file.
> You will also need config.guess and config.sub, which you can get from
> ftp://ftp.gnu.org/pub/gnu/config/.
> 
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3930.
> src/Makefile.am:33: warning: shell $(GLIB_COMPILE_RESOURCES: non-POSIX variable name
> src/Makefile.am:33: (probably a GNU make extension)
> javier@linuxsolus ~/fsearch $ ./configure --prefix=/usr
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether make supports nested variables... (cached) yes
> ./configure: line 2877: syntax error near unexpected token `IT_PROG_INTLTOOL'
> ./configure: line 2877: `AX_REQUIRE_DEFINED(IT_PROG_INTLTOOL)'
> javier@linuxsolus ~/fsearch $ 

Any help is welcome.

Regards,
Javier

**Comment by cboxdoerfer** [comment]
@sapomuyverde, try installing a package called `gnome-common`. not sure how it's called exactly on Solus OS.

**Comment by sapomuyverde** [comment]
Hi Christian,
Finally it worked!!!

I appreciate your help, I have some questions, I realized that to find all files for example *.png, should I not use *.png, I have to try with .png, but what about for example search *myfile*.* or myfile.* and so.

PS: How to search the entire contents of the hard disk without adding each folder, and then I can exclude folders that I do not want.

Regards,
Javier

**Comment by cboxdoerfer** [comment]
>I appreciate your help, I have some questions, I realized that to find all files for example .png, should I not use *.png, I have to try with .png, but what about for example search *myfile.* or myfile.* and so.

That's what the regex mode is for (menu bar: Search -> Enable RegEx). There you can use the usual regular expressions with wildcards and so on. E.g. the regular expression for "myfile.*" is `myfile\.+`.

But simple wildcard queries like you mentioned will be added to the normal search mode soon.

>How to search the entire contents of the hard disk without adding each folder, and then I can exclude folders that I do not want.

Just add the root directory of the filesystem (e.g. by pressing Ctrl+L in the add folder dialog, insert '/' and hit enter), or by manually navigating to the root dir.

**Comment by cboxdoerfer** [comment]
Since you managed to compile it, I'm closing the issue. If you have any additional questions or suggestions, feel free to ask.

**Comment by sapomuyverde** [comment]
Hi,
I appreciate your help, Thank you for signs.

Regards,
Javier
