### ISSUE TITLE
"Open folder" not working properly in KDE

### ISSUE THREAD

**Issue by fwther** [cboxdoerfer/fsearch#30]
In KDE the "Open folder" function does follow the default application set in the System Settings, so I had to manually edit mimeapps.list in /home to Dolphin. This isn't ideal !

And, after setting it to Dolphin, all urls sent to it are prefixed with "smb://" and therefore don't open correctly. Using another file manager works fine, and opening folders in Dolphin from other apps also works fine. 

I'm running Arch with the latest KDE/Plasma packages, please tell me if you need more info. Hope this can be fixed, fsearch looks great so far :)

**Comment by cboxdoerfer** [comment]
Thx for reporting. Will be fixed, probably simultaneously with #29.
