### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by THEGODFATHERRX** [cboxdoerfer/fsearch#300]
**Describe the bug**
stuck on the popup "Failed to open file \n Do you want to keep the window open?" if I press yes or no, nothing happens.

**To Reproduce**
1. try to open any file that cannot be opened like file from unmounted drive 
2. both times ive run across this error, fsearch has been indexing in the background, so try to do the same.
3. you will be met with the ""Failed to open file \n Do you want to keep the window open?" if I press yes or no" ive pressed yes every time.
4. no error shows up in the terminal (ive started it from terminal, in root environment(su))

**Expected behavior**
popup should close, and let me continue my work
**Screenshots**
https://i.imgur.com/axecwdp.png

**Desktop (please complete the following information):**
 - OS: Manjaro with gnome 40
 - How you installed FSearch: AUR, also updated yesterday, but error has shown up before too.
 - Version : hmm, it tells me 0.1, but pamac tells me fsearch-git  0.1.r31.gd3ec76b-1   AUR  747.7 kB

  - Output of `localectl status`
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us-acentos
      X11 Layout: us
       X11 Model: pc105

**Additional context**
tried to open a file from an external drive which was not mounted at the time (ie was mounted when fsearch was indexing.)

will try to click again after indexing has finished and update this issue if it works or not.
UPDATE: https://i.imgur.com/hznURqB.png popup does not go away even after indexing stops.
im going to now try to reproduce the bug again, and see what happens if I press NO first, if it hangs or not.

UPDATE: Nah gets stuck even if I click NO first https://i.imgur.com/7zbehPN.png

**Comment by cboxdoerfer** [comment]
Thx, confirmed. I'll fix it with the 0.1.1 update.

**Comment by mlv-** [comment]
Same problem with the newest version (0.13) on Pop OS, flatpak version from Pop Shop. Had to kill the program after trying to open a folder with an outdated path.

**Comment by cboxdoerfer** [comment]
@mlv- I'll have a look at that
