### ISSUE TITLE
[BUG]Why is my FSearch icon unclear

### ISSUE THREAD

**Issue by wayne0926** [cboxdoerfer/fsearch#302]
This is a screenshot of the application menu, I have endured it for a long time, it is as bad as the pixel game chart of the last century

![image](https://user-images.githubusercontent.com/63389859/136011798-850ef684-a005-4e00-bef8-a0d91428f9eb.png)

![image](https://user-images.githubusercontent.com/63389859/136012332-77350539-71c1-42d0-9b6c-74e1db99bf3d.png)

**Comment by wayne0926** [comment]
> This is most certainly caused by your icon theme, because I've never seen such a low quality icon. Which icon theme do you use?

`Yaru`
At the same time, I discovered that the Fsearch icon becomes strange only under the Yaru icon theme...
![image](https://user-images.githubusercontent.com/63389859/137572590-489ab6cb-0b05-4be2-9d70-0c7c54ce8d87.png)
![image](https://user-images.githubusercontent.com/63389859/137572608-d7df699a-49fb-444e-8c30-297b83fe542b.png)

**Comment by cboxdoerfer** [comment]
FSearch now ships its own icon. It's not the greatest and will probably be replaced at some point, but at least this fixes this issue.
