### ISSUE TITLE
[BUG]? /  com*   / search does not work as expected

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#304]
**Describe the bug**
When I search this way, I get no results:
![ksnip_20211017-162609](https://user-images.githubusercontent.com/13977359/137631789-6b9fd7a3-6df6-4786-a67f-7b6a4dcf5951.jpg)

But when uncheck "suche in pfad", then I get a lot of results.

Is this as it should behave?

**Expected behavior**
My expectation was, that I also would get results when "suche in pfad" is checked.

**Desktop (please complete the following information):**
 - OS: [MX Linux 19.4 Xfce]
 - How you installed FSearch [MX package installer]
 - Version [0.1]
 - Output of `localectl status`:
```
$ localectl status
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Der Rechner ist nicht aktiv

```

**Comment by cboxdoerfer** [comment]
No, what the `Search in path` option does is, that it passes the full path to the resp. search function. So only if the expression matches against the full path (e.g. `/home/testuser/testdir/testfile`) will you get any results.

**Comment by Golddouble** [comment]
OK. Thank you.

I understand now. 
"Search in path" does mean
--> search **ONLY** in path
and not
--> search **IN ADITIONAL** in path

**Comment by cboxdoerfer** [comment]
@Golddouble, exactly.
