### ISSUE TITLE
[BUG] Die Spaltenbreite der Spalte "geändert am" behält den Wert nicht beim schliessen und öffnen

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#305]
**Describe the bug**
Der Titel sagt alles.

**To Reproduce**
1. Oeffne Fsearch
2. verändere die Spaltenbreite
3. Schliesse Fsearch
4. Oeffne Fsearch erneut
5. Die Spaltenbreite ist wieder wie am Anfang. Die Korrektur von vorhin aht keine Wirkung.

**Expected behavior**
Die Spaltenbreiten sollten die Breite behalten.

**Screenshots**
Animation:
![Peek 2021-10-18 14-09](https://user-images.githubusercontent.com/13977359/137727994-8749d07c-4f6e-4856-80d4-9cf8ace2dcea.gif)

**Desktop (please complete the following information):**
 - OS: [MX Linux 19.4 Xfce]
 - How you installed FSearch [Mx Packet Installer]
 - Version [0.1]
 - Output of `localectl status`
```
 $ localectl status
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Der Rechner ist nicht aktiv
```

**Additional context**
Nicht nur, dass die Spaltenbreiten ihre Breite nicht behalten, sondern die Spalte "geändert am" ist sinnlos breit nach jedem Oeffnen.

**Comment by cboxdoerfer** [comment]
Der Fehler wurde bereits behoben, es dauert aber noch etwas bis die Version 0.1.1 veröffentlicht wird.
