### ISSUE TITLE
Select first/last-used result on enter

### ISSUE THREAD

**Issue by lucidBrot** [cboxdoerfer/fsearch#308]
**Is your feature request related to a problem? Please describe.**
When I search for a file, I would like to open it without using the mouse. Additionally, I would like to quickly open the specific file I am searching for and not a different one with the same name.

**Describe the solution you'd like**
Everything-Search is a similar tool I use on windows. They solve this problem in this way:  
* When I press enter, the entry is selected. When I press enter again, it is opened.
  I see that you have already implemented opening by pressing enter, and opening the directory by pressing ctrl+enter, so I figure the implementation should be relatively low-effort to do the selection. In fact, this functionality already exists for the down-arrow so I might as well use that - it would just be a slight convenience improvement to have Enter work as well.  
* I often search for the same file multiple times. Everything remembers which file I chose last time when I searched for the same (or a similar, if you want to go that far) term. E.g. I have one file called `todo.md`  that I use regularly and many other `todo.md` in other locations that I don't really care about. If fsearch would select the same file I opened last time when I search for `todo` again, that would be very convenient. Note that I would suggest that this behaviour does not happen on the Down-Arrow press, only on Enter, because Down-Arrow implies to go down from the search bar to the topmost list entry.

**Describe alternatives you've considered**
* Just use the Down-Arrow key  
  This works, but requires moving the hand away from where it was when typing. It does not solve the second point.

Thank you for your time! This issue is not pressing or anything, but it's something I noticed several times now as a minor annoyance, so I thought I should at least post the idea :blush:

**Comment by cboxdoerfer** [comment]
Hey, thanks for those suggestion!

> Everything remembers which file I chose last time when I searched for the same (or a similar, if you want to go that far) term. 

Interesting, I didn't know about that. So hitting enter in the search field does the following in Everything:

* if the results contain files which were previously opened -> focus the first one of these
* otherwise -> focus the first file in the result list

?

**Comment by lucidBrot** [comment]
Thanks for your reply! :blush:


> Also, can you check what Everything does when "Search as you type" is disabled (i.e. the results only update after hitting enter)?

I'm not noticing any difference in behaviour regarding this, when I disable "search as you type".

> otherwise -> focus the first file in the result list  

That's correct for sure

> if the results contain files which were previously opened -> focus the first one of these  

I assumed they focus the last-chosen one of these, not just the first in the list. But I just tried that out by choosing a different file than I usually open when I search for `todo` and it was not selected next time I searched for `todo`. My guess is that they keep track of which file was opened how many times (in the past N days, maybe) and select the one that was opened the most often. But those are just guesses.

I think the difference between "select the file that was opened the most from this tool in the past N days" and "select the last file that was opened from this tool" in terms of usefulness is not huge, so if one is way more effort to implement than the other...

**Comment by ComplexPlane** [comment]
Hi, strongly voting for this feature myself. Everything search does this, Nautilus file search does this, Windows start menu does this, it's essential to this program's workflow in my opinion.

**Comment by cboxdoerfer** [comment]
@ComplexPlane I'm currently adding this feature. Everything seems to first select the first result when you hit enter, and only opens the result upon the second key press. Is this something you prefer or should the result be selected and opened on the first press?

**Comment by cboxdoerfer** [comment]
Done. For now I decided to only select the first result and focus the result list when pressing enter.

**Comment by ComplexPlane** [comment]
Awesome!! I think enter to select is reasonable for now as well.

**Comment by skjerns** [comment]
Awesome! 

Is there a possibility to get the other feature on the roadmap? 😇

It was really useful in Everything that after selecting a certain file from a query, next time I run the query, the same file get's focused once I press enter. I guess some sort of counter was added to the database, keeping track on how often each file was accessed via Everything? Or maybe just the last selection date?

**Comment by cboxdoerfer** [comment]
@skjerns, yes the run history with better auto-selection is already on my TODO list. Though I'm not sure if it'll be part of the next 0.3 release, because this release is already getting quite big and I don't want to delay it any further than necessary. So unless someone else wants to work on that it'll probably take a few months before I get to that.
