### ISSUE TITLE
gnome shell extension

### ISSUE THREAD

**Issue by wouzer51** [cboxdoerfer/fsearch#312]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The addition of a gnome-shell extension (searchfield in the top bar) would make this an absolute killer app. I don't know if such thing exists for Plasma as well, but smooth DE-integration would make your app even cooler.
Maybe even a nautilus-addon to integrate even more.

**Describe alternatives you've considered**
None

**Additional context**
none

**Comment by cboxdoerfer** [comment]
Thx for the suggestion, but this feature request is already covered with #152
