### ISSUE TITLE
Allowing to open .desktop files from search results

### ISSUE THREAD

**Issue by PPC-scripts** [cboxdoerfer/fsearch#313]
I love fsearch (I consider it and Drill the best file searcher apps available under Linux), but, with little effort, fsearch can also be used as a simple application launcher- if one add /usr/share/applications to the folder's list- fsearch does display the .desktop matching the query (ex: Brave) but it's unable to start that application from the search result (it's opened as a text file)- you can run the executable refereed inside the .desktop file using something like " awk -F= '/Exec=/{system($2)}'  [path/to/desktop_file]"
 Very nice job!

**Comment by cboxdoerfer** [comment]
Thx for the suggestion. I'll add that to my todo list. I will probably add an option to specify if desktop files should be treated like apps or regular files.

As for how they can be launched, thankfully the GIO library handles that ([documentation](https://docs.gtk.org/gtk3/migrating-2to3.html#use-gio-for-launching-applications)) and it also honors fields like `Terminal=` in the desktop file, so this should probably be the way to implement this feature.

**Comment by cboxdoerfer** [comment]
@PPC-scripts, I've now added that option - it's enabled by default. I've also added a filter to only show desktop files.

**Comment by PPC-scripts** [comment]
hi, Christian

I compiled and tested fsearch- it works great! The only down side to this
feature is that there a bit more for me to localize :-)
 I've been using fsearch for a couple of months now and I want to let you
know- I'm an antiX Linux user/contributor (it's a tiny debian based distro,
specialized in running in old devices) and I've been developing an
alternative User Interface that uses tint2 as toolbar and jgmenu as menu-
it takes the best features from KDE, Windows 10, Windows 11 and mixes them
into a (what I hope) is a very good user experiece, running on about 100mb
of Idle RAM. I'm trying to figure out if I should add a compiller for
fsearch into my installer, insuring that it can be used as default file
searcher in this UI, because fsearch is not yet on the antiX repository
 If you want to check out my project it's over at
https://gitlab.com/antix-contribs/ft10-transformation

Best regards,

P.

Christian Boxdörfer ***@***.***> escreveu no dia domingo,
12/12/2021 à(s) 11:47:
