### ISSUE TITLE
[BUG] fsearch doesn't start after updating icu (libicuuc.so)

### ISSUE THREAD

**Issue by bugtracker2019** [cboxdoerfer/fsearch#314]
Hi,
I'am running Arch Linux. After a recent update (pacman -Syu) fsearch doesn't start anymore, complaining about icu.

> fsearch: error while loading shared libraries: libicuuc.so.69: cannot open shared object file: No such file or directory

So I made a symbolic link `sudo ln -s /usr/lib/libicuuc.so.70.1 /usr/lib/libicuuc.so.69`
which got me a little step further, but still an error appeared: 

> fsearch: symbol lookup error: fsearch: undefined symbol: unorm2_normalizeSecondAndAppend_69

Maybe it helps, so here are the last lines of `ldd -r /usr/bin/fsearch`:

> undefined symbol: unorm2_normalizeSecondAndAppend_69	(/usr/bin/fsearch)
> undefined symbol: unorm2_spanQuickCheckYes_69	(/usr/bin/fsearch)
> undefined symbol: ucasemap_close_69	(/usr/bin/fsearch)
> undefined symbol: ucasemap_utf8FoldCase_69	(/usr/bin/fsearch)
> undefined symbol: unorm2_getNFDInstance_69	(/usr/bin/fsearch)
> undefined symbol: u_strncpy_69	(/usr/bin/fsearch)
> undefined symbol: u_strFindFirst_69	(/usr/bin/fsearch)
> undefined symbol: u_strFromUTF8_69	(/usr/bin/fsearch)
> undefined symbol: ucasemap_open_69	(/usr/bin/fsearch)

**To Reproduce**
1. Update icu to 70.1-1
2. Start fsearch

**Expected behavior**
Should run. ;)

**Desktop:**
 - OS: Arch Linux
 - installed via AUR
 - fsearch version 0.1

**Comment by cboxdoerfer** [comment]
You probably need to rebuild fsearch (i.e. reinstall from the AUR). Arch maintainers do that automatically for all the packages in the official repos when a dependency breaks its ABI or symbol names change, but for packages from the AUR you need to do it manually.

**Comment by bugtracker2019** [comment]
Yes, that's it. After rebuilding the package everything is fine.
Schönes Wochenende!
