### ISSUE TITLE
fsearch: error while loading shared libraries: libicuuc.so.69: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Skrimpton** [cboxdoerfer/fsearch#316]
fsearch: error while loading shared libraries: libicuuc.so.69: cannot open shared object file: No such file or directory

I get this error when trying to start fsearch on manjaro KDE version after the last system update.

Not sure if it's me-issue, manjaro-issue or a fsearch-issue.

Anyways, thank you for the best search app, never had a problem until now, and I suspect this might be a me-issue.

**Comment by cboxdoerfer** [comment]
Hi, that's caused by how the AUR on Arch and Manjaro works. From the AUR wiki:

> The AUR is unsupported, so any packages you install are your responsibility to update, not pacman's. If packages in the official repositories are updated, you will need to rebuild any AUR packages that depend on those libraries.

In this case Arch/Manjaro updated libicu and FSearch depends on it, so all you need to do to fix this issue to rebuild/reinstall FSearch from the AUR.

**Comment by Skrimpton** [comment]
Fantastic! Thank you for the quick reply!
