### ISSUE TITLE
Custom filter support

### ISSUE THREAD

**Issue by djkazaz** [cboxdoerfer/fsearch#317]
**Describe the solution you'd like**

I would like to be able to define a category of files for frequent searches, similar to audio, documents etc, e.g. ebooks: epub, mobi, pdf...
This is useful if you run such searches frequently - similar functionality exists in "everything" on windows.

**Describe alternatives you've considered**
Using multiple wildcards, but that's not ideal for frequent searches 

Thank you for considering this request!

**Comment by cboxdoerfer** [comment]
Thx, for the request. This is now possible.

**Comment by djkazaz** [comment]
Fantastic, thank you!
