### ISSUE TITLE
add filtering options like Everything

### ISSUE THREAD

**Issue by danielkrajnik** [cboxdoerfer/fsearch#319]
most needed:
folder: (fliter folder)
file: (filter file)
datemodified: (when was modified)

EDIT: I will try to periodically keep adding to the list

**Comment by cboxdoerfer** [comment]
All of those filters have now been implemented. The format for "datemodified" is a little different and not as feature rich yet, but things like: `dm:today` or `dm:2020..2021` work already.

These features have not been documented yet outside of the code, but I'll make sure the documentation is ready for the next release.

**Comment by danielkrajnik** [comment]
That is amazing! Thank you!!! Going to test it as soon as possible

**Comment by cboxdoerfer** [comment]
No problem. Let me know if you have any suggestions or notice any strange behavior. There's also now support for explicit `AND`/`&&` and `OR`/`||` operators and grouping with `(` and `)`, so you can do things like:

`file:(*.pdf || *.odt) dm:20`

To get all PDFs or ODTs which were modified in 2020. The space between `)` and `dm` is always treated like an `AND`.

In addition to those hardcoded filters you can now also add custom filters in the preferences dialog, with a custom search text and macro name. For example you can add a custom filter for the above query:

 Name: `Documents 2020`
 macro: `doc2020`
 query: `file:(*.pdf || *.odt) dm:20`
 
And then you can simply type `doc2020:` in the search entry to get the same results.

**Comment by cboxdoerfer** [comment]
Here are all the default fields which are currently supported: https://github.com/cboxdoerfer/fsearch/blob/master/src/fsearch_query_parser.c#L77

**Comment by danielkrajnik** [comment]
Brilliant, one suggestion would be to also add the "!" (NOT) operator. Please correct me if it's there already, but it would be great if one could exclude some search results, for example 
```!.pdf```
to filter out all pdf files

**Comment by cboxdoerfer** [comment]
Just forgot to mention it, the not operator is also supported, both `!` and `NOT` works. ;)

**Comment by danielkrajnik** [comment]
Sorry for the late reply, but I was just trying the `!` `NOT` function and for some reason it yielded more results rather than filtering them out. I've tried to filter out part of the path, not a filename though - is it supported? I've built it from source following the BUILD instructions: https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions

**Comment by danielkrajnik** [comment]
I've just tried new fsearch - built from source following the instructions: https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions. I've noticed that `!` `NOT` works only is enclosed in parentheses like `(!keyword)`. This doesn't seem to work: `!keyword`. Is that intended? In Everything the second option usually works.

**Comment by cboxdoerfer** [comment]
Thx for the feedback. No, that's not how it's supposed to work, sounds like a bug.

Can you give a specific example to trigger the issue? Like what search term you're using and what filename it finds, even though it shouldn't?

**Comment by danielkrajnik** [comment]
![image](https://user-images.githubusercontent.com/15096799/161377157-29915d76-f55d-4f91-b20c-96416ae70e23.png)
![image](https://user-images.githubusercontent.com/15096799/161377178-1fd7e985-32f7-4c87-9ada-30798e559e58.png)

**Comment by cboxdoerfer** [comment]
Thanks! I can reproduce that. That's a bug in the implicit AND handling - FSearch simply didn't add one without the parentheses. If you write the AND explicitly, like so `.local AND !.Platform` it should also work. I'll fix that.

**Comment by cboxdoerfer** [comment]
Fixed. In case you're not familiar with `git` and how to get the latest code: simply go the the source directory of FSearch where you ran the 'make` commands, and now run `git pull && make && sudo make install` to fetch the new code, build and install it.

**Comment by danielkrajnik** [comment]
Oh I see, thank you. I've run the commands above and now it's working here as well! Fantastic, that was really efficient - haven't had a chance to work with an open-source developer before. 
![image](https://user-images.githubusercontent.com/15096799/161378615-5f8c765f-c0f1-4994-9115-f4b80fccf850.png)

**Comment by danielkrajnik** [comment]
I see, thank you. I've run the above commands and tested it again and it works if you try to `NOT` the second keyword, but it doesn't seem to work for the subsequent keywords. Like you mentioned above it works if `AND` is put before a `!keyword` anywhere though

![image](https://user-images.githubusercontent.com/15096799/161378952-c573510c-cb9f-43c2-a708-6b4042e3a441.png)

**Comment by cboxdoerfer** [comment]
Thanks again, that's awesome feedback, I really appreciate that. The issue should now be fixed as well.

**Comment by danielkrajnik** [comment]
Perfect, thank you again. It works here as well. Sounds like an intersting issue.
![image](https://user-images.githubusercontent.com/15096799/161381659-37e547f6-2a34-415e-b262-cfd016b94f59.png)

One minor thing that I've noticed - filtering out `!dm:1970` (date modified in year 1970) didn't work. It's probably less common for searching network locations/Google drive though.

**Comment by cboxdoerfer** [comment]
Thanks, I'll have a look at the date issue.

Btw, there's also some debug output for these type of issues, that way you can often avoid having to post screenshots. When you run FSearch with the following command `env G_MESSAGES_DEBUG=fsearch-query-tree fsearch` you get the following output every time the search text changes:

    (fsearch:8974): fsearch-query-tree-DEBUG: 13:44:03.466: [QueryParser]
    (fsearch:8974): fsearch-query-tree-DEBUG: 13:44:03.466:  * global_flags: 
    (fsearch:8974): fsearch-query-tree-DEBUG: 13:44:03.466:  * input: a b !c
    (fsearch:8974): fsearch-query-tree-DEBUG: 13:44:03.466:  * output: [ascii_icase:'a':] [ascii_icase:'b':] AND [ascii_icase:'c':] NOT AND 

This is often enough for me to know what's going wrong.

**Comment by danielkrajnik** [comment]
Thanks, that's true, publishing your disk's contents doesn't feel very secure.

```(fsearch:1600728): fsearch-query-tree-DEBUG: 12:57:00.175: [QueryParser]
(fsearch:1600728): fsearch-query-tree-DEBUG: 12:57:00.175:  * global_flags: Auto Match Case, Auto Search in Path, Search in Path
(fsearch:1600728): fsearch-query-tree-DEBUG: 12:57:00.175:  * input: local share !dm:1970
(fsearch:1600728): fsearch-query-tree-DEBUG: 12:57:00.175:  * output: [ascii_icase:'local':CPp] [ascii_icase:'share':CPp] AND [date-modified:'1546300800..1577836800':CPp] NOT AND```

**Comment by cboxdoerfer** [comment]
Thanks! Yes, the issue with `dm:1970` is related to your local daylight time savings, it causes the unix timestamp to go below zero, which the parser currently treats as an invalid time and then it tries to guess a different time from the input, which will be dm:19 i.e. dm:2019, so it omits the 70. I'm not sure yet what's the best way to handle this edge case, but I'll think about it.

**Comment by cboxdoerfer** [comment]
The issue with `dm:1970` should now be fixed.

**Comment by danielkrajnik** [comment]
hmm... not sure why, but `!dm:1970` didn't seem to work:
```
Found date: 5
(fsearch:1401981): fsearch-query-tree-DEBUG: 20:21:11.442: [QueryParser]
(fsearch:1401981): fsearch-query-tree-DEBUG: 20:21:11.442:  * global_flags: Auto Match Case, Auto Search in Path, Search in Path
(fsearch:1401981): fsearch-query-tree-DEBUG: 20:21:11.442:  * input: !dm:1970
(fsearch:1401981): fsearch-query-tree-DEBUG: 20:21:11.442:  * output: [date-modified:'1546300800..1577836800':CPp] NOT
```

**Comment by cboxdoerfer** [comment]
Thanks, then I probably still missed something. I'll have a look. Which timezone are you in?

**Comment by danielkrajnik** [comment]
Thanks, British Summer Time Time zone in London, UK (GMT+1)

**Comment by cboxdoerfer** [comment]
Next attempt to fix this. It seems it's not related to daylight saving time, but rather to timezones only - the documentation of those time functions is a little confusing.

Your timezone is 1 hour ahead of UTC, which is used for the unix time, so 1970 in your timezone starts at 1969-12-31 23:00 UTC, which would be a negative and invalid unix time (-3600) and hence can't be parsed. The parser now guards against that and always starts at 0, which will be 1970-01-01 01:00 GMT+1 in your case.

**Comment by cboxdoerfer** [comment]
Btw. we're going to visit London in a couple of days for the first time, so if you got any insider tips for things we must see or visit or do, I'd appreciate that ;)

**Comment by danielkrajnik** [comment]
Perfect, can confirm that `!dm:1970` works in London now as well. Haha, I recommend Soho in the evening here for any entertainment, restaurant or a club/pub.
