### ISSUE TITLE
"Open Folder" Does Not Select The Opened File

### ISSUE THREAD

**Issue by blueray453** [cboxdoerfer/fsearch#322]
**Is your feature request related to a problem? Please describe.**
When I right click a searched file and click "Open Folder" (Ctrl+Return) , it does not not select the opened file in the file explorer (in my case `nemo`).

**Describe the solution you'd like**
When I right click a searched file and click "Open Folder" , I want the file which I right clicked to be selected in the opened file explorer.

When I right click on `/home/ismail/Documents/a.adoc`  and click "Open Folder" , it acts like I used the command `nemo /home/ismail/Documents`. The result looks like

![Screenshot-2021-12-16-19:32:05](https://user-images.githubusercontent.com/855297/146381207-82ba88d7-43e1-4e29-9e98-3dbbbfc05d18.png)

What i want is , when I right click on `/home/ismail/Documents/a.adoc`  and click "Open Folder" , it should act like I used the command `nemo /home/ismail/Documents/a.adoc` so that the result looks like

![Screenshot-2021-12-16-19:31:48](https://user-images.githubusercontent.com/855297/146381205-a73f3af3-575a-445c-83a1-11fb3e3d0cff.png)

**Additional context**

Though I am not an expert, i checked the source code. I think it has something to do with `fsearch_window_actions.c`'s 

```
static void
fsearch_window_action_open_folder(GSimpleAction *action, GVariant *variant, gpointer user_data) {
    FsearchApplicationWindow *self = user_data;
    fsearch_window_action_open_generic(self, open_folder_cb);
}
```
It is probably only sending the directory path to nemo instead of sending the full file path.

**Comment by cboxdoerfer** [comment]
> When I right click a searched file and click "Open Folder" (Ctrl+Return) , it does not not select the opened file in the file explorer (in my case nemo).

The reason why this doesn't work by default yet is because I haven't found a way to make it work on all file managers.

> What i want is , when I right click on /home/ismail/Documents/a.adoc and click "Open Folder" , it should act like I used the command nemo /home/ismail/Documents/a.adoc so that the result looks like

This command only works when you select a file. If `a.doc` is a folder then `nemo` will just open that folder instead of selecting it. That's why for example Nautilus has the `--select` flag, which explicitly selects the last element, regardless whether it's a file or folder.

FSearch has an undocumented setting which allows you to make use of that and configure the folder open command. So if Nemo has the `--select` flag, you can simply add this to the end of your FSearch config file:

```
[Applications]
folder_open_cmd=nemo --select {path_full}
```

**Comment by blueray453** [comment]
Thank you very much.

**Comment by blueray453** [comment]
If I add 
```
[Applications]
folder_open_cmd=nemo {path_full}
```
to `/home/ismail/.config/fsearch/fsearch.conf` , the lines go away when close and open (restart) fsearch.

**Comment by cboxdoerfer** [comment]
You have to add them to the config file while FSearch isn't running.

**Comment by Carsten-Kaftan** [comment]
Thank God I found this »undocumented setting« here. Works fine with `folder_open_cmd=caja -s {path_full}` too. Automatically selecting the find result in the opened folder increases the practical value of FSearch very much, as it saves a few irritating seconds every time you use FSearch to collect a file.

> The reason why this doesn't work by default yet is because I haven't found a way to make it work on all file managers.

Perhaps it would be suitable to add an entry in Preferences to choose the favored file manager? And, depending on the choice, adding the appropriate folder_open_cmd entry to the configuration file? 

Thanks a lot for providing us with FSearch
Carsten
