### ISSUE TITLE
How to debug fsearch 

### ISSUE THREAD

**Issue by blueray453** [cboxdoerfer/fsearch#323]
I checked the build instructions from https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions

What I want to know is how to debug this project.

I found that I can use `g_debug("Message")` and the messages will be shown in the terminal when I run `make && sudo make install`

How to track different functions and variables to know how the program is actually running.

I am mostly sure that `make && sudo make install` is not the command to debug the source code. Because it is only showing warnings. And also it is completely deploying the program and working with the project as a whole and not dealing with individual files so developing with `make && sudo make install` will take longer.

Please give me an example of https://github.com/cboxdoerfer/fsearch/issues/322 . How can i know what values am I passing to nemo. How can I know where do I need to make changes and what changes i need to make to solve this issue.

**Comment by cboxdoerfer** [comment]
> I found that I can use g_debug("Message") and the messages will be shown in the terminal when I run make && sudo make install

No, those commands just build and install FSearch. The `g_debug` messages will be printed at runtime, i.e. when you launch FSearch from the command line. You can also omit the install part while playing with the code. When you're in the top level source directory of FSearch you can simply run `make && ./src/fsearch` to build and run FSearch with the latest changes.

> Please give me an example of #322 . How can i know what values am I passing to nemo. How can I know where do I need to make changes and what changes i need to make to solve this issue.

Do you know how `printf` formatting in C works? If so you can use the same in `g_debug` calls, which allows you to print the state of variables and those then get printed once the code path gets executed.

Alternatively you could also use a debugger with breakpoints and then inspect the variables, if you're familiar with that.

**Comment by blueray453** [comment]
Thank you very much.
