### ISSUE TITLE
Enable/disable RegExp search by hotkey

### ISSUE THREAD

**Issue by ciases** [cboxdoerfer/fsearch#324]
It's not a big problem, but sometimes it's not obvious in a what search mode I'm in. There is no any indicator about regexp.

It would be nice to have a hotkey to enable/disable regexp mode with some kind of visual warning. For example, pressing F8 is enable regexp and change background/foreground colors of input field.

**Comment by cboxdoerfer** [comment]
The current search mode (including regex mode) is displayed in the right corner of the status bar. Or do you mean something else?

**Comment by ciases** [comment]
Oops! My bad. There is an indicator.
What about hotkey? Is it hard/make sense to implement?

**Comment by cboxdoerfer** [comment]
Yes, hotkeys are already there for search modes

* `ctrl-r` regex mode
* `ctrl-u` search in path
* `ctrl-i` match case

**Comment by cboxdoerfer** [comment]
Yes, hotkeys are already there for search modes

* `ctrl-r` regex mode
* `ctrl-u` search in path
* `ctrl-i` match case

**Comment by ciases** [comment]
No way! It works! Thank you for quick feedback and great software. Cheers!
