### ISSUE TITLE
Micro-improvement of the search menu

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#330]
When I search with wildcards instead of Regex, I can activate or deactivate "search in path". When I deactivate it, it does not search in path.

So I was expecting, that the behaviour is the same, when I search with Regex. My expectation was:
When I search with Regex instead of wildcards, I can activate or deactivate "search in path". When I deactivate it, it does not search in path.

But this is wrong when I use Regex. When I use Regex, it does always search in path, regardless of whether "search in path" is activated or not.

Is this as it shout be? If yes, I would suggest to change the search menu in the menu-bar of Fsearch in a way, that this is more clear.

Here is what I would suggest:
![ksnip_20211230-102103](https://user-images.githubusercontent.com/13977359/147738838-e9119804-70ed-4c51-bdc6-c1514d4809d0.jpg)

Please note you can only choose one of the options
*search with wildcards inclusive path
*search with wildcards without path
*search with Regex inclusive path 
in addition you can activate or unactivate "respect upper and lower case".

This menu would represent exactly the behaviour of Fsearch. No one would expect now, that a Regex search would not automatically search in the path.

What do you think?

Edit:
Or maybe some other text:
*search with wildcards - include path
*search with wildcards - ignore path
*search with Regex - include path

**Comment by cboxdoerfer** [comment]
> But this is wrong when I use Regex. When I use Regex, it does always search in path, regardless of whether "search in path" is activated or not.

This sounds like a bug. I don't have access to my computers right now, but I'll have a look at it next week.

**Comment by cboxdoerfer** [comment]
I just tried to reproduce it and regex mode works like expected and honors the search in path option, which means it only searches in paths when the search in path option is enabled.

Can you provide an example and screenshot of the issue?

**Comment by Golddouble** [comment]
I have tried again. But now I can't reproduce it any more either.
I do not remember the example I have tried when I have reported this.
So Maybe I was mistaken? Sorry.
Or it was only with a particular example.

I close this issue, but I'll get back to you when I have an example.
