### ISSUE TITLE
Is 0.1.1 stable/recommended?

### ISSUE THREAD

**Issue by ryandesign** [cboxdoerfer/fsearch#331]
A git tag for 0.1.1 was created two days ago but a GitHub release was not created for this version, so the latest release shown on the project's GitHub main page is still 0.1. Please create a GitHub release for 0.1.1. If it is stable/recommended, mark the release as stable. If it is for development/testing, mark the release as "pre-release".

**Comment by cboxdoerfer** [comment]
Thx for the reminder, I've published the 0.1.1 release on GitHub.
