### ISSUE TITLE
[BUG] Why when I do a file search all the results are duplicated?

### ISSUE THREAD

**Issue by aliquo93** [cboxdoerfer/fsearch#332]
**Describe the bug**
As the title says, when I do a file search all the results are duplicated.

**To Reproduce**
Do a file search.

**Expected behavior**
The results shouldn't be duplicated.

**Screenshots**
![1](https://user-images.githubusercontent.com/9071297/150921024-91c275bf-97e7-45d8-9e66-f74df542d211.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 21.10 x86_64
 - Kernel version: 5.13.0-27-generic
 - KDE Plasma version: 5.23.5
 - KDE Frameworks version: 5.90.0
 - Qt version: 5.15.2
 - How you installed FSearch [from offical FSearch PPA: http://ppa.launchpad.net/christian-boxdoerfer/fsearch-stable/ubuntu/]
 - Version [FSearch 0.1.1]
 - Output of `localectl status`:
 ` System Locale: LANG=it_IT.UTF-8
       VC Keymap: n/a
      X11 Layout: it
       X11 Model: pc105`

**Comment by cboxdoerfer** [comment]
Can you provide a screenshot of the database settings? You most likely included the same directory twice.

**Comment by aliquo93** [comment]
> 

Nope, I've included `/ `and `/home`

![db](https://user-images.githubusercontent.com/9071297/150928107-e1802744-d86f-49f4-8038-1d29b6085fce.png)

**Comment by aliquo93** [comment]
I have them on 2 separate partitions, maybe I have to flag the "One Filesystem" option?

**Comment by cboxdoerfer** [comment]
No, the solution is to only include `/`, since home is a subdirectory of it, it will be included automatically.

25 Jan 2022 08:09:21 aliquo93 ***@***.***>:

**Comment by aliquo93** [comment]
Ok, now it works! Thank you very much! I thought I had to split them because I have them in two separate partitions.

Anyway, just for curiosity, what the option "One Filesystem" do?

**Comment by cboxdoerfer** [comment]
Awesome 👍

The one filesystem option does basically what you expected, it tells FSearch to stay on the filesystem this particular directory belongs to. So checking that box for `/` would have also solved your issue, however  if you just want to include everything it's simpler (and maybe a tiny tiny bit faster) to just include `/` without the one filesystem flag.

**Comment by cboxdoerfer** [comment]
In hindsight my "No" from earlier was not good answer. Here's a better one with two options:

If you only want to include particular mount points, for example to make sure unwanted external drives or network shares don't get included by accident, then use the one filesystem option and include every mount point you want separately, e.g. `/` and `/home`, both with the one file system flag set. But if you just want to include everything, then only add `/` without the one file system option.
