### ISSUE TITLE
[BUG] Updates

### ISSUE THREAD

**Issue by selahattinilhan** [cboxdoerfer/fsearch#339]
Updates are coming every day. I update it daily, yet it keeps coming.

**Comment by selahattinilhan** [comment]
> I suppose you're using one of the daily development build channels, like the fsearch-daily PPA? If so that's obviously expected, as hinted by the name: You get an update every day if there have been changes to the code.
> 
> If you don't want to get daily updates you shouldn't use the development versions. Instead you should use one of the stable channels mentioned on the main GitHub page, where you get updates once every couple of months.

I used the following commands while installing:

sudo add-apt-repository ppa:christian-boxdoerfer/fsearch-daily
sudo apt-get update
sudo apt install fsearch-trunk

maybe i made a mistake.

**Comment by selahattinilhan** [comment]
> > I suppose you're using one of the daily development build channels, like the fsearch-daily PPA? If so that's obviously expected, as hinted by the name: You get an update every day if there have been changes to the code.
> > If you don't want to get daily updates you shouldn't use the development versions. Instead you should use one of the stable channels mentioned on the main GitHub page, where you get updates once every couple of months.
> 
> I used the following commands while installing:
> 
> sudo add-apt-repository ppa:christian-boxdoerfer/fsearch-daily sudo apt-get update sudo apt install fsearch-trunk
> 
> maybe i made a mistake.

I tried uninstalling and reinstalling, the icon disappeared, the code below doesn't work:

sudo add-apt-repository ppa:christian-boxdoerfer/fsearch-stable
sudo apt-get update

**Comment by selahattinilhan** [comment]
> I tried uninstalling and reinstalling, the icon disappeared, the code below doesn't work:
> 
> sudo add-apt-repository ppa:christian-boxdoerfer/fsearch-stable sudo apt-get update

edit: I installed from ubuntu store.

**Comment by cboxdoerfer** [comment]
> I tried uninstalling and reinstalling, the icon disappeared, the code below doesn't work:
> 
> sudo add-apt-repository ppa:christian-boxdoerfer/fsearch-stable
> sudo apt-get update

What didn't work? What was the output? Did you remove the daily PPA?

**Comment by selahattinilhan** [comment]
> What didn't work? What was the output? Did you remove the daily PPA?

yes I removed it. when i reinstalled it seemed like the installation was complete but there was no icon.

**Comment by cboxdoerfer** [comment]
What's the output of `apt show fsearch`?

**Comment by selahattinilhan** [comment]
> What's the output of `apt show fsearch`?
**Turkish:**
N: '/etc/apt/sources.list.d/' dizinindeki 'christian-boxdoerfer-ubuntu-fsearch-stable-bionic.list.save' dosyası geçersiz bir dosya uzantısı olduğu için yok sayılıyor
**bla bla**
N: '/etc/apt/sources.list.d/' dizinindeki 'christian-boxdoerfer-ubuntu-fsearch-daily-bionic.list.save' dosyası geçersiz bir dosya uzantısı olduğu için yok sayılıyor
**bla bla**
N: fsearch paketi bulunamadı
N: fsearch paketi bulunamadı
E: Hiç paket bulunamadı

**Comment by selahattinilhan** [comment]
> > What's the output of `apt show fsearch`?
> 
> **Turkish:** N: '/etc/apt/sources.list.d/' dizinindeki 'christian-boxdoerfer-ubuntu-fsearch-stable-bionic.list.save' dosyası geçersiz bir dosya uzantısı olduğu için yok sayılıyor **bla bla** N: '/etc/apt/sources.list.d/' dizinindeki 'christian-boxdoerfer-ubuntu-fsearch-daily-bionic.list.save' dosyası geçersiz bir dosya uzantısı olduğu için yok sayılıyor **bla bla** N: fsearch paketi bulunamadı N: fsearch paketi bulunamadı E: Hiç paket bulunamadı

Currently installed, working. I downloaded it from the Ubuntu store.
