### ISSUE TITLE
Distinct search locations, selectable on the fly

### ISSUE THREAD

**Issue by paul1149** [cboxdoerfer/fsearch#343]
Frequently when I do a search I pull up a ton of unwanted hits, either from the root hierarchy or from secondary drives where I keep backups and storage. Sometimes I want to search those locations, but often I'm looking for something in the /home folders.

So this morning when I did such a search, which pulled up more unwanted hits than anything, I decided to go into preferences and deselect the secondary database locations for the purposes of the search. To my surprise, FSearch began reindexing the database when I clicked OK. Apparently I now have lost the indexing already done in the remote locations.

What I would like to see is the ability to select distinct database search locations on the fly, without triggering a DB indexing. It could be a drop-down box near the current 'search by type' drop-down. Or, less helpfully, it could be accessible via menu. But however it is done, it would be extremely helpful to be able to select search locations on the fly.

I'm on FS .01 on MX Linux.

Thank you.

**Comment by cboxdoerfer** [comment]
> What I would like to see is the ability to select distinct database search locations on the fly, without triggering a DB indexing.

This will be possible with the 0.2 update. Then you can simply add a custom filter to limit your searches to certain paths and their subfolders.

**Comment by paul1149** [comment]
Excellent. Thanks much.

**Comment by cboxdoerfer** [comment]
The custom filter feature is now ready on the development branch.

To give you an idea how it currently works, if your curious enough to try the development versions:

In `Preferences -> Search -> Filter` you can now find the list of all filters, which now can be edited. For example you can create a new filter with the following properties:

* Name: `Backup (External HDD1)`
* Macro: `exbackup1`
* Search in path: Yes
* Match case: Yes
* Enable regular expressions: Yes
* Query: `^/path/to/hdd1/mount_point`

This new filter will then be accessible from the filter drop down next to the search query. You can also use the 'Macro' field to activate the filter on demand from the search entry by typing the macro value followed by an `:`. For example in this case you can type `exbackup1:*.mp4` to list all mp4 files within the mount point of this external drive.

**Comment by Golddouble** [comment]
Great!

**Comment by paul1149** [comment]
Hello,
I finally got version .2.2 installed, and this is working beautifully. It will save a lot of effort focusing in on the searches.

I left Macro empty, and selected Search in Path. Not sure what the do, but it seems to be working fine.

The drop-down selection box has a truncated length under the linux KDE desktop, and the entries have to be fished out from "off-screen". Not a big problem.

Thanks much - great improvement, great prog!
