### ISSUE TITLE
[BUG] respect upper and lower case

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#346]
**Describe the bug**
When I am searching for the phrase "Genymobile" with the option "all" and when I have not activated "Beachte Gross- und Kleinschreibung", nevertheless it shows me only folders with "Grossschreibung" and no files with "Kleinschreibung".

**To Reproduce**
Gif-Animation:
![Fsearch upper lower case](https://user-images.githubusercontent.com/13977359/161426833-af123af5-0eb8-4806-9a7e-759044c821c6.gif)

**Expected behavior**
Regardless of whether I search for "Genymobile" or "genymobile", I would expect the same search result. But there are different search results.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]: MX-Linux 19.4
 - How you installed FSearch [e.g. built manually, PPA, AUR]: MX package Installer
 - Version [output of `fsearch --version`]: 0.1
 - Output of `localectl status`: $ localectl status
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Der Rechner ist nicht aktiv

**Comment by cboxdoerfer** [comment]
Do you have "Auto match case" enabled? It's in `Preferences -> Search`. That's likely the reason for that behavior. It basically means that the search will automatically match the case of the whole word when at least one character is upper case.

**Comment by Golddouble** [comment]
Oh yes. This was enabled. 
Sorry for the inconvenience.
Works now as expected.

The programme is too good for me. :-)
