### ISSUE TITLE
[BUG] Fsearch not compatible with Ubuntu 21.10

### ISSUE THREAD

**Issue by flickleafy** [cboxdoerfer/fsearch#347]
**Describe the bug**
Fsearch does not open at all.

**To Reproduce**
1. Click on Feach icon

**Expected behavior**
Open and show the main screen

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - How you installed FSearch: From Snap
 - Version: 0.1.2

The first time I got the problem, I tried to install from PPA, and looks like one package Fsearch uses, is obsolete in Ubuntu 21.10.

**Comment by cboxdoerfer** [comment]
What's the output when you run `/snap/bin/fsearch` from the terminal?

**Comment by cboxdoerfer** [comment]
I also just installed Ubuntu 21.10, but I can't reproduce the issues. Both the Snap installed from the Ubuntu Software Center and the versions from the PPA (both stable and development builds) work as expected.

**Comment by flickleafy** [comment]
When installed from the PPA, this is the output: 

`Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 fsearch : Depends: libicu66 (>= 66.1-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.
`
And the output from the one from Snap is this...

`(fsearch:305347): dbind-WARNING **: 20:40:40.018: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-701b2bEwMT: No such file or directory

(fsearch:305347): Gtk-WARNING **: 20:40:40.047: Theme parsing error: gtk.css:1428:23: 'font-feature-settings' is not a valid property name

(fsearch:305347): Gtk-WARNING **: 20:40:40.050: Theme parsing error: gtk.css:3318:25: 'font-feature-settings' is not a valid property name

(fsearch:305347): Gtk-WARNING **: 20:40:40.051: Theme parsing error: gtk.css:3780:23: 'font-feature-settings' is not a valid property name

(fsearch:305347): Gtk-WARNING **: 20:40:40.178: Theme parsing error: gtk.css:1428:23: 'font-feature-settings' is not a valid property name

(fsearch:305347): Gtk-WARNING **: 20:40:40.180: Theme parsing error: gtk.css:3318:25: 'font-feature-settings' is not a valid property name

(fsearch:305347): Gtk-WARNING **: 20:40:40.180: Theme parsing error: gtk.css:3780:23: 'font-feature-settings' is not a valid property name
activate fsearch
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/30-metric-aliases.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/30-metric-aliases.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/40-nonlatin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/40-nonlatin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/45-generic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/45-generic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/45-generic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/45-generic.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/45-latin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/45-latin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/45-latin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/45-latin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/50-user.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/50-user.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/50-user.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/50-user.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/51-local.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/51-local.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/51-local.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/51-local.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/60-generic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/60-generic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/60-generic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/60-generic.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/60-latin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/60-latin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/60-latin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/60-latin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 34: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/65-fonts-persian.conf", line 36: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/65-fonts-persian.conf", line 36: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/65-nonlatin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/65-nonlatin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/69-unifont.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/69-unifont.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/69-unifont.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/69-unifont.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
Segmentation fault (core dumped)`

**Comment by cboxdoerfer** [comment]
Ok, the PPA isn't working because for some reason you're using the FSearch package which was built for Ubuntu 20.04. So I suppose you upgraded from 20.04 and for some reason kept the old PPA and FSearch package. As far as I know Ubuntu always disables PPAs before upgrading the system and the user is then responsible for updating/re-enabling the PPAs. Did you do that?

Regarding the Snap version it, crashes for some reason. Can you post the output of `env G_MESSAGES_DEBUG=all /snap/bin/fsearch` (you can ignore all the Fontconfig warnings)?

**Comment by flickleafy** [comment]
For some reason, the links in the repository was not disabled during the upgrade from 20.04 to 21.10, then, as you told me, I fixed that removing all the repositories, and adding back in the proper maner, using "add-apt-repository".

In the end, I was able to install it from the PPA, and it worked as expected. 

Thanks.

**Comment by cboxdoerfer** [comment]
Thanks, can you still try to run the snap build which crashes with `env G_MESSAGES_DEBUG=all /snap/bin/fsearch` ? Maybe that's a bug and I'd like to fix it in case others run into it.

**Comment by flickleafy** [comment]
Here... but, unfortunately, it seems it is working now...
I had removed the other snap installation to re-install from the correct PPA, and now that I re-installed from snap, looks like it solved the problem it had.

(fsearch:1475445): dbind-WARNING **: 02:28:13.623: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-distBCiRKR: No such file or directory

(fsearch:1475445): Gtk-WARNING **: 02:28:13.638: Theme parsing error: gtk.css:1428:23: 'font-feature-settings' is not a valid property name

(fsearch:1475445): Gtk-WARNING **: 02:28:13.640: Theme parsing error: gtk.css:3318:25: 'font-feature-settings' is not a valid property name

(fsearch:1475445): Gtk-WARNING **: 02:28:13.640: Theme parsing error: gtk.css:3780:23: 'font-feature-settings' is not a valid property name
(fsearch:1475445): Gtk-DEBUG: 02:28:13.708: Connecting to session manager
(fsearch:1475445): fsearch-config-DEBUG: 02:28:13.709: [config] loading failed (0,004000 ms)

(fsearch:1475445): Gtk-WARNING **: 02:28:13.711: Theme parsing error: gtk.css:1428:23: 'font-feature-settings' is not a valid property name

(fsearch:1475445): Gtk-WARNING **: 02:28:13.713: Theme parsing error: gtk.css:3318:25: 'font-feature-settings' is not a valid property name

(fsearch:1475445): Gtk-WARNING **: 02:28:13.713: Theme parsing error: gtk.css:3780:23: 'font-feature-settings' is not a valid property name
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
(fsearch:1475445): fsearch-application-DEBUG: 02:28:14.553: [app] disabled action: update_database
(fsearch:1475445): fsearch-application-DEBUG: 02:28:14.553: [app] enabled action: cancel_update_database
(fsearch:1475445): fsearch-application-DEBUG: 02:28:14.553: [app] disabled action: update_database
(fsearch:1475445): fsearch-application-DEBUG: 02:28:14.553: [app] enabled action: cancel_update_database
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.554: [db_file] can't open database file: /home/xxx/snap/fsearch/14/.local/share/fsearch/fsearch.db
(fsearch:1475445): fsearch-application-DEBUG: 02:28:14.554: [app] database update finished in 0,83 ms
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.554: [db_scan] scan path: /home/xxx/snap/fsearch/14
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.554: [db_ref] increased to: 2
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.554: [db_ref] increased to: 3
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.554: [db_ref] increased to: 4
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.554: [db_unref] dropped to: 3
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_ref] increased to: 5
(fsearch:1475445): fsearch-search-DEBUG: 02:28:14.555: [query:00.0000] finished in 0,10 ms
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_ref] increased to: 5
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_unref] dropped to: 4
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_unref] dropped to: 3
(fsearch:1475445): fsearch-database-view-DEBUG: 02:28:14.555: [sort] started: 0
(fsearch:1475445): fsearch-database-view-DEBUG: 02:28:14.555: [sort] finished in  0ms
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_scan] scanned: 13 files, 14 folders -> 27 total
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_sort] sorted files: 0,000016 s
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_sort] sorted folders: 0,000017 s
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] saving database to file...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] trying to open temporary database file: /home/xxx/snap/fsearch/14/.local/share/fsearch/fsearch.db.tmp
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] updating folder indices...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] saving database header...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] saving database index flags...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] saving number of folders: 14
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] saving number of files: 13
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] saving folder block size...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] saving file block size...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] saving indices...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] saving excludes...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] saving exclude pattern...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] saving folders...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] saving files...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] saving sorted arrays...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] updating file and folder block size: 430, 397
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] removing current database file...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] renaming temporary database file: /home/xxx/snap/fsearch/14/.local/share/fsearch/fsearch.db.tmp -> /home/xxx/snap/fsearch/14/.local/share/fsearch/fsearch.db
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_save] database file saved in: 0,205000 ms
(fsearch:1475445): fsearch-application-DEBUG: 02:28:14.555: [app] database update finished in 1,19 ms
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.555: [db_unref] dropped to: 2
(fsearch:1475445): fsearch-application-DEBUG: 02:28:14.555: [app] enabled action: update_database
(fsearch:1475445): fsearch-application-DEBUG: 02:28:14.555: [app] disabled action: cancel_update_database
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.563: [db_ref] increased to: 2
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.563: [db_unref] dropped to: 1
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.563: [db_ref] increased to: 3
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.563: [db_ref] increased to: 4
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.563: [db_unref] dropped to: 3
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.563: [db_ref] increased to: 5
(fsearch:1475445): fsearch-search-DEBUG: 02:28:14.563: [query:00.0001] finished in 0,01 ms
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.563: [db_unref] dropped to: 0
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.563: [db_free] freeing...
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.564: [db_free] freed
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.564: [db_ref] increased to: 5
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.564: [db_unref] dropped to: 4
(fsearch:1475445): fsearch-database-DEBUG: 02:28:14.564: [db_unref] dropped to: 3
(fsearch:1475445): fsearch-database-view-DEBUG: 02:28:14.564: [sort] finished in  0ms

**Comment by cboxdoerfer** [comment]
> Here... but, unfortunately, it seems it is working now...

Too bad, but thank you anyway!
