### ISSUE TITLE
Delete confirmation and update listed files

### ISSUE THREAD

**Issue by flickleafy** [cboxdoerfer/fsearch#348]
**Is your feature request related to a problem? Please describe.**
Yes, when I delete files I selected in the listed files, there is no confirmation dialog that the files was deleted properly, then, the list is not updated as well, even when I confirmed that the files I "deleted" are in the trash.

It is quite annoying to have to look to the trash to see what was deleted. Or, to have to click to the button "Update Database", to be sure what that is listed is really there in the folders.

**Describe the solution you'd like**
First, when I click delete, it should pop up a dialog to confirm that the files are going to be deleted.
Second, if the files was deleted properly, then, update the files listed, removing the files that was deleted.

**Comment by cboxdoerfer** [comment]
There's now a confirmation dialog when a file was moved to the trash (or a warning dialog if the operation failed).

The issue that the result list isn't updated properly after a successful delete is tracked by #64 so I think we can close this issue now.
