### ISSUE TITLE
Add wild card/regex folder include/exclude

### ISSUE THREAD

**Issue by hmmftg** [cboxdoerfer/fsearch#351]
Hi
Indexing **node_modules** and it's alike folders is always a pain
The include/exclude menu is great, but it does not accept something like this:

     *\node_modules\*
     *\.history\*

these folders are not needed in search results

**Comment by phil294** [comment]
You can simply write e.g.

    .git;node_modules;dist

into Preferences > Database > Exclude > Exclude files and it should work as desired

**Comment by hmmftg** [comment]
thanks
it's great 
my mistake
