### ISSUE TITLE
[BUG] Install instructions don't work - "Neither directory contains a build file meson.build."

### ISSUE THREAD

**Issue by yllekz** [cboxdoerfer/fsearch#352]
**Describe the bug**
I'm following the build/compile/install instructions verbatim and they do not work. The commands are running in the wrong directories.

**To Reproduce**
https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions
After running meson compile I get ``ERROR: Neither directory contains a build file meson.build.``

**Expected behavior**
Compiles/installs

I got it working after playing around. Here's the updated instructions required:
```
sudo apt-get update
sudo apt install git build-essential meson libtool pkg-config intltool libicu-dev libpcre3-dev libglib2.0-dev libgtk-3-dev libxml2-utils
git clone https://github.com/cboxdoerfer/fsearch.git ~/Downloads/fsearch
cd fsearch
meson builddir
meson compile && cd builddir
meson install
```

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04] Linux Mint 20.3 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - How you installed FSearch [e.g. built manually, PPA, AUR] built manually
 - Version [output of `fsearch --version`] n/a
 - Output of `localectl status`   System Locale: LANG=en_US.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105

**Comment by cboxdoerfer** [comment]
Thanks for the report. The issue is with the `meson compile` command. The `command` flag is only supported by `meson >=0.54`, but your distributions ships an older meson version.

I've updated the build instructions to support older meson versions.
