### ISSUE TITLE
How to use "NOT" / !

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#362]
How should I use "NOT" ?

From your help:
![k20220601-103933](https://user-images.githubusercontent.com/13977359/171364012-fc16ecc6-e6c1-4010-90fe-69effefc53f1.jpg)

But this seems not to work:
![k20220601-103931](https://user-images.githubusercontent.com/13977359/171364087-529e4ce4-3117-492a-8b19-bfdd8bfa08f8.jpg)

My expectation was, that the files with exe will no longer be found. But they are there nevertheless.

Thank you.

FSearch version 0.1

**Comment by cboxdoerfer** [comment]
Hi, like the said help page says, those features (`NOT`, `AND`, `OR`) only work with FSearch 0.2 and newer. So if you want to use them right now you need to use the 0.2alpha builds, either by building them yourself or using the nightly PPA, AUR, copr, if they're supported by your distribution.
