### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wdahu2022** [cboxdoerfer/fsearch#367]
Text error in UI. I build Fsearch manually in my OS, and "Edit - Preferences - Database - Include - Update" error , the "Update" is displayed as "One Filesystem"

Desktop :
 - OS: deepinOS
 - How you installed FSearch: built manually
 - Version: all 0.1 , 0.1.2 , 0.1.4
![Fsearch0 1 4](https://user-images.githubusercontent.com/109205142/178689519-d313f745-01b9-40d1-9b41-584bbd583c0a.jpg)

**Comment by cboxdoerfer** [comment]
The "One Filesystem" text is correct, it's a different column with a different meaning. The "Update" column was removed sometime before the 0.1 release, but it will come back in the 0.3 release.
