### ISSUE TITLE
Add Support For Context Menu Key

### ISSUE THREAD

**Issue by bayazidbh** [cboxdoerfer/fsearch#369]
**Is your feature request related to a problem? Please describe.**
When I'm working and in the zone, I prefer to not have to switch between keyboard and mouse. However, the context menu is only accessible through right click and pressing on the [Menu Key](https://en.wikipedia.org/wiki/Menu_key) does nothing.

**Describe the solution you'd like**
Support showing the Context Menu by pressing the Menu Key.

**Comment by cboxdoerfer** [comment]
I agree, the menu key definitely should open the context menu. I'll add that.

**Comment by cboxdoerfer** [comment]
Added.
