### ISSUE TITLE
[BUG] Fails to delete file in NTFS

### ISSUE THREAD

**Issue by flickleafy** [cboxdoerfer/fsearch#371]
**Describe the bug**
Fails to delete files in a NTFS partition.

**To Reproduce**
1. Search a file (should have an hardrive with NTFS partitions included in the configuration)
2. Click on delete button
3. Nothing happens
4. Look at the file in the NTFS partition

**Expected behavior**
The file should be deleted.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - How you installed FSearch: PPA
 - Version: 0.2alpha

**Comment by cboxdoerfer** [comment]
Thx for the report. What happens when you attempt to trash the file with your file manager, without root?

**Comment by flickleafy** [comment]
The normal operation in Ubuntu is to permanently delete a file when it is in a NTFS partition and I hit the delete button, it does not try to create that "trash folder" that is usually present in other kinds of partition.

I does pop-up a dialog telling it is a permanent delete, but dont need to be a root operation.

**Comment by cboxdoerfer** [comment]
This sounds like the system lacks the permissions to properly move the file to the trash (or create a trash directory) on this filesystem. So I guess the bug in FSearch is that it doesn't show an error message about that and that it doesn't hide the trash menu entry for files which can't be moved to the trash.

FSearch currently can't permanently delete files, so this fallback is not available at the moment. But this feature will be added soon.

**Comment by cboxdoerfer** [comment]
> I don't think so, I use some other applications that do interact with this same NTFS partition, and it delete the files normally (sure, it do pop up a warning telling it is a permanent delete, but other applications works as expected).

Moving files to the trash requires different permissions than deleting files.

> About the trash folder in NTFS partition, I am not sure it is supposed to ever create a trash folder there, the same as it does in "native" unix partitions

It will, given the proper permissions. I just tested it and Nautilus and Dolphin allow trashing files on a mounted NTFS filesystem just fine. If not present already, they also create the trash folder at the root of the filesystem when first trash a file.

But like I said, the issue seems to be that FSearch doesn't report the permission error and doesn't hide the trash option if its not available on the current filesystem.

**Comment by flickleafy** [comment]
> It will, given the proper permissions. I just tested it and Nautilus and Dolphin allow trashing files on a mounted NTFS filesystem just fine. If not present already, they also create the trash folder at the root of the filesystem when first trash a file.

Where do you see that permissions?

**Comment by cboxdoerfer** [comment]
> Where do you see that permissions?

Go to the root of the NTFS filesystem and execute `stat .` to see which user is the owner of it (UID) and who's got access to it. Then you can also use something like `findmnt .` to see what mount flags were used to mount this filesystem.

**Comment by flickleafy** [comment]
That was right, the thing was, that partition was mounted with root permissions, so, what I did was change the mounting parameters in fstab, with my user id (this is valid only for FAT and NTFS), this solves the issue with the trash folder.

If you don't mind, I would like to suggest one thing. It would not be bad if there was a dialog telling the file is going to be deleted, and, after deletion (if the file was really deleted), update the search list, removing from the list the files that was deleted. Is that possible?

**Comment by cboxdoerfer** [comment]
> It would not be bad if there was a dialog telling the file is going to be deleted

Yes, that's planed. Right now FSearch can't permanently delete files at all, so such a dialog wouldn't work at the moment, but the 0.3 release will probably add that option.

> after deletion (if the file was really deleted), update the search list, removing from the list the files that was deleted

That'll also be part of the 0.3 release.
