### ISSUE TITLE
[BUG] fsearch-git file association issues

### ISSUE THREAD

**Issue by bayazidbh** [cboxdoerfer/fsearch#375]
**Describe the bug**
FSearch-git does not seem to respect user-set default application, and it seems to use the default default application.

PDF would open with default default browser, .zip files would open with the default file archive (Ark) even when I've set it to be opened by PeaZip (natively installed), and Office files (.docx/.xlsx/.pptx) would be opened Ark (as it's known to incorrectly read them as normal archive by default).

On my Ubuntu 22.04 VM, I tried both fsearch-daily and manually built fsearch from the git repo, it does seem to respect default application if it is installed natively, but not if it's a flatpak.

I set .pdf to be opened by Okular, and it opened just fine. I set .docx to be opened by Document Viewer and it opens Document Viewer (even though it cannot read .docx and doesn't show up in the Recommended App list in Open With menu).

If I set the two filetypes to be opened by a Flatpak app (WPS Office) by default, then both filetype will use the default recommended app.

So while I initially suspected another KDE issue, or a more recent commit to be the issue, it seems to be file association detection in general, as on my Arch-based system I installed fsearch stable and it was able to open with Flatpak apps set as default just fine.

**To Reproduce**
1. Use fsearch-git
2. Double click on the file

**Expected behavior**
Should respect system-set default applications.

**Screenshots**

https://user-images.githubusercontent.com/26621899/183272469-7c1999b8-f21e-4d44-95e4-448a31b18d08.mp4

<details><summary>Desktop</summary><p>

```
OS: Garuda Linux
Host: ASRock A320M-HDV R4.0
Kernel: 5.18.15-265-tkg-pds
Uptime: 57 mins
Packages: 2412 (pacman), 51 (flatpak)
Shell: zsh
DE: Plasma 5.25.4
WM: KWin
Terminal: konsole
CPU: AMD Ryzen 5 3400G (8) @ 3.7GHz
GPU: AMD ATI Red Dragon
```

```
$ fsearch --version
FSearch 0.2alpha (AUR-devel)

$ localectl status
System Locale: LANG=en_US.UTF-8
LC_NUMERIC=en_SG.UTF-8
LC_TIME=en_SG.UTF-8
LC_MONETARY=en_SG.UTF-8
LC_PAPER=en_SG.UTF-8
LC_NAME=en_SG.UTF-8
LC_ADDRESS=en_SG.UTF-8
LC_TELEPHONE=en_SG.UTF-8
LC_MEASUREMENT=en_SG.UTF-8
LC_IDENTIFICATION=en_SG.UTF-8
VC Keymap: us
X11 Layout: us
```

```
Name                  : fsearch-git
Version               : 0.2alpha.r405.g67bdfb7-1
Description           : A fast graphical file search utility. Development version.
URL                   : https://cboxdoerfer.github.io/fsearch
Licenses              : GPL2
Repository            : chaotic-aur
Installed Size        : 985.4 kB
Groups                : --
Depends On            : gtk3 icu pcre2
Optional Dependencies : --
Required By           : --
Optional For          : --
Provides              : --
Replaces              : --
Conflicts With        : fsearch
Packager              : UFSCar HPC Builder <hpc.ufscar@chaotic.cx>
Build Date            : Sun 07 Aug 2022 12:14:42 AM
Install Date          : Sun 07 Aug 2022 09:02:08 AM
Install Reason        : Explicitly installed
Validated By          : Signature
Backup files          : --
```

</p></details>

**Additional context**
Bug appears on a manually-built AUR install on Manjaro as well. I have confirmed that this behavior does not appear on the fsearch stable version, from AUR. Let me know if you need more info.

Edit: Potentially related to Issue #353?

**Comment by cboxdoerfer** [comment]
Thx for the detailed report. I'll look into it.

**Comment by cboxdoerfer** [comment]
@bayazidbh, I think I've found and fixed the issue. Can you rebuild the `fsearch-git` package and verify if it works correctly now?

**Comment by bayazidbh** [comment]
@cboxdoerfer Confirmed fixed on both my Arch-based KDE system and Ubuntu 22.04 VM, thanks!

**Comment by cboxdoerfer** [comment]
Nice, thanks for the feedback.
