### ISSUE TITLE
Any way of accessing .db file outside fsearch?

### ISSUE THREAD

**Issue by mez0ru** [cboxdoerfer/fsearch#376]
I have a hard drive which does hosts my files, however by unforeseen circumstances, the hard drive got wiped/formatted.
However I don't currently have fsearch sat up in my new system, but I have a backup of my .local files which has the fsearch.db file.
I want to access it but I can't find the right format which would let me access my file names, so that I know which files I have lost.
Thanks.

**Comment by TechLifeCorp** [comment]
this tool is great, would it be possible to extract the data because I wanted to write an api that will help me analyse our files and their location. When I found the db file it appears to be protected. Any help would be greatly appreciated.
