### ISSUE TITLE
[BUG] FSearch not opening files in Default Text Editor (Geany)

### ISSUE THREAD

**Issue by kajodowe** [cboxdoerfer/fsearch#377]
**Describe the bug**
Prior to approximately 2 weeks ago, FSearch would always open text files in my chosen default text editor (Geany). But lately when I click on a file in FSearch it opens in XED. If I click on the same file in Nemo it properly opens in Geany. 

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 Cinnamon
 - How you installed FSearch: Manually
 - Version [output of `fsearch --version`]
         0.2alpha (PPA-nightly)
 - Output of `localectl status:
       System Locale: LANG=en_US.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105

**Comment by cboxdoerfer** [comment]
Thx for the report. This should already be fixed. Do you have the latest version from the PPA installed?

**Comment by kajodowe** [comment]
I believe I have the latest version -- here is the installed version as shown in Synaptic: 20220808+r1924.dff9c8c~ubuntu20.04.1.

**Comment by cboxdoerfer** [comment]
That is weird, I can't reproduce the issue with this version on Ubuntu and Mint. What's the output of `xdg-mime query default text/plain` and `apt list fsearch`?

**Comment by kajodowe** [comment]
Hi Christian -- thanks for your assistance. The output of 'xdg-mime query default text/plain' is 'geany.desktop.'

The output of 'apt list fsearch' is as follows:
      fsearch/focal,now 20220808+r1924.dff9c8c~ubuntu20.04.1 amd64 [installed]
      N: There is 1 additional version. Please use the '-a' switch to see it

**Comment by cboxdoerfer** [comment]
> Hi Christian -- thanks for your assistance. The output of 'xdg-mime query default text/plain' is 'geany.desktop.'
> 
> The output of 'apt list fsearch' is as follows: fsearch/focal,now 20220808+r1924.dff9c8c~ubuntu20.04.1 amd64 [installed] N: There is 1 additional version. Please use the '-a' switch to see it

No problem. This looks all fine. Can you also post the output of `whereis fsearch` and (while FSearch is running) `ps aux | grep fsearch`? Just to make sure that there's no other FSearch binary which accidentally gets used. Also can you try if this issue happens with other file types as well? Like when you change the default mp3 player and open an mp3 with FSearch and your file manager.

I will probably prepare a build with some added debug output for the daily PPA, which then hopefully helps us identifying the cause of this issue. Because right now I'm out of ideas what might be going wrong.

**Comment by cboxdoerfer** [comment]
I've just added some debug output. The updated build on the PPA should be ready within the next 24 hours.

Once you've got the update you can run FSearch with the following command `env G_MESSAGES_DEBUG=fsearch-utils fsearch`

Then when you open a file you should see something like this on the command line:

```
(fsearch_scratchpad:16061): fsearch-utils-DEBUG: 10:43:48.493: [open] opening file/folder:
uri: "file:///tmp/testimg.jpg"
content type: "image/jpeg"
application: "Image Viewer"
cmd: "eog %U"
```

Maybe this information will then give a hint what might be going wrong.

**Comment by kajodowe** [comment]
Hi Christian -- here is the output for 'whereis fsearch' -- fsearch: /usr/bin/fsearch /usr/share/man/man1/fsearch.1.gz

And here is out put for 'ps aux | grep fsearch':
allen     129305  0.0  0.6 1054664 55084 ?       Sl   05:26   0:01 fsearch
allen     130569  0.0  0.0   9032  2652 pts/1    S+   05:51   0:00 grep --color=auto search

I am in the U.S. and it's 550 am on Friday as I type this. I read your most recent comment about 40 minutes ago and tested the issue again. Now FSearch works normally -- when I click on a text file it opens in Geany! The only thing I can think of that might contribute to this is that I rebooted my computer again after a power glitch a couple of days ago. 

I will still send the debut output from your most recent reply. Thanks very much for your help.

**Comment by kajodowe** [comment]
Thanks for all your help Christian. I'm glad to see you put the Sponsor link here. I sent you a donation! I use search probably 20-30 times a day. The Everything app was the main thing I missed from Windows and your FSearch is every bit as good!

**Comment by cboxdoerfer** [comment]
Thank you! I really appreciate that :)

**Comment by kajodowe** [comment]
Hi Christian -- I executed from terminal the command you suggested (env G_MESSAGES_DEBUG=fsearch-utils fsearch). This was the output:
(fsearch:336215): Gtk-WARNING **: 07:01:04.336: Theme parsing error: gtk.css:3:0: expected '{' after selectors
activate fsearch
(fsearch:336215): fsearch-database-WARNING **: 07:01:04.738: [db_scan] walk error: 1

**Comment by cboxdoerfer** [comment]
Thx! Can you also open a file while running FSearch with this debug output? It should then print something like:

```
uri: "file:///tmp/testimg.jpg"
content type: "image/jpeg"
application: "Image Viewer"
cmd: "eog %U"
```

**Comment by kajodowe** [comment]
Hi again Christian -- here was the output from that:
(fsearch:353606): fsearch-utils-DEBUG: 14:01:49.841: [open] opening file/folder:
uri: "file:///home/allen/Desktop/unnamed.txt"
content type: "text/plain"
application: "Geany"
cmd: "geany %F"

(geany:353624): Gtk-WARNING **: 14:01:49.879: Theme parsing error: gtk.css:3:0: expected '{' after selectors

**Comment by cboxdoerfer** [comment]
@kajodowe Thank you! Yes, this looks good. So it was probably caused by an older FSearch instance running and the restart fixed that by launching the updated version.

So I guess we can consider this issue as resolved. If this or a similar issue ever pops up again, just let me know!

**Comment by mutageneral** [comment]
I have the same exact problem on the latest version. I am using the Open Build Service RPM version on OpenSUSE Tumbleweed. Exact version is `FSearch 0.2.2 (OBS-rpm-stable)` I updated my system yesterday. zypper says its version `0.2.2-3.22`

Output of `xdg-mime query default text/plain` is `org.kde.kate.desktop` witch is Kate, my favourite text editor.

I clicked on a text file in fsearch, and it opened in the WINE notepad clone. Probably the worse text editor in existence, lol.

I then killed fsearch and tried again and same result:

```
me@OpenSUSE:~> killall fsearch 
me@OpenSUSE:~> fsearch 

(fsearch:1017): dbind-WARNING **: 23:45:51.716: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Failed to load cookie file from cookie: Permission non accordée
002c:fixme:winediag:LdrInitializeThunk wine-staging 8.12 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0120:fixme:exec:SHELL_execute flags ignored: 0x00000100
```
Most of this is WINE stuff.

**Comment by cboxdoerfer** [comment]
`xdg-mime` is a script which uses the KDE utilities to query the default applications behind the scenes. However the way KDE configures its default apps isn't fully compliant with the freedesktop specification.

The easiest way to set the default app in a freedesktop compliant way is by using the `gio` utility. For example to set Kate as the default editor for plain text files you can execute:

`gio mime text/plain org.kde.kate.desktop`

and to query the default app for a certain file type run:

`gio mime text/plain`

I hope that helps.

**Comment by mutageneral** [comment]
Thank you a lot! Everything works now and I learn something new today :)

Thank you so much for FSearch and have a great day :)
