### ISSUE TITLE
[BUG] search operators seem not to work

### ISSUE THREAD

**Issue by cristianrz** [cboxdoerfer/fsearch#379]
**Describe the bug**

I have installed both the ubuntu version and the flatpak version and search operators seem not to work. I am sure I am doing something wrong but I don't know what.

**To Reproduce**
1. search for `pdf`, files appear
2. search for `odt`, files appear
3. search for `pdf OR odt`, nothing appears
4. search for `pdf || odt`, nothing appears

**Expected behavior**
`pdf OR odt` shows files that include pdf and files that include odt in their name

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - How you installed FSearch: ppa and flatpak
 - Version: 0.1.4
 - Output of `localectl status`

```
   System Locale: LANG=en_GB.UTF-8
                  LANGUAGE=en_GB:en
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105
```

**Comment by cboxdoerfer** [comment]
Thx for the report. You're doing nothing, those search operators just require FSearch 0.2 to work, which will be released in a couple of days -- if no major issues arises.

If you want to try them out immediately you need to use the daily PPA with the development builds.

**Comment by cristianrz** [comment]
damn I was scratching my head for a while trying all sorts of combinations, thanks!
