### ISSUE TITLE
Don't separate files/folders in the search

### ISSUE THREAD

**Issue by awsms** [cboxdoerfer/fsearch#382]
**Is your feature request related to a problem? Please describe.**
I would like to see both big files and folders at the same time, and it's not possible yet since the size order is inverted for files & folders. It's either big files/small folders first, or the other way around, and both formats are separated.

for ex, instead of
```
├──file 1 (2GB)
├──file 2 (1GB)
├──file 3 (500MB) etc
├──folder 1 (1.5GB)
├──folder 2 (5GB)
└── ...
```
```
├──folder 1 (5GB)
├──file 1 (2GB)
├──folder 2 (1.5GB)
├──file 2 (1GB) etc
└── ...
```
**Describe the solution you'd like**
Adding a "Don't separate folders and files in search results" togglebox in settings

**Describe alternatives you've considered**
ncdu

**Comment by awsms** [comment]
Sorry, I've already searched in the issues but didn't find it!

**Comment by cboxdoerfer** [comment]
No problem.
