### ISSUE TITLE
[BUG] diacritics sensitivity

### ISSUE THREAD

**Issue by slrslr** [cboxdoerfer/fsearch#385]
I think that the Fsearch has a problem where it does not find file if the difference between searched phrase and file/folder name is only diacritics (kód/kod or kýl/kyl).
It is casual that some people name files with diacritics and some without it. You always end up with files of other people that are name one or another way.
But it seems stupid to always search two times. I think that the app should return diacritics matches in search results even i do not use diacritic above the letters when searching.
And vice versa - searching without diacritics, return also matches with diacritics.

1. run Fsearch
2. search for "Zdrojový Kód"
3. The file indexed and containing the phrase "Zdrojový Kod" (difference is in o/ó) will not be found
y/ý also does not work, likely [other diacritics](https://www.ecosia.org/search?q=diacritics+letters) too.
Opposite case (searching without diacritics) for existing file that has diacritics also does not return anything.

**Expected behavior**
Search should be case and diacritics insensitive by default.
People will not accidentally miss files and does not need to learn to search twice (i am using the app for 1 year and discovered it now, wondering how many files i have missed due to this), wasting time searching 2 times every time i need to find the file.

**Desktop:**
 - OS: Debian
 - How you installed FSearch: I do not know
 - Version FSearch 0.1.339-9f4c
 - Output of `localectl status` [here](https://bin.disroot.org/?d03aa866c0470464#HiV1Ra3kDgaRRmaYXDk8oq9tQspsoBQZobzaGa2xwNgw)

Thank you

**Comment by cboxdoerfer** [comment]
Thanks for the report! This feature was already requested in #303. So adding support for insensitive diacritic search is something I'd definitely want to have, but I still haven't looked at the details on how to implement that in a performant way. For further discussion please use #303.
