### ISSUE TITLE
[BUG] Disabling "Show highlighted search terms" doesn't seem to work

### ISSUE THREAD

**Issue by lepa22** [cboxdoerfer/fsearch#386]
**Describe the bug**
Disabling *Show highlighted search terms* doesn't seem to work. Search terms are still highlighted with bold fonts.

**To Reproduce**
1. Go to <kbd>&equiv;</kbd> &rarr; *Preferences*.
2. Uncheck *Show highlighted search terms*.
3. This doesn't have any effect and search terms are still highlighted.
4. Search terms are highlighted even after restarting FSearch.

**Expected behavior**
Search terms are not highlighted.

**Desktop**
 - OS: Fedora 36
 - How you installed FSearch: from https://copr.fedorainfracloud.org/coprs/cboxdoerfer/fsearch_nightly/
 - Version: `FSearch 0.2 (copr-nightly)`
 - Output of `localectl status`:
 
   ```   
   System Locale: LANG=en_US.UTF-8
                     LC_NUMERIC=el_GR.UTF-8
                     LC_TIME=el_GR.UTF-8
                     LC_MONETARY=el_GR.UTF-8
                     LC_PAPER=el_GR.UTF-8
                     LC_MEASUREMENT=el_GR.UTF-8
          VC Keymap: us
         X11 Layout: us,gr
        X11 Variant: ,
        X11 Options: grp:win_space_toggle
   ```

**Comment by cboxdoerfer** [comment]
Thank you for the report! This has been fixed. I'm probably going to release a bug fix release (0.2.1) in the next week or two with this fix — I want to wait a bit in case more bugs get caught after the 0.2 release.
