### ISSUE TITLE
[BUG] Segfault with the size filter

### ISSUE THREAD

**Issue by KatieFrogs** [cboxdoerfer/fsearch#388]
**Describe the bug**
Using the size filter with a range, like `size:1kb..3kb`, crashes fsearch

**To Reproduce**
1. `fsearch -s size:1kb..3kb`

**Expected behavior**
As a workaround, the following query can be used instead to get the expected result: `size:>1kb size:<3kb`

**Desktop**
 - OS: Ubuntu 22.04
 - From fsearch-stable PPA (jammy)
 - Version: FSearch 0.2 (PPA-stable)
 - Version in apt: 0.2-0\~202208171318\~ubuntu22.04.1

**Crash log**
```
activate fsearch

(fsearch:23500): IBUS-WARNING **: 18:34:07.410: Unable to connect to ibus: The given address is empty
**
ERROR:../src/fsearch_size_utils.c:9:fsearch_size_parse: assertion failed: (size_out)
Bail out! ERROR:../src/fsearch_size_utils.c:9:fsearch_size_parse: assertion failed: (size_out)
Segmentation fault (core dumped)
```

**Comment by cboxdoerfer** [comment]
Thanks for the report! I can confirm that, nice catch! I'm working on a fix.

**Comment by cboxdoerfer** [comment]
Fixed. Since this is a pretty bad bug, I'll probably release a 0.2.1 bug fix release within the next 24hours. Thx again for reporting.
