### ISSUE TITLE
Option to check/uncheck paths in database

### ISSUE THREAD

**Issue by spsf64** [cboxdoerfer/fsearch#39]
Sometimes I just want to search only one path/directory (screenshot)
Can you implement an option with checkmarks just to disable/enable a path instead of removing/adding it every time I want to change my options?
TIA

![screenshot from 2016-11-08 10-03-55](https://cloud.githubusercontent.com/assets/1877391/20098396/b9e9a494-a59a-11e6-84f6-b2ff9f8f3a26.png)

**Comment by cboxdoerfer** [comment]
That's already planed for version 0.2 and can be achieved then with the custom query syntax and custom filters. It'll work something like that:

- you create a new custom filter with the query `parent:$DIRECTORY` and give the filter a name, e.g. _Home Folder_
- then you'll be able to select the new filter in the combo box right next to the query field, which currently only contains (All, Files, Folders)
