### ISSUE TITLE
Install on Debian 10 (Buster) don't work

### ISSUE THREAD

**Issue by apapapapapapap** [cboxdoerfer/fsearch#390]
Followed the build instructions (https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions).

command 'meson builddir' gives:
src/meson.build:56:0: ERROR:  Dependency "libpcre2-8" not found, tried pkgconfig and cmake

Tried to install 'libpcre2-8'. 
But 'libpcre2-8' isn't available in debian packages, only 'libpcre2-8-0'

**Comment by cboxdoerfer** [comment]
Did you install `libpcre2-8-0` and tried it again?

**Comment by cboxdoerfer** [comment]
Also you need `libpcre2-dev`. I'll update the build instructions.

**Comment by apapapapapapap** [comment]
Installed libpcre2-dev.

It's working now.

Thx for the fast help.

**Comment by apapapapapapap** [comment]
Installed libpcre2-dev.

It's working now.

Thx for the fast help.

**Comment by cboxdoerfer** [comment]
Great! The build instructions have been updated.
