### ISSUE TITLE
ext:vsdx

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#395]
In ...
Einstellungen -> Suche -> Dokumente
... gibt es den Eintrag `ext:vsd`

Sollte dort nicht auch noch das neuere Format `ext:vsdx` für "MS Visio" drinstehen?

(Bei den anderen Office Programmen sind die neueren Formate jedenfalls dabei: 
doc,dox xls,xlsx, usw. )

(Natürlich habe ich es bei mir selber noch hinzugefügt. Dies soll nur ein Hinweis für die Standardeinstellung sein.)

**Comment by cboxdoerfer** [comment]
Ja, die Liste ist mit Sicherheit nicht vollständig. Ist jetzt aber im Standardfilter enthalten. Falls dir noch andere fehlende Dateiendungen auffallen, einfach bescheid sagen. Danke!

**Comment by Golddouble** [comment]
> Falls dir noch andere fehlende Dateiendungen auffallen, einfach bescheid sagen.

*.svg für Bilder vielleicht.
Ich habe *.svg bei mir jedenfalls dazu genommen.

(Wird verwendet für Skalierbare Bilder und Symbole/Icons.)

**Comment by Golddouble** [comment]
> Falls dir noch andere fehlende Dateiendungen auffallen, einfach bescheid sagen. Danke!

*.md für Markdown files.

Ich habe standardmässig in meinem System eine ganze Reihe von *.md files.
