### ISSUE TITLE
busy mouse pointer

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#398]
**Describe the bug**
FSearch supports the possibility for double clicking on a folder and then thunar opens with the content of that folder.
-> When I use this function I have a "busy mouse pointer" for about half a minute.
When I remember correctly: This was not an issue with FSearch 0.1 

**To Reproduce**
Gif-Animaion:
![Fsearch](https://user-images.githubusercontent.com/13977359/186845015-2050f8a1-9136-4e3f-b04a-0286fce18a7a.gif)

**Expected behavior**
The mouse pointer is busy for about half a second or less.

**Desktop (please complete the following information):**
 - OS:MX-Linux 19.4 Xfce (Debian 10 based)
 - How you installed FSearch MX package installer
 - Version 0.2.2
 - Output of `localectl status`:
 System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Der Rechner ist nicht aktiv

**Comment by cboxdoerfer** [comment]
I can't reproduce this on my system (Fedora, GNOME), but I'll try MX Linux in a VM this weekend.

I'm not a hundred percent sure about how the system implements the busy cursor, but I afaik it uses the `StartupNotify` entry in the applications desktop file. So maybe Thunar doesn't support those notifications (so never sends a startup finished notification) but the flag is set in desktop entry in your distro.

**Comment by Golddouble** [comment]
Since you said that this does not occur in your system, I have now done the following:
Shut down the PC and restarted it.
Now the problem no longer occurs.

**Comment by Golddouble** [comment]
OK I had this issue again.

**How to reproduce:**
0. Boot the PC
1. open FSearch
2. type into the search field *
3. choose picture filter
4. double click on a folder in the folder Column to open the folder 
5. Result: All is as expected. No busy mouse pointer
6. go back to the FSearch window
7. repeat 4) but with another folder in the folder Column
8. the mouse pointer is busy now. (Maybe you need to repeate step 4) more than one)

**Comment by cboxdoerfer** [comment]
Thx for the information, I'll try to reproduce it. Can you also show the output of the following command:

 `grep folder_open_cmd  ~/.config/fsearch/fsearch.conf`

**Comment by Golddouble** [comment]
No output with this command:
```
$ grep folder_open_cmd ~/.config/fsearch/fsearch.conf
Golddouble@mx:~
$ 
```

But if you want to know the content of the file "~/.config/fsearch/fsearch.conf" here it is:
```
[Interface]
single_click_open=false
launch_desktop_files=true
highlight_search_terms=true
restore_column_configuration=true
restore_sort_order=true
double_click_path=true
enable_list_tooltips=true
enable_dark_theme=false
show_menubar=true
show_statusbar=true
show_filter=true
show_search_button=false
show_base_2_units=false
action_after_file_open=0
action_after_file_open_keyboard=false
action_after_file_open_mouse=false
exit_on_escape=true
show_indexing_status=true
restore_window_size=true
window_width=1884
window_height=1058
show_listview_icons=true
show_path_column=true
show_type_column=false
show_extension_column=true
show_size_column=true
show_modified_column=true
sort_ascending=true
sort_by=Path
name_column_width=535
path_column_width=997
extension_column_width=100
type_column_width=100
size_column_width=75
modified_column_width=154
name_column_pos=0
path_column_pos=1
type_column_pos=2
size_column_pos=3
modified_column_pos=4

[Dialogs]
show_dialog_failed_opening=true

[Search]
search_as_you_type=true
auto_search_in_path=true
auto_match_case=false
search_in_path=false
enable_regex=false
match_case=false
hide_results_on_empty_search=true

[Database]
update_database_on_launch=false
update_database_every=false
update_database_every_hours=0
update_database_every_minutes=15
exclude_hidden_files_and_folders=false
follow_symbolic_links=false
location_1=/
location_enabled_1=true
location_update_1=true
location_one_filesystem_1=false
location_2=/media/D-Konto/Windows 10/Dokumente und Einstellungen/Verschiedenes/Documents
location_enabled_2=true
location_update_2=true
location_one_filesystem_2=false
exclude_location_1=/run/user/1000/gvfs/mtp:host=HMD_Global_Nokia_1_FRTBB81225005073
exclude_location_enabled_1=true
exclude_location_2=/media/D-Konto
exclude_location_enabled_2=true
exclude_location_3=/media/D-Konto/Seagate_2TB_ext4
exclude_location_enabled_3=true
exclude_location_4=/media/D-Konto/Seagate 2TB-1
exclude_location_enabled_4=true
exclude_location_5=/media/D-Konto/Volume
exclude_location_enabled_5=true
exclude_location_6=/media/D-Konto/homeNTFS
exclude_location_enabled_6=true
exclude_location_7=/home/D-Konto/Mein -D- Laufwerk/Backup
exclude_location_enabled_7=true
exclude_location_8=/home/D-Konto/Supermemo Collections
exclude_location_enabled_8=true
exclude_location_9=/home/D-Konto/LutrisPfx
exclude_location_enabled_9=true
exclude_location_10=/home/D-Konto/Mein -D- Laufwerk/Daten/Video/Neuer Ordnerr
exclude_location_enabled_10=true
exclude_location_11=/home/D-Konto/.local/share/lutris
exclude_location_enabled_11=true
exclude_location_12=/home/D-Konto/.local/share/Trash
exclude_location_enabled_12=true
exclude_files=

[Filters]
filter_1_name=Alles
filter_1_macro=
filter_1_query=
filter_1_match_case=false
filter_1_search_in_path=false
filter_1_enable_regex=false
filter_2_name=Ordner
filter_2_macro=
filter_2_query=folder:
filter_2_match_case=false
filter_2_search_in_path=false
filter_2_enable_regex=false
filter_3_name=Dateien
filter_3_macro=
filter_3_query=file:
filter_3_match_case=false
filter_3_search_in_path=false
filter_3_enable_regex=false
filter_4_name=Anwendungen
filter_4_macro=app
filter_4_query=ext:desktop;DESKTOP
filter_4_match_case=true
filter_4_search_in_path=false
filter_4_enable_regex=false
filter_5_name=Archive
filter_5_macro=archive
filter_5_query=ext:7z;ace;arj;bz2;cab;gz;gzip;jar;r00;r01;r02;r03;r04;r05;r06;r07;r08;r09;r10;r11;r12;r13;r14;r15;r16;r17;r18;r19;r20;r21;r22;r23;r24;r25;r26;r27;r28;r29;rar;tar;tgz;z;zip;7Z;ACE;ARJ;BZ2;CAB;GZ;GZIP;JAR;R00;R01;R02;R03;R04;R05;R06;R07;R08;R09;R10;R11;R12;R13;R14;R15;R16;R17;R18;R19;R20;R21;R22;R23;R24;R25;R26;R27;R28;R29;RAR;TAR;TGZ;Z;ZIP
filter_5_match_case=true
filter_5_search_in_path=false
filter_5_enable_regex=false
filter_6_name=Audio
filter_6_macro=audio
filter_6_query=ext:aac;ac3;aif;aifc;aiff;au;cda;dts;fla;flac;it;m1a;m2a;m3u;m4a;mid;midi;mka;mod;mp2;mp3;mpa;ogg;opus;ra;rmi;spc;rmi;snd;umx;voc;wav;wma;xm;AAC;AC3;AIF;AIFC;AIFF;AU;CDA;DTS;FLA;FLAC;IT;M1A;M2A;M3U;M4A;MID;MIDI;MKA;MOD;MP2;MP3;MPA;OGG;OPUS;RA;RMI;SPC;RMI;SND;UMX;VOC;WAV;WMA;XM
filter_6_match_case=true
filter_6_search_in_path=false
filter_6_enable_regex=false
filter_7_name=Dokumente
filter_7_macro=doc
filter_7_query=ext:c;chm;cpp;csv;cxx;doc;docm;docx;dot;dotm;dotx;h;hpp;htm;html;hxx;ini;java;lua;mht;mhtml;ods;odt;odp;pdf;potx;potm;ppam;ppsm;ppsx;pps;ppt;pptm;pptx;rtf;sldm;sldx;thmx;txt;vsd;vsdx;wpd;wps;wri;xlam;xls;xlsb;xlsm;xlsx;xltm;xltx;xml;C;CHM;CPP;CSV;CXX;DOC;DOCM;DOCX;DOT;DOTM;DOTX;H;HPP;HTM;HTML;HXX;INI;JAVA;LUA;MHT;MHTML;ODS;ODT;ODP;PDF;POTX;POTM;PPAM;PPSM;PPSX;PPS;PPT;PPTM;PPTX;RTF;SLDM;SLDX;THMX;TXT;VSD;VSDX;WPD;WPS;WRI;XLAM;XLS;XLSB;XLSM;XLSX;XLTM;XLTX;XML
filter_7_match_case=true
filter_7_search_in_path=false
filter_7_enable_regex=false
filter_8_name=Bilder
filter_8_macro=pic
filter_8_query=ext:ani;bmp;gif;ico;jpe;jpeg;jpg;pcx;png;psd;svg;tga;tif;tiff;webp;wmf;xpm;ANI;BMP;GIF;ICO;JPE;JPEG;JPG;PCX;PNG;PSD;SVG;TGA;TIF;TIFF;WEBP;WMF;XPM
filter_8_match_case=true
filter_8_search_in_path=false
filter_8_enable_regex=false
filter_9_name=Videos
filter_9_macro=video
filter_9_query=ext:3g2;3gp;3gp2;3gpp;amr;amv;asf;avi;bdmv;bik;d2v;divx;drc;dsa;dsm;dss;dsv;evo;f4v;flc;fli;flic;flv;hdmov;ifo;ivf;m1v;m2p;m2t;m2ts;m2v;m4b;m4p;m4v;mkv;mp2v;mp4;mp4v;mpe;mpeg;mpg;mpls;mpv2;mpv4;mov;mts;ogm;ogv;pss;pva;qt;ram;ratdvd;rm;rmm;rmvb;roq;rpm;smil;smk;swf;tp;tpr;ts;vob;vp6;webm;wm;wmp;wmv;3G2;3GP;3GP2;3GPP;AMR;AMV;ASF;AVI;BDMV;BIK;D2V;DIVX;DRC;DSA;DSM;DSS;DSV;EVO;F4V;FLC;FLI;FLIC;FLV;HDMOV;IFO;IVF;M1V;M2P;M2T;M2TS;M2V;M4B;M4P;M4V;MKV;MP2V;MP4;MP4V;MPE;MPEG;MPG;MPLS;MPV2;MPV4;MOV;MTS;OGM;OGV;PSS;PVA;QT;RAM;RATDVD;RM;RMM;RMVB;ROQ;RPM;SMIL;SMK;SWF;TP;TPR;TS;VOB;VP6;WEBM;WM;WMP;WMV
filter_9_match_case=true
filter_9_search_in_path=false
filter_9_enable_regex=false
filter_10_name=Konfigurations-Dateien
filter_10_macro=
filter_10_query=ext:conf;rc;txt
filter_10_match_case=false
filter_10_search_in_path=false
filter_10_enable_regex=false
```

**Comment by cboxdoerfer** [comment]
> No output with this command:

That's fine, this just means you didn't override the folder open command manually.

But I still can't reproduce the issue — I tried MX 21 with Xfce. I'll try MX 19 again tomorrow.

**Comment by Golddouble** [comment]
More Info:
I have now uninstalled version Version 0.2.2 .
After I have installed the old version 0.1-1 .

So I was able to test the same with the old version.
And yes: I have not this issue with the old version.

After I have uninstalled version 0.1-1 and installed again version 0.2.2:
Now I have again this issue.

**Comment by cboxdoerfer** [comment]
I've now tried to reproduce it with MX 19 (Xfce + Thunar), but no busy mouse pointer there either.

**Comment by Golddouble** [comment]
Thank you. Strange.

**Comment by cboxdoerfer** [comment]
Ah, now I can reproduce it. Do you by any chance have Thunar configured to open new instances as tabs? Because once I enable this feature, the busy mouse pointer shows up.

But this also seems to happen with other applications on my system which open the file manager. For example when I click on the "Open folder" button in the Firefox download menu, Thunar also shows the busy mouse pointer. So this seems like the issue is somewhere else. Maybe in Thunar, because it somehow doesn't notify the system that it successfully opened?

**Comment by cboxdoerfer** [comment]
The reason why this doesn't happen with 0.1 is because this version didn't use the [startup notification system](https://www.freedesktop.org/wiki/Specifications/startup-notification-spec/) at all, when opening files or folders.

**Comment by cboxdoerfer** [comment]
Another application I can use to trigger this bug is `mate-search-tool` from the `mate-utils` package.

**Comment by cboxdoerfer** [comment]
Had a quick look at Thunar's code and it's indeed a Thunar bug. [Here](https://gitlab.xfce.org/xfce/thunar/-/blob/master/thunar/thunar-application.c#L1442) the code returns early when Thunar opens a new tab instead of a window, without handling the [startup id](https://gitlab.xfce.org/xfce/thunar/-/blob/master/thunar/thunar-application.c#L1460). Hence the system doesn't know that Thunar startup was successful and thinks it's still loading, i.e. showing the busy mouse cursor.

**Comment by Golddouble** [comment]
Yes, I use tabs as new instances in thunar.

> ... and it's indeed a Thunar bug.

I see.

> The reason why this doesn't happen with 0.1 is because this version didn't use the [startup notification system](https://www.freedesktop.org/wiki/Specifications/startup-notification-spec/) at all, when opening files or folders.

It's interesting.

Thank you for having a look at it. :-)

**Comment by cboxdoerfer** [comment]
No problem. One workaround you could use, until this bug gets fixed in Thunar, is to set `StartupNotify` in the `thunar.desktop` file to `false`.

You should also report it to the Thunar developers, so they become aware of the issue.
