### ISSUE TITLE
[BUG] Not all results are marked bold in the path

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#399]
**Describe the bug**
Results should marked bold in the path. But not all results are marked bold in the path.

**To Reproduce**
0. Setting:
![k20220826-162433](https://user-images.githubusercontent.com/13977359/186926509-5ed6b1b8-1e76-48ff-9c69-78f4d2b616eb.jpg)

1. open FSearch
2. Search for * /user /icon ! /enpass
3. Result:
![k20220826-162307](https://user-images.githubusercontent.com/13977359/186926723-feec0e15-3769-4849-88d6-657f46e57eab.jpg)
4. My expectation was, that also `/usr` would be bold

Do I miss anything?

**Desktop (please complete the following information):**
 - OS: MX-Linux 19.4 Xfce Debian based
 - How you installed FSearch: MX package installer
 - Version: 0.2.2
 - Output of `localectl status`
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Der Rechner ist nicht aktiv

**Comment by cboxdoerfer** [comment]
> Do I miss anything?

Yes, you typed `/user` instead of `/usr` ;)

**Comment by Golddouble** [comment]
Oh you are so right. Your programme is more reliable than I am.
