### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by cyian-1756** [cboxdoerfer/fsearch#4]
It would help if you added a section to the readme on how to compile this program

**Comment by McSinyx** [comment]
From AUR PKGBUILD I think this is how you build it:
```sh
git clone git://github.com/cboxdoerfer/fsearch.git
cd fsearch
./autogen.sh
./configure
sudo make install
```

**Comment by cboxdoerfer** [comment]
@cyian-1756, I will add one. Thx for the suggestion.

What distribution are you using? Then I can also figure out the exact package names and commands to install all the dependencies.

**Comment by cyian-1756** [comment]
@cboxdoerfer Ubuntu 16.04

@McSinyx `./configure` errors out with 

`./configure: line 2890: syntax error near unexpected token `IT_PROG_INTLTOOL'
./configure: line 2890: `AX_REQUIRE_DEFINED(IT_PROG_INTLTOOL)'
`

**Comment by MoHD20** [comment]
I  wish you add instructions for fedora too.

**Comment by McSinyx** [comment]
@cyian-1756 sorry I didn't test it. I have that same error on Debian testing.

**Comment by cboxdoerfer** [comment]
@cyian-1756, finally had some time to install Ubuntu to figure out the build dependencies. Instructions how to build FSearch can new be found [here](https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions). I hope this works for you.

Currently they only cover Ubuntu, so I'll keep this bug report open until they at least cover the most common distributions (Fedora, Debian, openSUSE).

**Comment by McSinyx** [comment]
@cboxdoerfer It works on Debian testing too, but I'm wondering if we need `libpcre3` (the binary package) or not.

**Comment by cboxdoerfer** [comment]
@McSinyx, ah yes, that's not needed for building, but it's a runtime dependency. I'll update the wiki, thx.

**Comment by cboxdoerfer** [comment]
@MoHD20, added instructions to build on Fedora.

**Comment by JMMarchant** [comment]
Any chance of instructions for Ubuntu 14.04 (as it's still a supported LTS)? Following the instructions already posted `./configure` fails with:

`./configure: line 2877: syntax error near unexpected token ``IT_PROG_INTLTOOL'`
`./configure: line 2877: ``AX_REQUIRE_DEFINED(IT_PROG_INTLTOOL)'`

Would be great as I've been trying to find something like this for ages!

**Comment by cboxdoerfer** [comment]
Yes, Ubuntu 14.04 is currently not supported because it uses a too old GTK version, but I'll see if I can lower the requirements by using some ifdefs and make it work there too.

**Comment by JMMarchant** [comment]
That would be fantastic :)

**Comment by bsbhro** [comment]
Hi, I got this
./configure: line 6340: syntax error near unexpected token `-std=c11,'
./configure: line 6340: `AX_CHECK_COMPILE_FLAG(-std=c11, CFLAGS+=" -std=c11" ,'
and commented the proof out, than it worked. I use gcc-6.

The autogen-step gave me this:
---
$ ./autogen.sh 
Copying file po/Makefile.in.in

Please add the files
  codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
  progtest.m4
from the /usr/share/aclocal directory to your autoconf macro directory
or directly to your aclocal.m4 file.
You will also need config.guess and config.sub, which you can get from
ftp://ftp.gnu.org/pub/gnu/config/.

src/Makefile.am:65: warning: shell $(GLIB_COMPILE_RESOURCES: non-POSIX variable name
src/Makefile.am:65: (probably a GNU make extension)
---
I ignored it. The build was successful. Thank you!

**Comment by feinstaub** [comment]
I also get those error messages on openSUSE Tumbleweed:
```
./configure: line 6384: syntax error near unexpected token `-std=c11,'
./configure: line 6384: `AX_CHECK_COMPILE_FLAG(-std=c11, CFLAGS+=" -std=c11" ,'
```

**Comment by feinstaub** [comment]
The tool works great by the way! :)

**Comment by napcok** [comment]
> Which packages I need to install for Arch Linux? Anyone already compiled it to this distribution?

https://aur.archlinux.org/packages/fsearch-git/
