### ISSUE TITLE
Parent filter...what is supposed to do ?

### ISSUE THREAD

**Issue by nicolasmol** [cboxdoerfer/fsearch#406]
Hi.
What is it supposed to do ?
It's a shame. I wanted to use is for Nemo integration (creating a "action", like "search here"...)
![Peek 06-09-2022 10-50](https://user-images.githubusercontent.com/61077647/188617037-8af4b4ff-5482-46d5-a891-5c712b99fab4.gif)

**Comment by cboxdoerfer** [comment]
It shows all children of the typed path. So `parent:/home/nicolasm/Dev` will display all the files and folders in that folder.

**Comment by cboxdoerfer** [comment]
For a recursive "search here" action you probably want to use `path:` instead.

**Comment by nicolasmol** [comment]
But why it don't show anything with /home or /home/nicolasm ?

**Comment by nicolasmol** [comment]
Oh I understand...it's because they are outside the scope of the Database...
ok, ok...:-)

**Comment by cboxdoerfer** [comment]
Because you haven't added those folders to the index.
