### ISSUE TITLE
Short history

### ISSUE THREAD

**Issue by gualter60** [cboxdoerfer/fsearch#407]
**Is your feature request related to a problem? Please describe.**
Like everything that have the possibility to go back for the last searches by use shortcut keys. Better in list mode.  

**Describe the solution you'd like**
When repeat recent searches needed was good idea to have a short list for the latest searches

**Describe alternatives you've considered**
Maybe a log for all searches of de last 24h with time and words

**Additional context**

**Comment by cboxdoerfer** [comment]
Yes a search history is already on my TODO list. It's planned for version 0.4 or 0.5 (unless someone else implements it sooner). For further discussion see #122
