### ISSUE TITLE
[BUG] After alt-tabbing out of the application, scrolled cursor row position highlights are misplaced

### ISSUE THREAD

**Issue by nekohayo** [cboxdoerfer/fsearch#414]
**To Reproduce**
1. Open and maximize the fsearch window, search for something that has enough search results to scroll
2. Scroll down, notice there is a slight faded gray row highlight under the mouse cursor
3. Alt-tab to another application, alt-tab back to fsearch
4. Notice that the row highlight is now offset from the mouse cursor, it shows up way above the mouse cursor, as if you had not scrolled.

**Desktop (please complete the following information):**
 - OS: Fedora 35 with GNOME Shell, X11/Xorg version
 - How you installed FSearch: Flatpak from flathub
 - Version: 0.2.2

**Comment by cboxdoerfer** [comment]
Thx, I can confirm the issue.
