### ISSUE TITLE
Make past searches reusable

### ISSUE THREAD

**Issue by fethomm** [cboxdoerfer/fsearch#415]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem, would just be nice to have
**Describe the solution you'd like**
I would like to have a way to bring past searches up again and reuse them
**Describe alternatives you've considered**
There is no alternative other than to rack my brain trying to think of the search term I used a couple of days ago
**Additional context**

**Comment by cboxdoerfer** [comment]
Hi, a search history and bookmarked searches are already on my TODO list. They'll probably be part of the 0.4 or 0.5 release.
