### ISSUE TITLE
Other disks cannot be added to the search path

### ISSUE THREAD

**Issue by liuguicen** [cboxdoerfer/fsearch#419]
Why can't such a well-known application achieve such a simple function?
0.2.2 version
I have multiple hard disks in the/D/F directory, but none of them can be seen on the FSearch Add Search Path page

**Comment by cboxdoerfer** [comment]
If those folders can't be added to the database then FSearch doesn't have the permissions to read them. So either you're looking in the wrong place when adding them or you didn't grant FSearch access to those disks when mounting them.

Without additional information about the permissions of those folders etc. I can't provide any further help.

**Comment by pixel96x** [comment]
> Why can't such a well-known application achieve such a simple function? 0.2.2 version I have multiple hard disks in the/D/F directory, but none of them can be seen on the FSearch Add Search Path page

If it is installed as Flatpak, then custom directories created in e.g. root directory (`/`) might not be indexed

Example:
![](https://i.ibb.co/Pgyq4sd/fsearch-index.png)

You might need to install [Flatseal](https://beta.flathub.org/apps/details/com.github.tchx84.Flatseal) and add permission for accessing Your custom directories. Then they should be allowed to be indexed by an app.
