### ISSUE TITLE
build on opensuse: ERROR: Program 'itstool' not found or not executable

### ISSUE THREAD

**Issue by grummbeer** [cboxdoerfer/fsearch#432]
Following the build instructions for openSUSE at https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions#opensuse

`meson builddir` fails with

```
Program itstool found: NO

help/meson.build:16:6: ERROR: Program 'itstool' not found or not executable
```
Solution:

```bash
zypper install itstool
```
Afterward the build and install was successful.

The `itstool` should included in the `sudo zypper install meson …` list.

 - OS: openSUSE tumbleweed

**Comment by cboxdoerfer** [comment]
Thx, I've updated the build instructions.
