### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by apapapapapapap** [cboxdoerfer/fsearch#435]
OS: DebianBuster
Installed: Followed the build-instructions on github
Version: FSearch 0.3.alpha0
localectl status:
   System Locale: LANG=de_DE.UTF-8
       VC Keymap: n/a
      X11 Layout: de
      X11 Model: pc105

Problem:

a) when i try to 'open directory' at a found file:
 -> 'Error when getting information for content type 'inode/directory": Keine Standardanwendung bekannt.'
 
b) when i try to open the found file (doubleclick or ENTER:
 -> 'Error when getting Information for content type "application/x-7z-compressed": keine Standardanwendung bekannt'
    (7z is just an example, happens also with other filetypes)
    
This happens only on one of my machines, running debian buster.
When i checked fsearch 0.1 on that computer (just happend to be at hand on that machine): both options work perfect.

On another PC running debian buster fsearch0.3alpha works without problems also.

So the problem only occurs on one machine and only with fsearch 0.3 alpha.

(temporary) solution: using fsearch0.1

**Comment by cboxdoerfer** [comment]
Hi, thx for the report. Can you post a screenshot of the "Open with" context menu content when you right click on a folder?

**Comment by apapapapapapap** [comment]
Here they are:

![Screenshot_20221026_012919](https://user-images.githubusercontent.com/34889783/197843363-29fc2628-9988-48ec-b314-78c4c723112a.png)
![Screenshot_20221026_012935](https://user-images.githubusercontent.com/34889783/197843377-28115d5b-f798-4f5a-976c-13e66c051ce2.png)

**Comment by cboxdoerfer** [comment]
What is the output of `xdg-mime query default inode/directory` ?

**Comment by apapapapapapap** [comment]
Update:

After i choose my own application(s) (rightlick on found file -> 'open with' -> 'other application') i can select them
the next time i use the right-click context menu (they show up there).
I.e. i have a txt file, i chose 'scite' as assigned prg. then fsearch opened the file with scite. now if i doubleclick on a txt-file it automatically opens with scite.
Additionally i can choose also 'kate', because i chose that before at 'open with'

I'm not absolutely sure, but AFAIR that was not possible the last times i tried before.
What i did meanwhile was to change between fsearch 0.1 and 0.3alpha several times for testing purpose.

But (for me the main problem) open the containing directory still gives the error at the screenshots i posted before.

**Comment by apapapapapapap** [comment]
----------------------------
What is the output of xdg-mime query default inode/directory ?
----------------------------

Output:
org.kde.dolphin.desktop

**Comment by apapapapapapap** [comment]
Just for your information:

On my other debian buster where fsearch 0.3alpha0 works as expected the output is the same.

**Comment by apapapapapapap** [comment]
I think i accidentially closed the topic by mistake. never mind that.

**Comment by cboxdoerfer** [comment]
What happens when you run `gio open ~` ?

**Comment by apapapapapapap** [comment]
'gio mime inode/directory' output:
Keine Vorgabeanwendungen für »inode/directory«

'gio open ~' output:
gio: file:///home/w95: Es wurde keine Anwendung gefunden, die diese Datei verarbeiten kann

**Comment by cboxdoerfer** [comment]
Ok so there's some problem with your systems mime configuration. Maybe the mime database hasn't been updated.

**Comment by apapapapapapap** [comment]
I can't exclude that. Only i never had nor have similar problems with any application or in any situation on that pc. And with fsearch it was ok until version 0.2 (checked that recently). So just for your information: something in handling this situation has changed since fsearch 0.2. Using fsearch 0.1.4 on that pc rightnow - no problems with opening files or folders from within fsearch. Anyway, fsearch is a great help and this -at least for me- is only a minor problem. Thanks and keep up the good work.

**Comment by apapapapapapap** [comment]
Short update: Tried update-mime-database. Runs without errors. fsearch 0.3 still don't open folders.

**Comment by cboxdoerfer** [comment]
Yes the way files get opened changed with 0.2, but this issue is somewhere on your system. As you can see the `gio` command can't open your home directory as well -- it's supposed to open it with your default file manager. Most GTK applications use gio to open files, as does FSearch since 0.2, so the issue will also be present in many other GTK applications.

**Comment by cboxdoerfer** [comment]
One thing you can try to fix this is to let gio set your default file manager:

`gio mime inode/directory org.kde.dolphin.desktop`

**Comment by apapapapapapap** [comment]
That worked. At least for opening folders. For unknown file-types i still have to select a appropriate application once. Then the next time i select 'open' the application is opened automatically. So problem solved. Thank you.

**Comment by cboxdoerfer** [comment]
I think I found the reason why this doesn't work on your system. It seems this is a KDE bug: https://bugs.kde.org/show_bug.cgi?id=305136

In short: KDE does not have a `/usr/share/applications/kde-mimeapps.list` or  `/usr/share/applications/mimeapps.list` by default, which would tell the system what the default applications for specific file types should be. Instead KDE adds non-standard keys to their application's desktop files, which is not supported by non-KDE applications.

So since there's no `mimeapps.list` on your system, FSearch and other non-KDE apps have no idea how to open files. But once you explicitly open a filetype with a certain application it will remember that and store that in your user-specific `~/.config/mimeapps.list`.

**Comment by cboxdoerfer** [comment]
The reason why it worked with FSearch 0.1 is because it used the shell script `xdg-open` to open files, which on a KDE system runs `kde-open`, which obviously understands the non-standard KDE extension in desktop files and doesn't require a `mimeapps.list`.

**Comment by apapapapapapap** [comment]
Thanks for the explanation. For testing purposes i copied my mimeapps.list from the pc where fsearch handles all correctly to the other, problematic one. on the first pc, if i click a txt-file without extension scite opens, on the other one (now with identical mimeapps.list) kate opens. But anyway, works for me as it is now. Another observation: if i open a file or directory out of fsearch on my 'correct working' pc and close fsearch then, the opened file and directory windows stay in place. On the other 'problematic' pc the directory and file windows are closed when i end fsearch.

**Comment by cboxdoerfer** [comment]
> For testing purposes i copied my mimeapps.list from the pc where fsearch handles all correctly to the other, problematic one. on the first pc, if i click a txt-file without extension scite opens, on the other one (now with identical mimeapps.list) kate opens. 

There are probably multiple mimeapps.list files on your other PC. For example there's `~/.config/mimeapps.list` and `/usr/share/applications/mimeapps.list`. The former has precedence over the other and stores your overridden default applications. I suppose `scite` was declared as default in `~/.config/mimeapps.list` and maybe you only copied `/usr/share/applications/mimeapps.list`?

> Another observation: if i open a file or directory out of fsearch on my 'correct working' pc and close fsearch then, the opened file and directory windows stay in place. On the other 'problematic' pc the directory and file windows are closed when i end fsearch.

That is weird. From which commit was this version build? (Go to the fsearch build directory and run `git rev-parse HEAD` alternatively you can also provide the output of `stat /usr/local/bin/fsearch` to get a rough estimate of how old that build is).

**Comment by apapapapapapap** [comment]
On the 'problematic' pc is only one mimeapps.list, it's located in ~/.config/. On the other pc there's also only the mimeapps.list in ~/.config. That's the one i copied. 

'git rev-parse HEAD' output: d1fad39c330e9ebd3836d403bc6532f1ccd0c4f1
'stat /usr/local/bin/fsearch' output:
  Datei: /usr/local/bin/fsearch
  Größe: 1072056        Blöcke: 2096       EA Block: 4096   reguläre Datei
Gerät: 811h/2065d       Inode: 3492        Verknüpfungen: 1
Zugriff: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Zugriff    : 2022-10-27 07:53:27.185846454 +0200
Modifiziert: 2022-10-27 07:53:20.394025083 +0200
Geändert   : 2022-10-27 07:53:20.394025083 +0200
 Geburt    : -

Btw: Countertest with fsearch 0.1.4: file and directory windows stay open after fsearch get closed.

**Comment by apapapapapapap** [comment]
'git rev-parse HEAD' output:
d1fad39c330e9ebd3836d403bc6532f1ccd0c4f1

**Comment by apapapapapapap** [comment]
after i send the output of 'git rev-parse HEAD' output: is truncated. Can't send the whole number?

**Comment by cboxdoerfer** [comment]
That's no problem, GitHub already links to the right commit automatically.
