### ISSUE TITLE
fsearch: error while loading shared libraries: libicuuc.so.71: cannot open shared object file: No such file or directory[BUG]

### ISSUE THREAD

**Issue by ZAKhan** [cboxdoerfer/fsearch#436]
ArchLinux

Latest upgrade shows libicuuc.so was upgraded top 72 which results in this error.

❯ locate libicuuc
/opt/teamviewer/tv_bin/RTlib/libicuuc.so.63
/usr/lib/libicuuc.so
/usr/lib/libicuuc.so.72
/usr/lib/libicuuc.so.72.1
/usr/lib/insync/libicuuc.so.56
/usr/lib/plexmediaserver/lib/libicuucplex.so.69
/usr/lib32/libicuuc.so
/usr/lib32/libicuuc.so.72
/usr/lib32/libicuuc.so.72.1

**Comment by cboxdoerfer** [comment]
You need to rebuild FSearch. From the AUR documentation:

> The AUR is unsupported, so any packages you install are your responsibility to update, not pacman's. If packages in the official repositories are updated, you will need to rebuild any AUR packages that depend on those libraries.

In this case `icu` was updated, which means you need to rebuild every installed AUR package which depends on it.
