### ISSUE TITLE
Use Gtk.HeaderBar

### ISSUE THREAD

**Issue by donadigo** [cboxdoerfer/fsearch#44]
It'll probably make sense to use Gtk.HeaderBar as the titlebar instead of classic one in GTK+ 3 UI.

**Comment by lf-araujo** [comment]
Yes, please!

**Comment by cboxdoerfer** [comment]
Shouldn't be too much work to add an option to toggle between the classic interface and a headerbar. However menu bar will remain the default.

**Comment by cboxdoerfer** [comment]
Took a while, GtkHeaderBar is now supported. In order to activate it you need to disable the menubar in the preferences.
