### ISSUE TITLE
[BUG] fsearch opens new dolphin session while opening a folder

### ISSUE THREAD

**Issue by soundsbeard** [cboxdoerfer/fsearch#451]
**Describe the bug**
in started to happen after some recent os update.
while opening a folder, fsearch opens a duplicate session of a dolphin file manager instead of opening a folder in the new tab of the existing dolphin session.

**To Reproduce**
1. open dolphin fm with few tabs
2. open fsearch
3. search for any folder
4. double click on it

**Expected behavior**
fsearch should open existing dolphin session and create there a new tab with desired folder 

**Screenshots**
https://i.imgur.com/vviGNIK.mp4

**Desktop (please complete the following information):**
 - OS: 
 manjaro plasma

 - How you installed FSearch
aur, fsearch-git 

 - Version [output of `fsearch --version`]
FSearch 0.3.alpha0 (AUR-devel)
tested on aur stable also

 - Output of `localectl status`
System Locale: LANG=en_US.UTF-8
               LC_NUMERIC=ru_RU.UTF-8
               LC_TIME=ru_RU.UTF-8
               LC_MONETARY=ru_RU.UTF-8
               LC_PAPER=ru_RU.UTF-8
               LC_NAME=ru_RU.UTF-8
               LC_ADDRESS=ru_RU.UTF-8
               LC_TELEPHONE=ru_RU.UTF-8
               LC_MEASUREMENT=ru_RU.UTF-8
               LC_IDENTIFICATION=ru_RU.UTF-8
    VC Keymap: us
   X11 Layout: us

**Additional context**
-

**Comment by cboxdoerfer** [comment]
Does the same happen when you open folders with the following command:

1.  `gio open /usr/lib`
2. `gio open /usr/share`

and do you have `Configure Dolphin -> Startup -> Open new folders in tabs` enabled?

Otherwise this sounds like a bug in Dolphin.

**Comment by soundsbeard** [comment]
> nd do you have Configure Dolphin -> Startup -> Open new folders in tabs enabled?

it was disabled.
it seems that system update somehow changed dolphin config, bc i've been using fsearch+dolphin for years and it was enabled (i believe by default)

thank you for your help.
