### ISSUE TITLE
[BUG] No filter option in preferences

### ISSUE THREAD

**Issue by adevoss** [cboxdoerfer/fsearch#452]
Installed fsearch on Mint and AV Linux.
Search is working on both.
No filter options in preferences on AV Linux (based on MX Linux)
Maybe not a bug (sysvinit/systemd). If not a bug please put some message in the preferences window.

1. Install fsearch on AV Linux (maybe MX Linux too??)
2. Click on 'Edit - Preferences - Search'
3. There is no Filter option. Only the first four options.

**Expected behavior**
The Filter option should be there

**Screenshots**
Made a screenshot but drag and drop returns error?? (png/jpg).

**Desktop (please complete the following information):**
 - OS: Mint 21.1 / AV Linux 21.1
 - How you installed FSearch: PPA
 - Version FSearch 0.2.2 (PPA-stable)
 - Output of `localectl status`
 Mint:
   System Locale: LANG=nl_NL.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105
     X11 Variant: euro
AV Linux:
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
(So SysVinit instead of systemd I think)

**Additional context**
Mint: ext4 file system
AV Linux: btrfs file system

**Comment by cboxdoerfer** [comment]
This sounds like AV Linux is not using the 0.2 version but 0.1. Are you sure you're using 0.2.2?

**Comment by adevoss** [comment]
It is not part of AVL. Installed it manually via PPA. After your comment I checked. It was version 0.1.
Installed it the same twice. Can't reproduce anymore.

When downloading the .deb file it is version 0.2.2.
Thanks.
