### ISSUE TITLE
[BUG] fsearch: error while loading shared libraries: libicuuc.so.67: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by danielkrajnik** [cboxdoerfer/fsearch#455]
**Describe the bug**
can't start fsearch, missing library

**Desktop:**
 - OS: Ubuntu 22.04
 - How you installed FSearch: [PPA](https://launchpad.net/~christian-boxdoerfer/+archive/ubuntu/fsearch-stable)
 - Output of `localectl status`: 
 -    System Locale: LANG=en_GB.UTF-8
                  LANGUAGE=en_GB:en
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105

not sure how that happened or how to fix it ;/

**Comment by cboxdoerfer** [comment]
Hi, thx for the report.

That's a weird issue, because Ubuntu 22.04 never shipped ICU 67 and FSearch was always build against the shipped ICU 70 version as far as I know. Can you post the output of the following commands?

`whereis fsearch`

`dpkg -l | grep fsearch`

`fsearch --version`

**Comment by danielkrajnik** [comment]
Sure,
```whereis fsearch```
```fsearch: /usr/bin/fsearch /usr/local/bin/fsearch /usr/share/man/man1/fsearch.1.gz```

```dpkg -l | grep fsearch```
```ii  fsearch                                          20221231+r2058.c5a43d9~ubuntu22.04.1        amd64        A fast graphical file search utility```

```fsearch --version```
```fsearch: error while loading shared libraries: libicuuc.so.67: cannot open shared object file: No such file or directory```

**Comment by cboxdoerfer** [comment]
Thx, I think this explains the issue. There's a different version of FSearch installed in `/usr/local`, probably from a manual build when your system was still an Ubuntu 20.04 release (I assume you upgraded this system at one point). So to fix this you need to remove the FSearch version installed to `/usr/local`, there a few ways how you can do that.  Do you still have a `fsearch` folder in your home directory (or somewhere else?), where you performed the manual build? If yes, can you post the output of `ls -l` from within that folder? Then I can give you the proper uninstall command.

**Comment by danielkrajnik** [comment]
Perfect, thank you very much. You are completely right, there was a manually compiled fsearch executable in ```/usr/local/bin``` from last year, which after removing and reinstalling fsearch via apt made the problem go away.

**Comment by cboxdoerfer** [comment]
> Perfect, thank you very much. You are completely right, removing a manually compiled fsearch executable in /usr/local/bin from last year and reinstalling fsearch via apt made the problem go away.

Great! I'm glad it worked.

> I don't have that fsearch folder on the system anymore, but I hope that just removing the binary from /usr/local/bin will suffice.

Yes, that's certainly enough to fix the issue. There will be just some left-over files in `/usr/local`, for example `/usr/local/share/applications/io.github.cboxdoerfer.FSearch.desktop`. You can remove them as well if you like.
