### ISSUE TITLE
Select your file manager

### ISSUE THREAD

**Issue by fullmooninu** [cboxdoerfer/fsearch#458]
**Is your feature request related to a problem? Please describe.**
I'm on manjaro/arch
When I open a folder, it opens another software, not thunar.

**Describe the solution you'd like**
Maybe be able to change the file manager / filemanager command?

**Describe alternatives you've considered**

**Additional context**

**Comment by cboxdoerfer** [comment]
FSearch uses the default file manager (according to the Freedesktop specification). So most likely Thunar just isn't configured as your default file manager.

This should be easy to fix:
With `gio mime inode/directory` you can query which application is registered as your default file manager and with `gio mime inode/directory thunar.desktop` you can set Thunar as your default file manager.

Let me know if that solves your issue.

**Comment by fullmooninu** [comment]
$ gio mime inode/directory
Default application for “inode/directory”: qdirstat.desktop
Registered applications:
	qdirstat.desktop
	thunar.desktop
Recommended applications:
	qdirstat.desktop
	thunar.desktop


yeh. thanks it was like the above. now it changed the default to thunar :)

**Comment by cboxdoerfer** [comment]
Great, no problem.
