### ISSUE TITLE
Integrate with Synapse

### ISSUE THREAD

**Issue by lf-araujo** [cboxdoerfer/fsearch#46]
The tool could have a Synapse extension.

**Comment by cboxdoerfer** [comment]
What exactly do you have in mind?

**Comment by lf-araujo** [comment]
Thanks for answering. What I have in mind was something attempted before, but axed by Synapse developers. The idea is to add a search with fsearch option, which will lead to answers in synapses own window. This [dude](https://medium.com/@theGrowingNoise/full-text-search-on-ubuntu-with-synapse-and-recoll-984b6c9540f6#.ntzrfk6ts) tried that before, this was his axed [branch](https://code.launchpad.net/~pmarchwiak/synapse-project/recoll-plugin). [Here](https://www.reddit.com/r/elementaryos/comments/3lwxqu/synapse_support_for_recoll_search_engine/) a discussion about it at elementary subreddit, and finally another model for this feature was the (late, I guess) Recoll [lens](http://www.webupd8.org/2012/03/recoll-lens-full-text-search-unity-lens.html).

**Comment by cboxdoerfer** [comment]
I just had a look at synapse, and apparently it already provides a plugin for locate. Isn't this exactly what you are looking for?

**Comment by lf-araujo** [comment]
Thanks for that. The locate functionality is indeed powerful, perhaps the problem is that my usecase is too specific. I work in science, and sometimes I have a concept in mind and I need to find which author cited it. Today I run the search either in Mendeley or in Recoll itself, it would be, however, so much more easy if my launcher would allow me to do that right off the bat...

**Comment by cboxdoerfer** [comment]
Sorry for the late response, and yes this feature is likely too specific and requires too much time. So I'm not going to add that.
