### ISSUE TITLE
"Automatic Item Selection Failure in Ubuntu File Directories"

### ISSUE THREAD

**Issue by bb33bb** [cboxdoerfer/fsearch#460]
"Upon opening a directory, the mouse pointer in Ubuntu is unable to automatically select items. manual selection is required."

**Comment by cboxdoerfer** [comment]
I don't quite understand what you mean by that. Can you describe the issue in different words? Maybe with a step by step description on how to reproduce it. Screenshots might also be helpful.

**Comment by avboy1337** [comment]
When using Everything on Windows, after searching for a file, you can simply right-click and select "Open Containing Folder" to automatically locate and select the previously searched file, which is really convenient. Fsearch is probably the best alternative for Linux.

After opening the directory in fsearch, you need to manually sort the files alphabetically and visually search for the previously searched file. Can you please add a feature to automatically select the previously searched file? Thank you!

**Comment by cboxdoerfer** [comment]
I think I understand now. This feature is already present in FSearch but you need to edit the config file and not every file manager supports this. The only ones I'm aware of which do support it are Nautilus and Dolphin.

If you're using one of those file managers you can enable this feature with:

1. Close FSearch
2. Open `~/.config/fsearch/fsearch.conf` with a text editor of your choice
3. Add the following at the end of the file if you use Dolphin:
```
  [Applications]
  folder_open_cmd=dolphin --select {path_full}
```

or if you use Nautilus:

```
  [Applications]
  folder_open_cmd=nautilus --select {path_full}
```

**Comment by avboy1337** [comment]
Worked！
Make  sure to exit the program then edit it.

**Comment by bb33bb** [comment]
how to set 
thunar
works??
I tried 

[Applications]
folder_open_cmd=thunar --select {path_full}

not success

**Comment by cboxdoerfer** [comment]
@bb33bb Thunar doesn't support a `--select` flag, so this won't work. You'll need to open feature request on the Thunar issue tracker (if not already present).

**Comment by bb33bb** [comment]
> @bb33bb Thunar doesn't support a `--select` flag, so this won't work. You'll need to open feature request on the Thunar issue tracker (if not already present).

thanks for your kindly tips!!!

**Comment by bb33bb** [comment]
> Reference in ne

[Applications]
folder_open_cmd=thunar {path_full}

works
