### ISSUE TITLE
Option to delete files

### ISSUE THREAD

**Issue by orschiro** [cboxdoerfer/fsearch#47]
Hello @cboxdoerfer,

What a great application. :-)

What do you think of an option to delete files?

![image](https://cloud.githubusercontent.com/assets/170947/20762013/33f84a1a-b725-11e6-895e-5676b4cb18a3.png)

**Comment by cboxdoerfer** [comment]
Yes, sure.

There's already a bug report for this request, so I'm closing this one. You can follow the process here #38.

**Comment by orschiro** [comment]
Thank you, Christian. :-)
