### ISSUE TITLE
behavior after open a file or click close button: minimized and stay in the tray 

### ISSUE THREAD

**Issue by GuShaocheng** [cboxdoerfer/fsearch#477]
Hi developer,

I would like to keep fsearch always running.
Would you consider adding such behavior for it:
- click the close button but don't close it instead minimize it to the system tray
- open a file or folder successfully then minimize it to the tray

Thanks for your consideration,
All the best!

**Comment by nekohayo** [comment]
Duplicate of #327, #487, #52. Please close this.
