### ISSUE TITLE
Add support for icu-73.2-1

### ISSUE THREAD

**Issue by JJenkx** [cboxdoerfer/fsearch#486]
After updating my system fsearch won't launch now

fsearch: error while loading shared libraries: libicuuc.so.72: cannot open shared object file: No such file or directory

**Comment by IukeByte** [comment]
I just encountered this 2 minutes ago and went to report it as well xD

**Comment by JJenkx** [comment]
After installing fsearch-git with yay it is working again

**Comment by cboxdoerfer** [comment]
Hi, I suppose you're using the AUR packages. On Arch Linux you need to manually rebuild AUR packages when one of their dependencies get updated. In this case icu was updated.

So all you need to do is basically reinstall the fsearch package with your favorite AUR helper.

**Comment by napcok** [comment]
Works fine here: fsearch 0.2.2 + icu 73.2.
You just need to rebuild fsearch.
