### ISSUE TITLE
Debian 12 Repository Missing

### ISSUE THREAD

**Issue by creeloper27** [cboxdoerfer/fsearch#488]
**Is your feature request related to a problem? Please describe.**
There currently are no `Debian 12 (bookworm)` repositories as can be seen [here](http://download.opensuse.org/repositories/home:/cboxdoerfer/) and [here](https://software.opensuse.org//download.html?project=home%3Acboxdoerfer&package=fsearch#manualDebian), there are only `Debain 11 (bullseye)` and `Debian 10 (buster)` repositories.

**Describe the solution you'd like**
It would be nice to have a `Debian 12 (bookworm)` repository as a considerable part of the Debian userbase is moving to `Debian 12 (bookworm)`, source [here](https://popcon.debian.org/#:~:text=1.76%20(bookworm/stable)%20%20%20%20%3A%2050419).

**Describe alternatives you've considered**
Installing by [building from source](https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions) is an alternative but it's not practical as you do not get automatic updates when new versions come out.

**Comment by cboxdoerfer** [comment]
Thank you for the reminder. I've just added the repository for Debian 12. If you notice any issues with it, just let me know.
