### ISSUE TITLE
Open Folders with Dolphin instead of Konqueror?

### ISSUE THREAD

**Issue by ColCorn** [cboxdoerfer/fsearch#489]
When I use Fsearch to find a folder/directory, and I click on that folder/directory in the Fsearch window, it always opens the folder with Konqueror rather than my default file manager, Dolphin.

I suspect there may be a way for me to edit a config file somewhere such that when I click on a folder/directory in the Fsearch window, it will open in Dolphin rather than Konqueror, but I don't know how, and can't find any setting in Edit/Preferences. Is there a way to do this?

(If it matters, I'm using Kubuntu 22.04 LTS.)

Thank you for a GREAT application. I use it every day!

**Comment by cboxdoerfer** [comment]
Hi. Unfortunately KDE isn't following the freedesktop specification to set default applications. That's why FSearch isn't able to honor KDE settings and picks the wrong file manager.

In order to set Dolphin as your default file manager in a desktop agnostic way you can run the following command:

``` gio mime inode/directory org.kde.dolphin.desktop```

Let me know if that resolves the issue.

**Comment by ColCorn** [comment]
Dear Christian:
Thank you so much...that worked! And thank you for taking the time to email me the solution. I really appreciate it.

Best regards from sunny Virginia, USA,
Jeff

    On Thursday, July 27, 2023 at 09:58:29 AM UTC, Christian Boxdörfer ***@***.***> wrote:  
 
 


Hi. Unfortunately KDE isn't following the freedesktop specification to set default applications. That's why FSearch isn't able to honor KDE settings and picks the wrong file manager.

In order to set Dolphin as your default file manager in a desktop agnostic way you can run the following command:

 gio mime inode/directory org.kde.dolphin.desktop

Let me know if that resolves the issue.

**Comment by cboxdoerfer** [comment]
No problem! I'm glad it worked.
