### ISSUE TITLE
russian translation

### ISSUE THREAD

**Issue by yakonstb** [cboxdoerfer/fsearch#49]
I have added russian translation:
https://github.com/yakonstb/misc/blob/master/ru.po

**Comment by yakonstb** [comment]
updated translation

**Comment by cboxdoerfer** [comment]
Hi, thx. But could you please use Weblate for submitting translations? Like described here: https://github.com/cboxdoerfer/fsearch#localization

**Comment by cboxdoerfer** [comment]
Saw you already did the translation on Weblate, thx :)
