### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cboxdoerfer/fsearch#5]
I would like to point out that identifiers like "[`_DatabaseSearch`](https://github.com/cboxdoerfer/fsearch/blob/02ce6973d98eaa808d68b980b312f3f58bfa33ab/src/database_search.c#L33)" and "[`_FsearchApplication`](https://github.com/cboxdoerfer/fsearch/blob/19ac067a543ac456a213fcd16da6cc7e4b5fb80f/src/fsearch.c#L40)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by cboxdoerfer** [comment]
Yeah, probably a bad habit of mine. I will think of a better way how to do it.

**Comment by cboxdoerfer** [comment]
This is fixed in some parts now, but when declaring GObjects with `G_DECLARE_FINAL_TYPE` it can't be avoided.

**Comment by elfring** [comment]
:thinking: How do you think about to [influence the software evolution](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") any more for [affected identifiers](https://github.com/cboxdoerfer/fsearch/blob/b4bf7f8414e7158e06b00b9f4f17fd437fe9cb55/src/fsearch.c#L42 "Update candidate")?

**Comment by cboxdoerfer** [comment]
Like I said, in the case of GObject declarations it's what macros like [G_DECLARE_FINE_TYPE](https://developer.gnome.org/gobject/stable/gobject-Type-Information.html#G-DECLARE-FINAL-TYPE:CAPS) demand:

> the MyAppWindow types is defined as a typedef of struct _MyAppWindow. The struct itself is not defined and should be defined from the .c file before G_DEFINE_TYPE() is used.

So I'm not going to change those identifiers. It's not feasible for me to take a stand against glib's API design and code conventions. All other identifiers should now adhere to the C coding standards.
