### ISSUE TITLE
exclude folder not working

### ISSUE THREAD

**Issue by cenobite1** [cboxdoerfer/fsearch#50]
i keep on adding /mnt to the  exclusion list, yet it keeps indexing mnt and all its subdirs

**Comment by cboxdoerfer** [comment]
Can you paste the content of `~/.config/fsearch/fsearch.conf`?

**Comment by cenobite1** [comment]
[Interface]
restore_column_configuration=false
enable_list_tooltips=true
enable_dark_theme=false
show_menubar=true
show_statusbar=true
show_filter=true
show_search_button=true
restore_window_size=false
window_width=800
window_height=600
show_listview_icons=true
show_path_column=true
show_type_column=true
show_size_column=true
show_modified_column=true
name_column_width=674
path_column_width=250
type_column_width=100
size_column_width=75
modified_column_width=125
name_column_pos=0
path_column_pos=1
type_column_pos=2
size_column_pos=3
modified_column_pos=4

[Search]
search_as_you_type=true
auto_search_in_path=true
search_in_path=false
enable_regex=false
match_case=false
hide_results_on_empty_search=true
limit_results=true
num_results=10000

[Database]
update_database_on_launch=true
exclude_hidden_files_and_folders=false
follow_symbolic_links=false
location_1=/
exclude_location_1=/media
exclude_location_2=/mnt/C
exclude_location_3=/mnt/F
exclude_location_4=/mnt/G

**Comment by cboxdoerfer** [comment]
Just to be clear: do all items in /mnt/C show up in the search results? Or does only /mnt/C show up, but not its subdirs and items?

**Comment by cenobite1** [comment]
> Just to be clear: do all items in /mnt/C show up in the search results?

Yep

**Comment by cboxdoerfer** [comment]
Hm, that's weird. I can't confirm that. How did you install FSearch? PPA, AUR, deb-file or build from source?

**Comment by cboxdoerfer** [comment]
Oh, and another thing: can you try running FSearch from command line and paste the output here as soon as the database is updated?

**Comment by cenobite1** [comment]
i installed it from here : https://github.com/cboxdoerfer/fsearch/releases/download/0.1beta1/fsearch_0.1beta1-1_amd64.deb

**Comment by cboxdoerfer** [comment]
There's now a PPA to get updates automatically: https://launchpad.net/~christian-boxdoerfer/+archive/ubuntu/fsearch-daily

Please try the version from there.

**Comment by cenobite1** [comment]
When run from Konsole, this is the output:

`(fsearch:1975): Gtk-WARNING **: Theme directory aplets/64 of theme breeze-dark has no size field`

Nothing else.

**Comment by cenobite1** [comment]
Ok, will try the ppa

Also i noticed following : when searching for deb files (eg XnViewMP-linux-x64.deb) via *deb it doesn't seem to find anything, is that a feature or am i doing something wrong? file is located in /home (which is indexed).

Thanks

**Comment by cboxdoerfer** [comment]
Great.

Yes, searching with * didn't work in the version you used, but it works with the one from the PPA. And yes, searching while the database is being updated doesn't work currently I'll see what I can do about that. I opened a new issue for that: https://github.com/cboxdoerfer/fsearch/issues/51
