### ISSUE TITLE
[BUG] "Depends: libicu72 (>= 72.1~rc-1~) but is not installable"

### ISSUE THREAD

**Issue by nicolasmol** [cboxdoerfer/fsearch#500]
**Describe the bug**
Impossible to install. 
Linux mint 20.1
Error message:

"Depends: libicu72 (>= 72.1~rc-1~) but is not installable"

Not able to find anything about how to install it

**Comment by cboxdoerfer** [comment]
How did you attempt to install FSearch? You're most likely using the wrong repository with packages which were not built for Linux Mint 20.1.

**Comment by nicolasmol** [comment]
sudo add-apt-repository ppa:christian-boxdoerfer/fsearch-stable
sudo apt update
sudo apt install fsearch

**Comment by cboxdoerfer** [comment]
There must be some other repository configured as well, because the packages in that one don't require 72.1rc-1.

What's the output of:

`apt show fsearch`

And

`ll /etc/apt/sources.list.d/`

**Comment by nicolasmol** [comment]
Package: fsearch
Version: 0.2.3-1+3.23
Priority: optional
Section: utils
Maintainer: Christian Boxdörfer <cboxdoerfer@posteo.de>
Installed-Size: 1 106 kB
Depends: libc6 (>= 2.34), libcairo2 (>= 1.2.4), libgdk-pixbuf-2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.75.3), libgtk-3-0 (>= 3.21.5), libicu72 (>= 72.1~rc-1~), libpango-1.0-0 (>= 1.14.0), libpcre2-8-0 (>= 10.22)
Homepage: https://cboxdoerfer.github.io/fsearch/
Download-Size: 229 kB
APT-Sources: http://download.opensuse.org/repositories/home:/cboxdoerfer/Debian_Unstable  Packages
Description: A fast graphical file search utility
 FSearch is a fast file search utility, based on GTK3.
 It supports regular expressions, wildcards, fast sorting,
 instant results with millions of files and more.


total 84K
-rw-r--r-- 1 root root 122 août  31 13:06 blaze-main-focal.list
-rw-r--r-- 1 root root 154 août  18 14:36 costales-clipboard-to-file-focal.list
-rw-r--r-- 1 root root 130 août  18 14:36 deadsnakes-ppa-focal.list
-rw-r--r-- 1 root root 126 août  18 14:36 dupeguru-ppa-focal.list
-rw-r--r-- 1 root root 146 août  18 14:36 flexiondotorg-quickemu-focal.list
-rw-r--r-- 1 root root 130 août  18 14:36 gerardpuig-ppa-focal.list
-rw-r--r-- 1 root root 121 août  18 14:36 github-cli.list
-rw-r--r-- 1 root root 190 août  18 14:36 google-chrome.list
-rw-r--r-- 1 root root 122 août  18 14:36 hluk-copyq-focal.list
-rw-r--r-- 1 root root  83 août  20 16:06 home:cboxdoerfer.list
-rw-r--r-- 1 root root 132 août  18 14:36 libreoffice-ppa-focal.list
-rw-r--r-- 1 root root 164 août  18 14:36 maarten-fonville-android-studio-focal.list
-rw-r--r-- 1 root root 193 août  18 14:36 microsoft-edge.list
-rw-r--r-- 1 root root  95 août  18 14:36 mongodb-org.list
-rw-r--r-- 1 root root 204 août  18 14:36 nodesource.list
-rw-r--r-- 1 root root 894 août  29 11:53 official-package-repositories.list
-rw-r--r-- 1 root root 122 août  18 14:36 ondrej-php-focal.list
-rw-r--r-- 1 root root 132 août  18 14:36 papirus-papirus-focal.list
-rw-r--r-- 1 root root 111 août  18 14:36 syncthing.list
-rw-r--r-- 1 root root 142 août  20 16:56 ubuntuhandbook1-apps-focal.list
-rw-r--r-- 1 root root 203 août  18 14:36 vscode.list

**Comment by cboxdoerfer** [comment]
That's the wrong repository you're using. The one you have installed is for Debian, not Linux Mint (or Ubuntu), which means you didn't run:

```
sudo add-apt-repository ppa:christian-boxdoerfer/fsearch-stable
sudo apt update
sudo apt install fsearch
```

What you need to do is to remove the Debian FSearch repository. This should do the trick:

```sudo rm /etc/apt/sources.list.d/home:cboxdoerfer.list```

And then run:

```
sudo add-apt-repository ppa:christian-boxdoerfer/fsearch-stable
sudo apt update
sudo apt install fsearch
```

**Comment by nicolasmol** [comment]
It works, thanks
