### ISSUE TITLE
In Preferences to have the possibility to chose if Close Window button (x) only hide (minimize) the window 

### ISSUE THREAD

**Issue by silviulaurentiu** [cboxdoerfer/fsearch#507]

**Comment by nekohayo** [comment]
As per the suggestions in #392 and #416, I would recommend against this added complexity.

**Comment by nekohayo** [comment]
Also it is a duplicate of #327, #487, #52. At this point I would suggest closing this ticket.

**Comment by cboxdoerfer** [comment]
Yes, that'll be covered by the tray icon feature.
