### ISSUE TITLE
Allow searching while database updates

### ISSUE THREAD

**Issue by cboxdoerfer** [cboxdoerfer/fsearch#51]

**Comment by AtilioA** [comment]
That would be great. One of the bummers of using fsearch is when it is updating the database and you can't search anything until it finishes, and that could take some time.

**Comment by cboxdoerfer** [comment]
Searching while the database updates is now possible.

**Comment by cboxdoerfer** [comment]
@AtilioA, searching while the database is scanned should already work with the latest changes, even right after the start. But just to be clear, FSearch still has to load the database file from disk first, which is usually pretty quick.

**Comment by AtilioA** [comment]
Yeah, I forgot about that 😅. That would be solved only by minimizing to the tray, I guess.

**Comment by AtilioA** [comment]
Yeah, I forgot about that 😅. The message is a bit misleading, though - "Loading database" better conveys the meaning intended.
That would be solved only by minimizing to the tray, I guess.
