### ISSUE TITLE
combine videos and folders filters

### ISSUE THREAD

**Issue by nick75e** [cboxdoerfer/fsearch#511]
**Is your feature request related to a problem? Please describe.**
On my computer, I have got a lot of folders where series/TV shows/films are mixed with pictures and text files. I'd like a filter that would only show videos and folders. But I just can't find the correct syntax to combine the folders and videos filters.
Is it possible ?

**Comment by cboxdoerfer** [comment]
Can you give an example of what you want to achieve or describe it in more detail? Because this

> I'd like a filter that would only show videos and folders

can be easily achieved with:

```
folders: OR video:
```
But I'm not sure if that's really what you want.

**Comment by nick75e** [comment]
This is exactly what I was looking for!
For some reason, I went with a weird syntax mixing `ext:` and `AND`.
Your solution is so much simpler.
Thanks!
