### ISSUE TITLE
[BUG]Double entry in result list

### ISSUE THREAD

**Issue by Key-Snapper** [cboxdoerfer/fsearch#512]
**Describe the bug**
Sometimes files have 2 entries in the results list. 
I do not see a pattern why this happens. 
But this query "Tresor .7z" (with a space after Tresor) reproduces the error in different filters.

**Expected behavior**
no double entries

**Screenshots**
![fsearch result double entry](https://github.com/cboxdoerfer/fsearch/assets/84930208/f9db4bb3-56d6-471e-b7ff-bce91e73a486)

No doublette on the desktop:
![Schreibtisch wg fsearch](https://github.com/cboxdoerfer/fsearch/assets/84930208/2ee42a59-e568-4588-9bae-e6d82f25e85c)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1 Cinnamon, 
 - How you installed FSearch: PPA
 - Version: FSearch 0.2.3 (PPA-stable)
 - Output of `localectl status`:
       System Locale: LANG=de_DE.UTF-8
       VC Keymap: n/a
       X11 Layout: de
       X11 Model: pc105

**Additional context**

**Comment by kantheerava** [comment]
second that
FSearch 0.3.alpha0 (PPA-nightly)
Ubuntu 20.04

**Comment by Key-Snapper** [comment]
Sorry, my fault. I had a double entry in the search paths
