### ISSUE TITLE
Auto start after desktop logged in 

### ISSUE THREAD

**Issue by Ilhamkang** [cboxdoerfer/fsearch#517]
This app is ridiculously helpful for making a quick search of my files. Thank you for creating this awesome app! 

I use Ubuntu anyway. Everything just working fine on my laptop, but I found it lacks a minor thing for my needs. At the original state, the app should be launched manually to index all the files. And took a while to work perfectly. 

I'm wondering if there is an option to launch the app automatically after logging in to the desktop and running the index immediately in the background. So everything would be ready to use without a manual launch.

Well, it sounds similar to #327 though. 

How do you think?

**Comment by danielkrajnik** [comment]
This sounds more like a Desktop Environment feature than Fsearch. If you copy/symlink fsearch.desktop file into your `~/.config/autostart` folder it should autostart on login, no?

**Comment by Ilhamkang** [comment]
Thankw for the clue @danielkrajnik! you're right I can do the setting on the Startup Application Preferences. Adding this directory worked fine for me: `/usr/bin/fsearch` . I rarely use this startup app setting simply just to make the Gnome light (I'm aware that the term "light" is rather subjective for some people), so it is a bit forgotten.     
 
![image](https://github.com/cboxdoerfer/fsearch/assets/22653757/0b087859-8ab8-4558-ba88-f43949413946)

Sure, I will check the other features that might fit my preference and then will post it when I find it. Hopefully Gnome has that similar feature.

**Comment by nekohayo** [comment]
You can do this in GNOME using the "Tweaks" application:

![image](https://github.com/cboxdoerfer/fsearch/assets/479401/9aae87c0-c180-40be-87a2-720092767916)

As such, I would suggest closing this ticket.

**Comment by cboxdoerfer** [comment]
Yes, automatically starting the app should be handled by the desktop environment. But we can add a section to FSearch Wiki on how that can be done.
