### ISSUE TITLE
[BUG] Broken on latest arch linux with missing ` libicuuc.so.73`.

### ISSUE THREAD

**Issue by zw963** [cboxdoerfer/fsearch#523]
fsearch: error while loading shared libraries: libicuuc.so.73: cannot open shared object file: No such file or directory

```sh
 ╰─ $ sudo find -name 'libicuuc.so.*'
./lib32/libicuuc.so.74.2
./lib32/libicuuc.so.74
./lib/libicuuc.so.74.2
./lib/libicuuc.so.74
```

Both `fsearch` and `fsearch-git` not work.

Thanks.

**Comment by cboxdoerfer** [comment]
AUR packages need to be rebuilt when one of their dependencies get updated. Just rebuild or reinstall the FSearch package and everything should be working again.

**Comment by zw963** [comment]
Hi, i installed fsearch use `pacman`, not `yay`. it seem like never build when i installed whatever from both of them.

```
 ╰─ $ pacman -Qi fsearch
Name            : fsearch
Version         : 0.2.3-1
Description     : A fast graphical file search utility.
Architecture    : x86_64
URL             : https://cboxdoerfer.github.io/fsearch
Licenses        : GPL2
Groups          : None
Provides        : None
Depends On      : gtk3  icu  pcre2
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : fsearch-git
Replaces        : None
Installed Size  : 969.33 KiB
Packager        : lilac (on behalf of integral) <integral@murena.io>
Build Date      : Sun 06 Aug 2023 04:30:09 AM CST
Install Date    : Tue 19 Dec 2023 06:21:24 PM CST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by zw963** [comment]
> notify the package maintainers (seems to be `lilac` from integral?)

Don't know where this package come from, but, it updated today, and works now.

Thank you.
