### ISSUE TITLE
[BUG] Fsearch does not launch after arch update

### ISSUE THREAD

**Issue by bambirombi** [cboxdoerfer/fsearch#525]
**Describe the bug**
Fsearch does not launch after archlinux update.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - How you installed FSearch: [AUR](https://aur.archlinux.org/packages/fsearch)
 - Version [output of `fsearch --version`]: `fsearch: error while loading shared libraries: libicuuc.so.73: cannot open shared object file: No such file or directory`
 - Output of `localectl status`
 ```
localectl status
   System Locale: LANG=de_DE.UTF-8
   VC Keymap: de
   X11 Layout: de
   X11 Variant: winkeys
```

**Comment by cboxdoerfer** [comment]
AUR packages need to be rebuilt every time one of their dependencies gets updated. So rebuilding the FSearch package will fix that issue.

**Comment by bambirombi** [comment]
@cboxdoerfer Could you share any tutorial, please?

**Comment by swishkin** [comment]
Just found this, was wondering why fsearch wasn't working. Got it working by doing the below:

If using yay for AUR helper:

`yay fsearch`

```
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
```
Hit A, then reinstall as normal. It will rebuild the package and then install it.

Thanks @cboxdoerfer!
