### ISSUE TITLE
[BUG] FSearch's searching results include a duplicate file

### ISSUE THREAD

**Issue by hitbuyi** [cboxdoerfer/fsearch#533]
**Describe the bug**
The search resutls are duplicate 

**Expected behavior**
Remove the duplicate files

**Screenshots**
![FSearch_bug_duplcicate](https://github.com/cboxdoerfer/fsearch/assets/10301777/f90257e2-92d1-47a1-8043-1e37b6e91322)

**Desktop (please complete the following information):**
 - OS:  Ubuntu 20.04
 - How you installed FSearch:   built manually, snap

**Additional context**
This problem lasts for a long time. when I update the FSearch to latest version, the problem doesn't disappear.

**Comment by new-penguin** [comment]
I've had this bug before. I think I just deleted the index to fix it.

**Comment by cboxdoerfer** [comment]
You probably configured FSearch to index the same folders twice in the database settings.

**Comment by hitbuyi** [comment]
> You probably configured FSearch to index the same folders twice in the database settings.

I check the search directory,  and the search directory includes twice actually, thinks a lot.
this issue shall be closed.

**Comment by new-penguin** [comment]
> You probably configured FSearch to index the same folders twice in the database settings.

You're right. After some testing, that's the only way  I could reproduce it. Thanks. I love Fsearch.
