### ISSUE TITLE
[BUG] Cannot install on ubuntu 24.04

### ISSUE THREAD

**Issue by mcwindy** [cboxdoerfer/fsearch#548]
**Describe the bug**
Unable to install fsearch on ubuntu 24.04

**To Reproduce**
➜  sudo apt install ./fsearch_0.2.3-1+3.137_amd64.deb       
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'fsearch' instead of './fsearch_0.2.3-1+3.137_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 fsearch : Depends: libicu72 (>= 72.1~rc-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Expected behavior**
Install successfully

**Screenshots**
![image](https://github.com/cboxdoerfer/fsearch/assets/40684304/73b6a919-3638-4f52-b168-45e90fa01935)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - How you installed FSearch: Debian package

**Comment by gordonlau** [comment]
Second this. It is due to the fact that Ubuntu 24.04 no longer ships with the debian package  `libicu72`. It only comes with `libicu74` and `libicu-dev`. One possible workaround is to compile the software from source code.

**Comment by ryonakano** [comment]
Another possible workaround is to install from [Flathub](https://flathub.org/apps/io.github.cboxdoerfer.FSearch) instead of .deb

**Comment by ryonakano** [comment]
The .deb files available on [OpenBuildService](https://software.opensuse.org//download.html?project=home%3Acboxdoerfer&package=fsearch#manualDebian) are built for Debian so I guess it may not work on Ubuntu which is basically newer than Debian.

**Comment by gordonlau** [comment]
I tried both the debian version and ppa version but no luck on both. I think it is better to build the package from source code. The [build instruction](https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions) is clear and working well.

**Comment by mcwindy** [comment]
> I tried both the debian version and ppa version but no luck on both. I think it is better to build the package from source code. The [build instruction](https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions) is clear and working well.

Thanks! I have successfully compiled a runnable version using the build instructions.
