### ISSUE TITLE
Ubuntu 24.10  FSearch PPA does not have a release file - unable to install application

### ISSUE THREAD

**Issue by paulgir** [cboxdoerfer/fsearch#581]
This is one of three unrelated PPAs that I have encountered this problem on
It may be an Ubuntu problem

Err:13 https://ppa.launchpadcontent.net/christian-boxdoerfer/fsearch-daily/ubuntu oracular Release
  404  Not Found [IP: 2620:2d:4000:1::81 443]
Err:14 https://ppa.launchpadcontent.net/christian-boxdoerfer/fsearch-stable/ubuntu oracular Release
  404  Not Found [IP: 2620:2d:4000:1::81 443]
E: The repository 'https://ppa.launchpadcontent.net/christian-boxdoerfer/fsearch-daily/ubuntu oracular Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://ppa.launchpadcontent.net/christian-boxdoerfer/fsearch-stable/ubuntu oracular Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

# System Details Report
---

## Report details
- **Date generated:**                              2024-10-27 09:23:37

## Hardware Information:
- **Hardware Model:**                              ASUSTeK COMPUTER INC. PRIME B450M-A
- **Memory:**                                      8.0 GiB
- **Processor:**                                   AMD Ryzen™ 5 2600 × 12
- **Graphics:**                                    NVC1
- **Disk Capacity:**                               1.6 TB

## Software Information:
- **Firmware Version:**                            3211
- **OS Name:**                                     Ubuntu 24.10
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.0-9-generic

**Comment by cboxdoerfer** [comment]
Hi, thx for the report. I've just added support for this Ubuntu release, the builds should be ready in a few minutes.
