### ISSUE TITLE
[ISSUE] Can't install FSearch Stable on Fedora 41 through COPR repos.

### ISSUE THREAD

**Issue by ahmednasser293** [cboxdoerfer/fsearch#584]
DNF returns this:
Problem: conflicting requests
  - nothing provides libicuuc.so.73()(64bit) needed by fsearch-1:0.2.3-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:cboxdoerfer:fsearch

**Comment by Nasdrovia69** [comment]
Hi
Thank you for the solution work perfectly !!

**Comment by FlawlessCasual17** [comment]
@cboxdoerfer could you add this to the installation section for fedora users that are having issues with installing your app?
