### ISSUE TITLE
Locate File or Directory in Desktop Environment

### ISSUE THREAD

**Issue by Jetcser** [cboxdoerfer/fsearch#586]
**Is your feature request related to a problem? Please describe.**
Since there are many work files on my computer (>200,000), I often need to use fsearch to quickly locate files in the file manager. However, the current version of fsearch only supports opening the directory containing the file. I am using the Deepin distribution with the DDE desktop environment, and I use the _dde-file-manager --show-item /path/to/fileordir_ command to locate files (similar to GNOME's _nautilus --select /path/to/fileordir_ command).

**Describe the solution you'd like**
Can you add an option or function to call command to locate file/dir in desktop environment?

**Describe alternatives you've considered**
I have added the following function copy from _fsearch_window_action_open_generic()_ to call the _dde-file-manager --show-item_ command:

````C
// Edit fsearch-0.2.3/src/fsearch_window_actions.c
// Add Deepin file location function fsearch_window_action_open_de() after fsearch_window_action_open_generic() function,
// If not using Deepin desktop environment, still call fsearch_window_action_open_generic() to open directory

void
fsearch_window_action_open_de(FsearchApplicationWindow *win, bool open_parent_folder, bool triggered_with_mouse) {
    const guint selected_rows = fsearch_application_window_get_num_selected(win);
    if (selected_rows == 0) {
        return; 
    }

    GList *paths = NULL;
    if (open_parent_folder) {
        fsearch_application_window_selection_for_each(win, (GHFunc)collect_selected_entry_parent_path, &paths);
    } else {
        fsearch_application_window_selection_for_each(win, (GHFunc)collect_selected_entry_path, &paths);
    }

    // Check if the desktop environment is Deepin, in UOS v20, the value of $XDG_CURRENT_DESKTOP is "Deepin"; in Deepin v23, the value is "DDE"
    const char *desktop_env = g_getenv("XDG_CURRENT_DESKTOP");
    bool is_deepin = desktop_env && (g_strcmp0(desktop_env, "Deepin") == 0 || g_strcmp0(desktop_env, "DDE") == 0);

    if (is_deepin) {
        // Use Deepin file manager to open the path
        for (GList *l = paths; l != NULL; l = l->next) {
            char *path = (char *)l->data;
            g_autofree char *cmd = g_strdup_printf("dde-file-manager --show-item \"%s\"", path);
            int status = system(cmd);
            if (status != 0) {
                // If failed to open, handle the error if needed
                fprintf(stderr, "Failed to open path with Deepin file manager: %s\n", path);
            } else {
                // Proceed with further operations if needed
                action_after_open(triggered_with_mouse);
            }
        }
    } else {
        fsearch_window_action_open_generic(win, open_parent_folder, triggered_with_mouse);
    }

    g_list_free_full(paths, g_free);
}
```

And use this fuction here:

```
// Edit fsearch-0.2.3/src/fsearch_window_actions.c 
// Change fsearch_window_action_open_folder() ,using fsearch_window_action_open_de() to open directory.

static void
fsearch_window_action_open_folder(GSimpleAction *action, GVariant *variant, gpointer user_data) {
    FsearchApplicationWindow *self = user_data;
    fsearch_window_action_open_de(self, false, false);
}
```

**Comment by Jetcser** [comment]
Here's a demonstration of what the effect looks like:
![202410291616477208_20241030001626](https://github.com/user-attachments/assets/91488c60-ee9f-4f2d-8939-a96f85838cfd)

**Comment by Jetcser** [comment]
I just noticed that in the fsearch.c file, there is a piece of code that states that it is possible to set the folder open command in the fsearch.conf configuration file, something like this:

_[Applications]
folder_open_cmd=dde-file-manager --show-item "%s"_

But it doesn't work, and when the program is closed, this configuration is deleted. How do I use this setting correctly?
```
// Applications
        config->folder_open_cmd = config_load_string(key_file, "Applications", "folder_open_cmd", NULL);
```

**Comment by monoblaine** [comment]
Hey @Jetcser I was having the same problem and luckily find your issue. I'm using xfce and using the following method worked in my case:

1. Quit FSearch using <kbd>Ctrl</kbd> + <kbd>Q</kbd>
2. Open `~/.config/fsearch/fsearch.conf` with a text editor of your choice
3. Add the following at the end of the file:

```conf
[Applications]
folder_open_cmd=thunar {path_full}
```

reference: https://github.com/cboxdoerfer/fsearch/discussions/440#discussioncomment-4089803

Theoretically, using `dde-file-manager --show-item {path_full}` instead of `thunar {path_full}` should work in your case.

**Comment by Jetcser** [comment]
@monoblaine It works! Thank you very much!
