### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [cboxdoerfer/fsearch#6]
[An extra null pointer check is not needed](https://developer.gnome.org/glib/stable/glib-Memory-Allocation.html#g-free) in functions like the following.
- [list_model_get_value](https://github.com/cboxdoerfer/fsearch/blob/26a88029aa1ec3cd857a33333fc887a1ca84f6f3/src/list_model.c#L450)
- [search_query_free](https://github.com/cboxdoerfer/fsearch/blob/02ce6973d98eaa808d68b980b312f3f58bfa33ab/src/database_search.c#L331)

**Comment by cboxdoerfer** [comment]
Thx, will fix those.

**Comment by cboxdoerfer** [comment]
Fixed.
