### ISSUE TITLE
Folder Size reports 1 item less than actual

### ISSUE THREAD

**Issue by kklibo** [cboxdoerfer/fsearch#60]
The value in the Size column for Folder results is 1 less than the actual number of files in the folder (except for empty folders, which are correctly reported as having 0 Items).

Great work on this software so far, it has saved me hours of work.

**Comment by cboxdoerfer** [comment]
Fixed. Thanks for reporting.

**Comment by kklibo** [comment]
confirmed fixed in ba6aa54
