### ISSUE TITLE
Feature: add option to report file sizes in ^2 units, instead of ^10

### ISSUE THREAD

**Issue by kklibo** [cboxdoerfer/fsearch#61]
I usually configure kB to refer to 2^10 bytes instead of 10^3 bytes, mB = 2^20, not 10^6, etc.

I generally argue that this should be the default, but a checkbox in the options would work also.

**Comment by torbei** [comment]
I think this could be closed as well?
@cboxdoerfer

**Comment by cboxdoerfer** [comment]
Yes, you're right, thanks.

**Comment by kklibo** [comment]
I just tried this in fd5c867, it looks good.
