### ISSUE TITLE
Remember Window Size option doesn't work

### ISSUE THREAD

**Issue by kklibo** [cboxdoerfer/fsearch#62]
Edit->Preferences->Interface->Remember Window Size seems to have no effect: the window always resets to the original size on restart.

**Comment by kupiqu** [comment]
I can confirm this. 

To workaround it until it is fixed, I have set a rule in kwin (KDE user here) to force the initial window size to my taste.

Other window managers may have this functionality as well...

**Comment by cboxdoerfer** [comment]
Just tried to reproduce it in Openbox and Kwin, restoring window size works there as expected. @kklibo which window manager are you using.

And are you sure that FSearch gets shutdown properly? I.e. does `~/.config/fsearch/fsearch.conf` contain the entries `window_width=` and `window_height=` and do they have the proper values?

**Comment by kklibo** [comment]
I'm using KWin (KDE Plasma 5.8.5).

I checked window_width and window_height; When I close FSearch with the 'x' button in the corner of the window frame (as I normally do), they are not updated.
When I quit using the File->Quit menu option, everything works. They are updated and the window correctly restores its size on the next run.

In a quick test, all resize functionality with and without the Remember Window Size option checked seemed correct as long as only File->Quit was used to close the program.

**Comment by cboxdoerfer** [comment]
@kklibo, ah that explains it and I can confirm that. Will be fixed.

**Comment by kklibo** [comment]
confirmed fixed in ba6aa54
