### ISSUE TITLE
Clicking entries under the column "Path" should open the that path in file manager

### ISSUE THREAD

**Issue by rieje** [cboxdoerfer/fsearch#69]
Clicking entries under the column "Path" should open the that path in file manager, and ideally, highlight that entry automatically in the file manager (extremely useful when you have many files in that folder). This is the behavior in Everything Search and is very useful.

**Comment by cboxdoerfer** [comment]
Yes, sounds like a useful feature. I'll add that.

**Comment by AtilioA** [comment]
@cboxdoerfer I noticed this has been addressed in e44656de11dd6bc5836a1e02dd39af36ae9db9ea, you could close this issue.

**Comment by cboxdoerfer** [comment]
Thx, closing.
