### ISSUE TITLE
Add filters

### ISSUE THREAD

**Issue by bigbruno** [cboxdoerfer/fsearch#70]
Add filters before all, folders, files, adding filter by extensions:

Áudio (mp3, wma, ogg...)
Movies (avi, mkv, mp4...)
Documents (odt, doc, docx...)
PDF
Text file

**Comment by cboxdoerfer** [comment]
That's already on my todo list with a high priority. I just didn't have much spare time lately to work on FSearch.

**Comment by bigbruno** [comment]
Thank you anyway, fsearch is best search app, i don't know how is so fast, is crazy fast.

**Comment by cboxdoerfer** [comment]
This was added some time ago. Closing.
