### ISSUE TITLE
problem searching two words spread out in a path

### ISSUE THREAD

**Issue by kupiqu** [cboxdoerfer/fsearch#71]
somehow fsearch fails to find anything for: "fsearch config", even though there is a ".config/fsearch" folder at $HOME

if instead I search for "fsearch conf" then fsearch finds "fsearch.conf", so I guess the problem is in finding the two words if separated by "/", might it be?

**Comment by cboxdoerfer** [comment]
Yes, you are correct. By default FSearch doesn't search within the whole path but only in the name of each entry. However you can easily change that behaviour, just enable `Search -> Search in Path`

**Comment by kupiqu** [comment]
Ooops, I didn't realize the search path option was for that, sorry (somehow I thought it was to limit the search within a given path)... It works great!
