### ISSUE TITLE
Add "Copy full path of file" to context menu when right clicking on file

### ISSUE THREAD

**Issue by cenobite1** [cboxdoerfer/fsearch#74]
Add "Copy full path of file" to context menu when right clicking on file

**Comment by SGHphoto** [comment]
I use this extremely often in the windows counter part.

**Comment by cboxdoerfer** [comment]
Thankfully added by @torbei

**Comment by cenobite1** [comment]
Thanks, but just for the cosmetics, the menu entry language should follow the system language, right now it seems hardcoded to english.

**Comment by cboxdoerfer** [comment]
@cenobite1, it's not hard coded, the new entry just hasn't been translated yet. I can only provide German translations, for every other language I rely on others to help.

**Comment by cenobite1** [comment]
thx, looks much better now
