### ISSUE TITLE
Pressing Enter opens current selected file instead of doing a new search

### ISSUE THREAD

**Issue by robert1826** [cboxdoerfer/fsearch#76]
with "search as you type" option deselected I can type the query string and then press enter to do the search ... then I can select a file and hit enter again to open the selected file and that's expected, now when i want to do another search I click on the text input area and type the 2nd query string then I hit enter again .. but this time it opens the previously selected file instead of doing a new search.
I believe that this is not be the expected behavior from my point of view anyway.

**Comment by cboxdoerfer** [comment]
Confirmed.

**Comment by robert1826** [comment]
thanks alot :)
