### ISSUE TITLE
add --new-window flag

### ISSUE THREAD

**Issue by udiNur** [cboxdoerfer/fsearch#79]
hi.
first, hi love this FSearch. Unfortunately, I only encountered her today :(

can you pls add '--new-window' flag, in order to allow me to launch new window when i'm trying to find number of different files at ones?

thx

P.S. Will you build a CLI interface? It is much faster than any other terminal search tool that i know (locate, find)..

**Comment by cboxdoerfer** [comment]
Sure. There are quite a few flags I'd like to add and `--new-window` is one of them.

> Will you build a CLI interface?

Yes probably, however it's not a high priority for me right now. But maybe once I've finished the initial work on libfsearch, maybe someone else will build a CLI on top of that.

**Comment by cboxdoerfer** [comment]
New window flag was added some time ago. Closing.
