### ISSUE TITLE
Current location of ongoing index in status bar

### ISSUE THREAD

**Issue by nazar2sfive** [cboxdoerfer/fsearch#8]
When I ask fsearch to update my index and as it curls through my harddisk only moving circle is shown in the status bar. It would be really great if it could show me the location where index is going on. I want to see the path as the indexing is going on.

**Comment by cboxdoerfer** [comment]
Good idea, I'll add that.

**Comment by cboxdoerfer** [comment]
Hi, just added that feature. Please let me know if it works like expected.

**Comment by nazar2sfive** [comment]
It works great. Just a suggestion though - if you could display by aligning text to left than center. Or put the path in status bar with alignment to left.

**Comment by cboxdoerfer** [comment]
Hi, thx for the feedback. Moved the text to the status bar and it's now left aligned, so it should be easier to read.

**Comment by nazar2sfive** [comment]
superb exactly what i needed. Thank you.
