### ISSUE TITLE
`configure` script fails

### ISSUE THREAD

**Issue by enedil** [cboxdoerfer/fsearch#80]
Hi! I'm on Fedora 25 with gcc 6.3.1. I get this error while executing `configure`:

    ./configure: line 6384: syntax error near unexpected token `-std=c11,'
    ./configure: line 6384: `AX_CHECK_COMPILE_FLAG(-std=c11, CFLAGS+=" -std=c11" ,'

If I comment this problematic line out, I get message that my compiler doesn't support c11 which is not true.

**Comment by cboxdoerfer** [comment]
Looks like you are missing the autoconf archive package. Did you follow the [build instructions](https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions) and install all the packages listed there?

**Comment by enedil** [comment]
@cboxdoerfer yeah, you're right. Sorry for the hassle.

**Comment by cboxdoerfer** [comment]
No problem.
