### ISSUE TITLE
cron job for updating db

### ISSUE THREAD

**Issue by p0nti** [cboxdoerfer/fsearch#82]
Is there any commandline switch for having fsearch update its db ?
That way a cron job could be added and run hourly

Thanks

**Comment by cboxdoerfer** [comment]
Duplicate #73

**Comment by cboxdoerfer** [comment]
No, but it's planned.

**Comment by unpairedliabilitylibrarian** [comment]
Hi Christian,
first of all thank you so much for fsearch! It's my favorite linux search utility (came from windows with everything) and works fine :)
Over two years ago, you said this command-line option to update the database via cronjob is planned. Is it already implemented or is there a way to auto update every x minutes the database in background?

Thank you!
