### ISSUE TITLE
Improve hiDPI support

### ISSUE THREAD

**Issue by Calinou** [cboxdoerfer/fsearch#86]
fsearch does provide some sort of hiDPI support, but it is far from ideal: the menus are not spaced enough, their dropdowns don't cast drop shadows like they do in Qt 5-based applications and the icons are too small. It's also much harder than usual to resize the columns, because the dragging areas' sizes do not increase with scaling.

This was tested with a build of https://github.com/cboxdoerfer/fsearch/commit/0871f542dc6e50c88cc1fdce5c158b4d3cc2f49e on Manjaro Linux using KDE Plasma 5.9.5. The system theme is Breath, applied on native, GTK+2 and GTK+3 applications, but this issue also happens with the Breeze theme (the Plasma default).

Some screenshots (fsearch and, for comparison, a Qt 5-based application, Krita) with 200% scaling can be seen below.

![fsearch_kde](https://cloud.githubusercontent.com/assets/180032/26407843/7ed5b31e-409c-11e7-9b91-4f7f6559fef0.png)

![krita_kde](https://cloud.githubusercontent.com/assets/180032/26407849/84c35c5e-409c-11e7-9b61-c21a96efd23e.png)

**Comment by cboxdoerfer** [comment]
What's the value of `gsettings get org.gnome.desktop.interface scaling-factor`?

**Comment by cboxdoerfer** [comment]
Maybe you might also want to try setting `GDK_SCALE=2` in your environment. Afaik GTK+ doesn't respect other values.

**Comment by cboxdoerfer** [comment]
@Calinou I just tried it and using `GDK_SCALE=2` gives the proper result:
![2017-05-24-175636_940x858_scrot](https://cloud.githubusercontent.com/assets/6108388/26412847/5edb4642-40aa-11e7-8dec-b90a9d53fd64.png)

**Comment by cboxdoerfer** [comment]
No reponse, so I guess `GDK_SCALE` did the trick. If not let me know, then I'll reopen the issue again.
