### ISSUE TITLE
Install on Linux Mint 17.3

### ISSUE THREAD

**Issue by mttr402** [cboxdoerfer/fsearch#87]
Is there a way to compile it to run on Mint 17.3. I am so looking forward to having a fast search. Currently using catfish and angrysearch. Both are useful but not anything like Search Everything on windows.

**Comment by cboxdoerfer** [comment]
No, currently FSearch depends on GTK+ and GLib versions which aren't available in Linux Mint 17.3. However I'm currently evaluating to lower the dependencies if it doesn't lead to any major feature loss.

**Comment by cboxdoerfer** [comment]
Since those distributions are now basically EOL, I'm closing this issue. I don't have much time for development work anyway, so I rather focus on newer versions.
