### ISSUE TITLE
Multiple-selection for Include/Exclude directory browsers

### ISSUE THREAD

**Issue by 0ion9** [cboxdoerfer/fsearch#92]
Just had to setup fsearch from scratch on another computer.
Noticed it's kind of tedious to throw a bunch of directories sharing a parent (eg. direct leaf directories of $HOME ) into Include or Exclude section; you have to bring up the dialog, select a directory, confirm. NDIRS times. 

Supporting multiple selection would drop that to 1 time.

**Comment by cboxdoerfer** [comment]
Yes I agree, reworking the whole file/folder selection in the database dialog is already on my todo list.

**Comment by Shadowfire-Elite** [comment]
Hi, when will this issue be resolved?
I'm still unable to select multiple folders.

**Comment by cboxdoerfer** [comment]
@Shadowfire-Elite The plan is to fix it before the 0.2 release, which is about to be released in the next two weeks or so.

**Comment by cboxdoerfer** [comment]
Selecting multiple folders is now possible in the development builds.

**Comment by Shadowfire-Elite** [comment]
Alright, thank you!
