### ISSUE TITLE
Add Ubuntu 17 support to the ppa

### ISSUE THREAD

**Issue by eugenesvk** [cboxdoerfer/fsearch#93]
First of, thanks a lot for an awesome clone of Everything! Have been waiting for a long time for such an app to appear on Linux
Would you please add support for Ubuntu Zesty in the ppa to avoid this error?
>W: The repository 'https://launchpad.net/~christian-boxdoerfer/+archive/ubuntu/fsearch-daily zesty Release' does not have a Release file.

I built from source and it seems to be working just fine, but it would be much more convenient to have it part of a ppa for future updates.
Thanks

**Comment by cboxdoerfer** [comment]
Hm, weird. I just tried it in a virtual machine and the FSearch PPA works fine with Zesty there. Can you paste the commands you used to add the PPA?

**Comment by eugenesvk** [comment]
Hm, your'e correct, sorry, I had copy&pasted a wrong PPA

**Comment by cboxdoerfer** [comment]
No problem.
