### ISSUE TITLE
exclude regex

### ISSUE THREAD

**Issue by msajadi832** [cboxdoerfer/fsearch#94]
I have this folders:
~/Documents/www/ticket/vendor
~/Documents/www/fire/vendor

and i want to exclude all "vendor" folders.
How can do it?

In Edit -> Preferences -> Database -> Exclude files I set this:
*/vendor/*
Is this correct?

**Comment by cboxdoerfer** [comment]
You just need to insert `vendor`. `/vendor/` won't match anything, because `/` is a forbidden character in file/folder names.
