### ISSUE TITLE
There's no obvious way to use a space in a regexp search

### ISSUE THREAD

**Issue by detly** [cboxdoerfer/fsearch#98]
Entering `(\d{2})\.(\d{2})\.(\d{2})\.mp4` into the search box finds a bunch of files ending with eg. `10.00.01.mp4`. That's kind of what I expected.

Entering `([1-9]\d{3})-(\d{2})-(\d{2}) (\d{2})\.(\d{2})\.(\d{2})\.mp4` find a whole bunch of `.jpg` files as well as the results from the former search. I'm guessing it's splitting the search expression at the space and providing the union of the results of both?

But I can't figure out how to make the space be treated as part of the regular expression. I've tried `[ ]`, `( )`, `\ `... they all result in zero results.

**Comment by detly** [comment]
`*sigh*` answered my own question: `\s` works. Still not perfect because I think it includes tabs and newlines, but I'll leave it to you as to whether that's a workaround or you're fine with it.

**Comment by cboxdoerfer** [comment]
Good catch, thank you. That's of course a bug and needs to be fixed - splitting the search expression by space shouldn't happen in regex mode.
